jenkinsci/blueocean-plugin

- blueocean-dashboard/src/main/js/components/PipelineRowItem.jsx
> Update PipelineRowItem - variable name fix

- blueocean-dashboard/src/main/js/OrganisationPipelines.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
Via SSE events. Related to issue [UX-439](https://cloudbees.atlassian.net/browse/UX-439). 
__Short Video ...__
[![Video](http://img.youtube.com/vi/Kamnpoalobo/maxresdefault.jpg)](https://youtu.be/Kamnpoalobo)
@reviewbybees 
Note that delete operation events are currently not working - [JENKINS-35153](https://issues.jenkins-ci.org/browse/JENKINS-35153).
> [UX-439] Auto-update pipeline listing page

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineNodeImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineNodeTest.java
- blueocean-rest/README.md
.
.
.
@reviewbybees 
- thresholdInKB wuery parameter to override 150KB default
- use start=0 query parameter to fetch full log
> UX-510# Serve last 150 KB (Default) logs

- blueocean-dashboard/package.json
- blueocean-dashboard/pom.xml
Related to issue [UX-242](https://cloudbees.atlassian.net/browse/UX-242). 
The main changes for review are in https://github.com/jenkinsci/sse-gateway-plugin/pull/2 and in the new [blueocean-acceptance-test](https://github.com/cloudbees/blueocean-acceptance-test) repo itself.
Once we agree that the above changes are ok I'll release proper versions of the plugins/packages and update.
@reviewbybees
> [UX-242] Tweaks to help with acceptance tests

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanRootAction.java
- blueocean-web/src/main/java/io/jenkins/blueocean/BlueOceanUI.java
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
> UX-525# Make BlueOceanUI url base configurable

- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
- blueocean-dashboard/src/main/less/extensions.less
- blueocean-dashboard/src/test/js/activity-spec.js
- blueocean-dashboard/src/test/js/run-details-changes-spec.js
Related to issue # UX-527 and UX-540. 
* Add new column to Run - Changes tab
* Fix bug where wrong message displayed for some Runs in activity tab
> feature/ux 527 - column addition and bug fix

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
> UX-533# Don't recurse in to sub folders

- bin/setup.sh
- bin/start.sh
- install.sh
> The beginning of the blue ocean installer

- blueocean-rest-impl/pom.xml
- pom.xml
Adds Jacoco test reports to blueocean-rest-impl.
We have 79% coverage atm.
> [Ux-449] Jacoco test coverage

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineContainer.java
> UX-550# Pipeline API: /pipelines

- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
Related to issue # UX-529. 
* Add some logic to filter out the folders
I wanted to experiment with a new concept in this PR which is using Immutable.js Record subclasses. I think it would be an improvement if our data was typed, mainly for use of debugging but also giving us the ability to bake some relevant methods directly into the data itself.
@reviewbybees
> feature/ux 529 - filter out folders from the Pipelines view

- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-web/package.json
Related to issue # UX-531. 
* Update the UI to use the new CSS classes for buttons
> feature/ux 531 - new button styles

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineNodeGraphBuilder.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineNodeTest.java
> UX-563# Run.getExecution() nullability handled

- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/PullRequest.jsx
Related to issue - no bug filed. 
* The links to the Run Details screen from the Branches and Pull Requests tabs were broken since they were not updated when the URL schemes were changed.
@reviewbybees
> bug/fix broken links to Branches and Run Details

- blueocean-dashboard/.storybook/head.html
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
Related to issue # UX-546. 
. @i386 should do this to remove material font
@reviewbybees
> UX-546 no downloading remote material icons

- .eslintrc
- blueocean-dashboard/.eslintrc
- blueocean-dashboard/src/main/js/components/Runs.jsx
Related to issue # JENKINS-35690. 
* Use new component that will animate build progress
Note: requires merge of jenkinsci/jenkins-design-language#47 and publish of new JDL before merge.
@reviewbybees
> feature/jenkins 35690 - update activity tab with build progress indicator

- blueocean-dashboard/pom.xml
Related to issue [JENKINS-35711](https://issues.jenkins-ci.org/browse/JENKINS-35711). 
Depends on:
* https://github.com/jenkinsci/sse-gateway-plugin/pull/3
* https://github.com/jenkinsci/pubsub-light-module/pull/1
> New SSE Gateway plugin with fix for JENKINS-35711

- blueocean-dashboard/src/test/js/pipeline-graph-converter-spec.js
Small cleanup that's been TODO for a while, I just remembered about it due to working on the related code in JDL :)
@reviewbybees
> remove-deprecated-jdl-consts - just a small cleanup that's a bit overdue

- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-dashboard/src/main/js/redux/index.js
- blueocean-dashboard/src/main/js/redux/reducer.js
Try-catch-fail.
@reviewbybees esp. @scherler
> FIX errors being swallowed

- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/main/js/components/Step.jsx
- blueocean-web/package.json
Related to issue # . 35820
.
.Implement click on pipelineGraph will trigger the change of the steps
.
@reviewbybees
> Hotfix/jenkins 35820 Implement click on pipelineGraph will trigger the change of the steps

- blueocean-dashboard/package.json
.
.continue on lint and not stop watching
.
@reviewbybees
> [hotfix/lintWatchEnhanced] continue on lint and not stop watching

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
Use a better animation when displaying the 'modal' view
@reviewbybees esp. @cliffmeyers @i386
> Set modal to use expand-in animation

- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineSearch.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineContainer.java
.
.
.
@reviewbybees 
- Gives flattened view of all pipelines
- Removed /rest/pipelines API
> JENKINS-35997# Use search API to get pipelines across org

- blueocean-web/src/main/js/try.js
Related to issue [JENKINS-35993](https://issues.jenkins-ci.org/browse/JENKINS-35993). 
> [JENKINS-35993] Fix Blue Ocean button for when no context root

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineRunImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/MultiBranchTest.java
> JENKINS-36004# ChangeSet order fixed.

- blueocean-dashboard/src/main/js/components/PipelineRowItem.jsx
- blueocean-dashboard/src/test/js/pipeline-spec.js
Related to issue # JENKINS-35901. 
* Use "fullName" in pipeline list so folder names are displayed
@reviewbybees
> feature/JENKINS-35901 - show fullName in pipeline list

- blueocean-dashboard/src/main/js/components/LogToolbar.jsx
> reduce open log icon size on result

- blueocean-dashboard/package.json
- blueocean-web/package.json
Bump dependancy version for JDL
@reviewbybees
> Bump JDL dep

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueMultiBranchPipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueQueueContainer.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueQueueItem.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRunContainer.java
@vivek I can't get it use WebMethods on /. Get 404's
@reviewbybees
> [JENKINS-35797] API for running pipelines

- blueocean-commons/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-plugin/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- pom.xml
Related to issue #JENKINS-36101 
I wish we didn't have to list contributors like this, it should be from scm. 
@reviewbybees
> alpha version string, and some scm details

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineStepContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineNodeTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
> JENKINS-35771# Fixed steps log API

- pom.xml
In order in which it appears in github. 
@reviewbybees
> Contributor list up to date with github so far

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
- blueocean-rest/README.md
> [JENKINS-35863] Refactor log functions and add the ability to download it

- .dockerignore
- Dockerfile
Currently the docker build is not working, since the impl rest plugin is not included, and the blueocean plugin seems to have a funny name in the maven build.
Also I changed the `COPY` commands to `ADD`, since `COPY` is deprecated.
> Fixed docker build.

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineFactory.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
@michaelneale @imeredith 
@reviewbybees
> JENKINS-36207# Make BluePipeline extensible

- blueocean-dashboard/src/main/js/components/LogToolbar.jsx
@i386 [Screen shot](https://issues.jenkins-ci.org/secure/attachment/33135/Screen%20Shot%202016-06-27%20at%201.50.33%20PM.png)
.
.
.
@reviewbybees
> [JENKINS-35888] Add download link for log file

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BranchImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetResource.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineRunImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/MultiBranchTest.java
> JENKINS-36154# Link related fixes

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/MultiBranchTest.java
Lets us conditionally run problematic problems 
cc @vivek 
@reviewbybees
> conditional assumptions for running problematic multibranch tests

- blueocean-dashboard/src/main/js/api/Branch.js
- blueocean-dashboard/src/main/js/components/RunPipeline.jsx
Related to issue [JENKINS-36261](https://issues.jenkins-ci.org/browse/JENKINS-36261). 
> [FIX JENKINS-36261] Toast run queuing based on run response Vs queue status events

- js-extensions/package.json
- js-extensions/src/ExtensionStore.js
Related to issue N/A . 
. Fix issue with extension point bundle loading timing
@reviewbybees esp. @cliffmeyers
> Fix issue with extension point bundle loading timing

- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ExtensionClassImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineFolder.java
Adds supports for [Capability annotation](https://github.com/jenkinsci/capability-annotation) with /rest/classes API. 
@reviewbybees
> JENKINS-35884# Capability annotation support

- blueocean-commons/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-personalization/pom.xml
- blueocean-plugin/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
Alpha release is not showing up in experimental UC
@reviewbybees
> update centre requires url to wiki to deploy

- blueocean-rest-impl/pom.xml
> [JENKINS-35843] Support PR's from origin

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineRunImpl.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
Changed stop() to return BlueRun. Uses TreeResponse annotation
@reviewbybees
> [JENKINS-36513] Use TreeResponse for return of stop()

- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ActionProxiesImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
- blueocean-rest/pom.xml
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueExtensionClass.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueFavorite.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueMultiBranchPipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueOrganization.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineFolder.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineNode.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineStep.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueQueueItem.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueUser.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/GenericResource.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/Resource.java
> JENKINS-36376# Annotate model classes with @Capability

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BluePipelineFactory.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FavoriteImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/hal/Link.java
cc: @cliffmeyers @imeredith 
@reviewbybees
> JENKINS-36488# Use LinkResolver to get favorite item

- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/MultiBranchPipelineQueueContainer.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/AbstractRunImplTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/MultiBranchTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
This PR allows a run to be replayed
> [JENKINS-35881] replay a run

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FavoriteContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FavoriteImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/util/FavoriteUtil.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/MultiBranchTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
cc: @imeredith @cliffmeyers 
@reviewbybees
> JENKINS-36580# PUT .../pipelines/:id/favorite/ enhancements

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/MultiBranchPipelineImpl.java
> JENKINS-36489# NPE fix

- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-events/src/main/java/io/jenkins/blueocean/events/BlueMessageEnricher.java
**Decription**
This is a regression fix, a few different things. cc @cliffmeyers @vivek 
Related to https://issues.jenkins-ci.org/browse/JENKINS-36675
@reviewbybees
> Fix to launch multibranch

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/LinkResolverTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
> JENKINS-36668# Fixed

- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/PipelineRowItem.jsx
- blueocean-dashboard/src/main/js/components/PullRequest.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-personalization/src/main/js/jenkins-js-extension.yaml
- blueocean-plugin/src/test/java/io/jenkins/blueocean/jsextensions/JenkinsJSExtensionsTest.java
**Decription**
This adds some extension points to various screens in the UI.
The change is completely inert until someone actually makes use of the extension points. I did have one XP registered for testing previously and the JenkinsJSExtensionsTest has been updated to pass.
@reviewbybees
> feature/jenkins 36586 - extensions table actions

- PULL_REQUEST_TEMPLATE
**Decription**
Otherwise the reviewer probably does not know what/how to test the PR.
> Added a submitter checklist item for providing test instructions for the reviewer

- blueocean-dashboard/src/main/js/components/RunDetailsTests.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
* Fix bad encoding in REST URL by creating URL based off HAL link
* **Looking for feedback on this approach!** it seems a huge improvement in simplification of code. cc @kzantow @tfennelly @scherler @sophistifunk 
* I don't have a test for this yet... I'm going to try to test our actions stuff. The actions are tangled together, and should be simpler to test than they are right now.
@reviewbybees
> bug/JENKINS-36674 - test results not found

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetResource.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineRunImpl.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueChangeSetEntry.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
**Decription**
Adds urls for changeset commits. ie to github.
No extra tests for this as I can't make it generate a url when doing it locally.
@reviewbybees
> [JENKINS-35868] changeset url

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BranchImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/TestProject.java
**Decription**
GET /organizations/:id/pipelines/:id/
See in response if _class value is io.jenkins.blueocean.service.embedded.rest.PipelineImpl.
@reviewbybees 
cc @cliffmeyers
> JENKINS-36728# Pipeline job's _class fix

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/jsextensions/JenkinsJSExtensions.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ExtensionClassContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ExtensionClassImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueExtensionClassContainer.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueExtensionClassMap.java
**Decription**
Already covered by test. But if you want to do follow this: https://github.com/jenkinsci/blueocean-plugin/blob/task/JENKINS-36542/blueocean-rest/README.md#get-detailed-map-of-all-given-classes
@reviewbybees
> JENKINS-36542# API to map of class details for multiple classes

- blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
- blueocean-dashboard/src/main/js/config.js
- blueocean-dashboard/src/main/js/redux/actions.js
**Decription**
To test: view the test results from a project that properly archived them. Not sure how best to test this redux bit, happy to add a test if there's a good example.
@reviewbybees
> JENKINS-36829 - test results fetch URL incorrect

- blueocean-web/package.json
- blueocean-web/src/main/js/DevelopmentFooter.jsx
**Decription**
part 2 of https://github.com/jenkinsci/blueocean-plugin/pull/375 Fixing the underlying lib https://github.com/scherler/git-info/commit/35a580ed8197a8be109e7fe7341d834746241c8d
@reviewbybees
> Jenkins 36903

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/util/FavoriteUtil.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- blueocean-rest/README.md
**Decription**
1. Favorite a multi-branch project and a branch
2. favorite each of the projects created above. [See doc favorite multi-branch](https://github.com/jenkinsci/blueocean-plugin/tree/bug/JENKINS-36967/blueocean-rest#favorite-a-multi-branch-pipeline)
2. Check _link.self.href of the response, it should be same as the path in above step
3. Get user favorites, each favorite json object's _link.self.href should point to  the value in step 2 above. [see  doc to get user favorites](https://github.com/jenkinsci/blueocean-plugin/tree/bug/JENKINS-36967/blueocean-rest#fetch-user-favorites)
@reviewbybees
> JENKINS-36967# Favorite object self link fix

- blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
- blueocean-dashboard/src/test/js/testResult-spec.js
**Decription**
Show 'fixed' tests even if if all tests are passing and the encouraging message is displayed. Addresses: [JENKINS-36336](https://issues.jenkins-ci.org/browse/JENKINS-36336)
NOTE: this also now addresses: [JENKINS-36930](https://issues.jenkins-ci.org/browse/JENKINS-36930)
@reviewbybees
> [FIXED JENKINS-36336] Always show fixed tests if there are some

- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/Step.jsx
- blueocean-dashboard/src/main/less/core.less
- blueocean-dashboard/src/main/less/variables.less
- blueocean-web/package.json
**Decription**
https://issues.jenkins-ci.org/browse/JENKINS-36169
@reviewbybees
> [JENKINS-36169] Override resultItem css to remove border and padding

- README.md
- blueocean-analytics-tools/LICENSE.txt
- blueocean-analytics-tools/README.md
- blueocean-analytics-tools/gulpfile.js
- blueocean-analytics-tools/package.json
- blueocean-analytics-tools/pom.xml
- blueocean-analytics-tools/src/main/java/io/jenkins/blueocean/analyticstools/AnalyticsTools.java
- blueocean-analytics-tools/src/main/js/rollbar.js
- blueocean-analytics-tools/src/main/resources/index.jelly
- blueocean-analytics-tools/src/main/resources/io/jenkins/blueocean/analyticstools/AnalyticsTools/header.jelly
- blueocean-plugin/pom.xml
- blueocean-web/src/main/java/io/jenkins/blueocean/BlueOceanUI.java
- blueocean-web/src/main/java/io/jenkins/blueocean/BluePageDecorator.java
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
- pom.xml
**Decription**
@i386 @michaelneale RollBar support in. To test:
* mvn hpi:run --> rollbar JS code is not injected on dashboard page
* mvn hpi:run -DBLUEOCEAN_ROLLBAR_ENABLED=true --> enables rollbar and relevant JS code is injected on dashboard page
From what I understand this should be good enough to deploy rollbar on dogfood instance.
@reviewbybees 
Also includes infrastrucutre to inject HTML head tags and HTTP header by any plugin that implements BluePageDecorator
and appropriate jelly files.
> JENKINS-36884# Analytics-tools plugin to integrated rollbar

- blueocean-dashboard/src/main/less/core.less
> [JENKINS-37022] add a little spacing to actions on Branches tab

- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- pom.xml
See [JENKINS-36238](https://issues.jenkins-ci.org/browse/JENKINS-36238)
Depends on
* https://github.com/jenkinsci/sse-gateway-plugin/pull/7 and
* https://github.com/jenkinsci/pubsub-light-module/pull/3
Two possible tests ... minimum of 1:
1. **Min**: Verify that there are no regressions i.e. that SSE based notifications still work on the browser e.g. run a build and toasts etc popup .. build run animations appear.
1. **Bonus**: Setup a http proxy server that redirects requests to the Jenkins instance you are testing against. Connect the browser to Jenkins via this proxy - the activity page of a job ... establish a session etc. Kill the proxy and then, in another browser window/tab, connect to the activity page for the same job (not via the proxy of course), start a run and let it finish …
> [JENKINS-36238] New SSE client gateway with store and forward support

- pom.xml
Sorry ... another small fix trying to get ATH running, this time fixing the test env checks I tried to make last time, but screwed up. Sorry about the noise ... just as well guys are on vacation 😈
> Updated SSE Gateway to 1.8 to fix ATH (v2 grrrrr)

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/main/js/components/Step.jsx
No associated JIRA ... simple HTML `class` tweaks that we hope will help make the ATH tests run a little more predictably.
See ATH PR that uses these ... https://github.com/jenkinsci/blueocean-acceptance-test/pull/22
__N/A__
__N/A__
> Ath test help changes

- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
See [JENKINS-36021](https://issues.jenkins-ci.org/browse/JENKINS-36021).
> Add a little noscript about JavaScript

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ExtensionClassContainerImpl.java
classes api now resolves any class in Jenkins via uberClassLoader
See [JENKINS-37321](https://issues.jenkins-ci.org/browse/JENKINS-37321).
Tested with multibranch jobs which was a failing case
> [FIXED JENKINS-37321] Source class details from uberclassloader

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/StoppableRun.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
See https://issues.jenkins-ci.org/browse/JENKINS-36976
Not sure if it applies to API only changes but anyways, provide link to how to run test harness. 
> JENKINS-36976# stop API with blocking call feature

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineFolder.java
See https://issues.jenkins-ci.org/browse/JENKINS-36376.
Call classes API: 
GET http://localhost:8080/jenkins/blue/rest/classes/?q=io.jenkins.blueocean.service.embedded.rest.AbstractPipelineImpl,io.jenkins.blueocean.rest.impl.pipeline.PipelineImpl,io.jenkins.blueocean.rest.impl.pipeline.BranchImpl
- For class io.jenkins.blueocean.service.embedded.rest.AbstractPipelineImpl, it's capabilities should include hudson.model.Job but not io.jenkins.blueocean.rest.model.BlueBranch and org.jenkinsci.plugins.workflow.job.WorkflowJob
- For class io.jenkins.blueocean.rest.impl.pipeline.PipelineImpl, it's capabilities should include hudson.model.Job, org.jenkinsci.plugins.workflow.job.WorkflowJob but not io.jenkins.blueocean.rest.model.BlueBranch.
- For class …
> JENKINS-36376# Adding missing capabilities

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsTests.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
RunDetailsTestView: Uncaught TypeError: Cannot read property 'self' of undefined
See [JENKINS-37505](https://issues.jenkins-ci.org/browse/JENKINS-37505).
AT https://github.com/jenkinsci/blueocean-acceptance-test/pull/25
> Jenkins 37505 RunDetailsTestView: Uncaught TypeError: Cannot read property 'self' of undefined

- blueocean-dashboard/src/main/js/components/LogToolbar.jsx
- blueocean-dashboard/src/main/less/core.less
See [JENKINS-37075](https://issues.jenkins-ci.org/browse/JENKINS-37075).
> [JENKINS-37075] Step heading should be bold to match pipeline graph

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
See [JENKINS-36773](https://issues.jenkins-ci.org/browse/JENKINS-36773).
To set up AT for this edge case is too expensive (I need to create the infrastructure to create folder  projects etc.) -> will come with https://issues.jenkins-ci.org/browse/JENKINS-36660
> [JENKINS-36773] Pipeline name does not have spaces between slashes

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
> [hotfix/preventNPE] Prevent NPE

- blueocean-dashboard/src/main/js/components/PullRequest.jsx
See [JENKINS-36676](https://issues.jenkins-ci.org/browse/JENKINS-36676).
> [JENKINS-36676] PullRequest.jsx needs to cope with branch names that are non alpha (eg feature/thing)

- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
Commit messages are missing on the activity view
See [JENKINS-37021](https://issues.jenkins-ci.org/browse/JENKINS-37021).
I will add AT for this as soon I implemented multiBranch support for AT
> [JENKINS-37021] Commit messages are missing on the activity view

- blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
- blueocean-dashboard/src/test/js/run-details-changes-spec.js
See [JENKINS-35890](https://issues.jenkins-ci.org/browse/JENKINS-35890).
https://youtu.be/ONDs9iZkYwY
> [JENKINS-35890] Developer can click the commit ID on the Changes tab of the Run result screen to view the full commit details

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
See [JENKINS-37605](https://issues.jenkins-ci.org/browse/JENKINS-37605).
> [JENKINS-37605] Name of pipeline has encoding problem on run modal

- blueocean-dashboard/src/main/js/components/records.jsx
See [JENKINS-37640](https://issues.jenkins-ci.org/browse/JENKINS-37640).
Add artifacts to runRecord.
https://github.com/jenkinsci/blueocean-acceptance-test/pull/27
> [JENKINS-37640] Add artifacts to the runRecord

- blueocean-dashboard/src/main/js/components/stories/index.js
See [JENKINS-37544](https://issues.jenkins-ci.org/browse/JENKINS-37544).
It's storybook, which is tests, which is why there were no tests written.
To test: run storybook from dashboard.
> [FIX JENKINS-37544] - storybook updates

- blueocean-dashboard/src/main/js/util/UrlUtils.js
See [JENKINS-37712](https://issues.jenkins-ci.org/browse/JENKINS-37712).
Tests covered in pending ATH test cases.
To test: create a multibranch project and in the repo, create branch with a slash in the name - e.g. `hotfix/JENKINS-37712`, verify you can access the run details for that branch.
@jenkinsci/code-reviewers @reviewbybees esp. @scherler
> [FIX JENKINS-37712] - branch encoding was wrong

- blueocean-dashboard/src/main/js/redux/actions.js
See [JENKINS-37799](https://issues.jenkins-ci.org/browse/JENKINS-37799).
I'm going to write some tests for this whole module, but for now need to get this fixed for the beta, it is partially covered in the ATH (which is all passing locally).
To test this, create a pipeline (not multibranch) using the provided script and follow along with the build, make sure it ends as appropriate.
```
node {
echo "42"
sleep 5
echo "done"    
}
```
> [FIX JENKINS-37799] issue matching individual pipelines

- blueocean-dashboard/src/main/js/redux/actions.js
See https://issues.jenkins-ci.org/browse/JENKINS-37826
##Manual Test instructions
* Create matrix style project matrix1, added axises os  (linux, windows) and jdk (7, 8)
* Go to blueocean dashboard you should only see matrix1 project (none of its axis and value permutations should be listed)
Triggered https://ci.blueocean.io/job/Acceptance%20Tests%20Param/60/
…oesn't need flattening
> JENKINS-37826# Regression listing Matrix style project on dashboard

- blueocean-dashboard/src/main/js/redux/actions.js
See [JENKINS-37829](https://issues.jenkins-ci.org/browse/JENKINS-37829).
To test: create a folder, create a freestyle project in that folder, add a simple bash script and watch execution in the BOUI, it should complete properly.
Tests covered in forthcoming ATH.
@jenkinsci/code-reviewers @reviewbybees esp. @cliffmeyers
> [FIX JENKINS-37829] - More reliable run matching for SSE events

- blueocean-dashboard/src/main/js/util/UrlUtils.js
This fixes current master with safari. Needs testing with IE still.
See [JENKINS-37838](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
> [JENKINS-37838] Calls to backend MUST end with /

- blueocean-core-js/package.json
- blueocean-core-js/src/js/jwt.js
- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-web/package.json
See [JENKINS-37859](https://issues.jenkins-ci.org/browse/JENKINS-37859).
> [JENKINS-37859] Allow for 60s of clock skew

- blueocean-core-js/package.json
- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-web/package.json
> Release core-js 0.0.5

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
See https://issues.jenkins-ci.org/browse/JENKINS-37873
* Create a MB project that has '/' in one of the branch
* Trigger build of this branch, make sure it ends up in queue
* See run list page in blueocean and see the POST /runs results has Link self reference with properly encoded branch names. For details see the JIRA ticket.
ATH runs fine locally.
> JENKINS-37873# Self link fix for branch queue items

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/BlueOceanConfigProperties.java
- blueocean-config/pom.xml
- blueocean-config/src/main/java/io/jenkins/blueocean/config/BlueOceanConfig.java
- blueocean-core-js/package.json
- blueocean-core-js/src/js/config.js
- blueocean-core-js/src/js/fetch.js
- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanRootAction.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest/README.md
- blueocean-web/package.json
This PR disables JWT by default and lets developers enable it with DFEATURE_BLUEOCEAN_JWT_AUTHENTICATION system property.
See [JENKINS-37837](https://issues.jenkins-ci.org/browse/JENKINS-37837).
> [JENKINS-37837] JWT feature flag

- blueocean-dashboard/src/main/js/components/ChangeSet.jsx
- blueocean-dashboard/src/main/js/components/ChangeSetToAuthors.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/js/components/stories/changes.js
- blueocean-dashboard/src/main/js/components/stories/index.js
- blueocean-dashboard/src/main/js/components/stories/logDisplay.js
See [JENKINS-35847](https://issues.jenkins-ci.org/browse/JENKINS-35847).
- implement condense version if overflow is detected
- add storybook examples
https://github.com/jenkinsci/blueocean-acceptance-test/pull/28
> [FIX JENKINS-35847] Developer should see a condensed version of the change summary

- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- blueocean-personalization/src/main/less/pipeline-card.less
See [JENKINS-37673](https://issues.jenkins-ci.org/browse/JENKINS-37673).
> [JENKINS-37673] running indicator clipped

- blueocean-dashboard/src/main/js/components/Step.jsx
See [JENKINS-37666](https://issues.jenkins-ci.org/browse/JENKINS-37666).
https://youtu.be/yo0Z_eb67lM
https://github.com/jenkinsci/blueocean-acceptance-test/pull/32
> [FIX JENKINS-37666] Proceeding step is sometimes erroneously expanded

- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- See [JENKINS-36973](https://issues.jenkins-ci.org/browse/JENKINS-36973).
- Fixing the icon change that was most when I merged master to the branch earlier today.
> [JENKINS-36973] fix icon that got lost in merge

- blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
- blueocean-dashboard/src/main/less/testing.less
See [JENKINS-37166](https://issues.jenkins-ci.org/browse/JENKINS-37166).
Mostly a CSS change, didn't bother with a test. Just go look at the test results to verify.
NOTE: I used smaller font sizes than the ticket called for, they were too large, looked bad and quickly caused wrapping on the simple example I have in the screenshot.
> [FIX JENKINS-37166] - update test result console style

- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/ApiHead.java
See https://issues.jenkins-ci.org/browse/JENKINS-38016
* Can't be tested as it is, we need to release and then test it on fresh install of 2.7.3
Not practical to write test. Does not cause any regression, we need to test after release on fresh jenkins 2.7.3.
Ran locally.
…ns are installed
> JENKINS-38016# Create ApiRoutable extensions lazily

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/pageable/PagedResponse.java
See https://issues.jenkins-ci.org/browse/JENKINS-37202.
* Create 120 jobs (?)
* Call URL localhost:8080/jenkins/blue/rest/search/?q=type:pipeline
* You should get only 100 records
Ran ATH locally, all tests passed successfully.
> JENKINS-37202# Set pagination by default

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
See [JENKINS-38006](https://issues.jenkins-ci.org/browse/JENKINS-38006).
https://github.com/jenkinsci/blueocean-acceptance-test/pull/35
> [FIX JENKINS-38006] - REGRESSION: logs not tailing with freestyle

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineJobFilters.java
See [JENKINS-37746](https://issues.jenkins-ci.org/browse/JENKINS-37746).
Simple enough fix, need to close some of these out ASAP.
To test: add the cloudbeers org folder as described in the JIRA issue.
> [FIX JENKINS-37746] - Org folders need to be excluded from BO list

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
See [JENKINS-37979](https://issues.jenkins-ci.org/browse/JENKINS-37979). No unit test practical here. Nothing you can really test ... will run the ATH.
> Pass the run instance to 'jenkins.pipeline.run.result' implementation.

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchContainerImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/BranchContainerImplTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ContainerFilter.java
- blueocean-rest/README.md
This PR makes branches ordered first by if they are a favorite or not, then by recent activity.
@i386 
See [JENKINS-38039](https://issues.jenkins-ci.org/browse/JENKINS-38039).
> [JENKINS-38039] branch ordering

- blueocean-config/package.json
- blueocean-core-js/package.json
- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-web/package.json
- js-extensions/@jenkins-cd/subs/css-bundle.js
- js-extensions/package.json
- pom.xml
Depends on...
* https://github.com/jenkinsci/js-modules/pull/4
* https://github.com/jenkinsci/js-builder/pull/10
* https://github.com/jenkinsci/sse-gateway-plugin/pull/10
> Getting the ATH running

- pom.xml
See https://issues.jenkins-ci.org/browse/JENKINS-38178
* Its change of Jenkins core from 2.7.3 to 2.7.1. Reviewer should sanity test manually or run ATH.
N/A
Can't get ATH to run locally.
> JENKINS-38178# Use LTS baseline 2.7.1

- blueocean-dashboard/src/main/js/components/Activity.jsx
See [JENKINS-38240](https://issues.jenkins-ci.org/browse/JENKINS-38240).
AT: https://github.com/jenkinsci/blueocean-acceptance-test/pull/41/
…tered
> [JENKINS-38240] REGRESSION open link on toast is not working

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/OrganizationApiTest.java
> Disable 2 flaky tests

- blueocean-dashboard/src/main/js/LoadingIndicator.js
See [JENKINS-38345](https://issues.jenkins-ci.org/browse/JENKINS-38345).
> [hotfix/JENKINS-38345] REGRESSION remove classList

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
See [JENKINS-37753](https://issues.jenkins-ci.org/browse/JENKINS-37753).
https://github.com/jenkinsci/blueocean-acceptance-test/pull/43 -> not tested due to problems with updatecenter mirror in spain, @recena is looking into it. -> NOW tested since update center is back
…inished with the run, this makes sure that they will be refetched after the run ended.
> [FIX JENKINS-37753] REGRESSION: Steps showing up as incomplete when they are in fact complete

- js-extensions/package.json
See [JENKINS-38321](https://issues.jenkins-ci.org/browse/JENKINS-38321).
js-x-vbump-20160926 * Bump js-extensions version out of beta before publishing to npm
> Bump version of JS-Extensions out of beta before publish

- js-extensions/package.json
See [JENKINS-38321](https://issues.jenkins-ci.org/browse/JENKINS-38321).
>  Fix missing dev dependency from package.json

- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-38321](https://issues.jenkins-ci.org/browse/JENKINS-38321).
JENKINS-38321-dashboard-new-button * Update dependency on js-extensions to latest, add an ExtensionPoint for the 'new pipeline' action with default of old behaviour
> Update to latest js-extensions, and add an ExtensionPoint for the "New Pipeline" button

- blueocean-dashboard/src/main/js/components/MultiBranch.jsx
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/PullRequests.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-dashboard/src/test/js/pullRequests-spec.js
See [JENKINS-38329](https://issues.jenkins-ci.org/browse/JENKINS-38329).
Prevent that the error occurs however ATM debugging the issue with keith.
For the AT of this test I need back the folder.js which is atm commented
…ting them otherwise we will run into failures the next time. Further in general we should never try to fetch something where we know before hand that it does not exit.
> [JENKINS-38329] REGRESSION Errors on activity and branches tabs

- blueocean-dashboard/src/main/js/components/DocumentTitle.jsx
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/test/js/pipeline-not-found-spec.js
- blueocean-dashboard/src/test/js/pipelines-spec.js
See [JENKINS-37793](https://issues.jenkins-ci.org/browse/JENKINS-37793).
Implemented the different titles. Will add AT when I will implement test for the JENKINS-38329 regression
…tests
> [FIX JENKINS-37793] Developer can see meaningful page titles

- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-38056](https://issues.jenkins-ci.org/browse/JENKINS-38056).
depends on https://github.com/jenkinsci/jenkins-design-language/pull/98
> FIX JENKINS-38056 Duration of running Pipeline is not live

- blueocean-dashboard/src/main/js/util/logDisplayHelper.js
- blueocean-dashboard/src/test/js/data/steps/failingRunningSteps.js
- blueocean-dashboard/src/test/js/log-spec.js
See [JENKINS-38009](https://issues.jenkins-ci.org/browse/JENKINS-38009).
> FIX Jenkins 38009 Executing step is not expanded when there is a proceeding failing step

- Jenkinsfile
See [JENKINS-37918](https://issues.jenkins-ci.org/browse/JENKINS-37918).
Params updated to match ATH changes.
> Fix ATH build trigger param names

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
See [JENKINS-36781](https://issues.jenkins-ci.org/browse/JENKINS-36781).
> [JENKINS-36781] Display of SCM identifiers should be consistent

- blueocean-dashboard/src/main/js/components/LogConsole.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/main/js/components/Step.jsx
See [JENKINS-37925](https://issues.jenkins-ci.org/browse/JENKINS-37925).
AT https://github.com/jenkinsci/blueocean-acceptance-test/pull/54
https://ci.blueocean.io/job/ATH-Jenkinsfile/job/JENKINS-37925/2
> [FIX JENKINS-37925] change full log link in steps to the backend log

- blueocean-dashboard/src/main/js/components/LogConsole.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/main/js/components/Step.jsx
- blueocean-dashboard/src/main/less/core.less
- blueocean-dashboard/src/main/less/variables.less
See [JENKINS-38248](https://issues.jenkins-ci.org/browse/JENKINS-38248).
https://youtu.be/lCQ6SyFZGZg
> FIX JENKINS-38248 Log should only be linkable from its line number

- bin/ncuUpdate
See [JENKINS-38673](https://issues.jenkins-ci.org/browse/JENKINS-38673).
Adding script to help keeping deps in sync
> [ncuUpdateScript] add a small script to update our main plugins

- blueocean-core-js/package.json
- blueocean-core-js/src/js/index.js
- blueocean-core-js/src/js/sse/SseBus.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/Dashboard.jsx
- blueocean-dashboard/src/main/js/OrganizationPipelines.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
[JENKINS-37206](https://issues.jenkins-ci.org/browse/JENKINS-37206): Changes to try help stabalise the ATH some more. Involves some tweaks to the SSE Gateway client ala https://github.com/jenkinsci/sse-gateway-plugin/pull/12 (review that too please).
[JENKINS-38925](https://issues.jenkins-ci.org/browse/JENKINS-38925): Eliminate multiple Blue Ocean connections to the SSE Gateway.
> [FIX JENKINS-37206 and JENKINS-38925] New SSE Gateway client for better headless sse for ATH stability

- blueocean-rest/README.md
Simple change to docs to add an exmaple of PR data. No testing needed
See [JENKINS-36573](https://issues.jenkins-ci.org/browse/JENKINS-36573).
> [JENKINS-36573] Add an example for a pullrequest

- README.md
- Just an update to the README doc
> improve docs for shrinkwrap

- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
- blueocean-dashboard/src/test/js/pipeline-graph-converter-spec.js
- blueocean-dashboard/src/test/json/pipeline-graph-converter/every-result.json
See [JENKINS-39201](https://issues.jenkins-ci.org/browse/JENKINS-39201).
> bug/JENKINS-39201 * Fix for showing UNSTABLE nodes correctly, + tests

- blueocean-config/npm-shrinkwrap.json
- blueocean-config/package.json
New version includes a small bug fix. Should be safe to roll in.
> Upgrade rollbar to 1.9.2

- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/util/UrlUtils.js
- blueocean-dashboard/src/test/js/UrlUtils-spec.js
See [JENKINS-/JENKINS-39338](https://issues.jenkins-ci.org/browse/JENKINS-39338).
This is my first foray into react - added a test. I hate eslint. Also I don't think position of cog on summary screen is right. 
To try it: open a pipeline, look at top of summary screen or results for a cog. 
@cliffmeyers @imeredith I expect this needs to only be visible when user has some kind of access? 
> link to classic config screen JENKINS-39338

- blueocean/pom.xml
See [JENKINS-36377](https://issues.jenkins-ci.org/browse/JENKINS-36377).
To test:
* Ensure that your email configured in Jenkins is the same as your git email
* Setup a multibranch pipeline
* Create a new branch with a single commit on it
* Index the multibranch pipeline
* Wait until the pipeline is running
* Check that the new branch is a favorite on the dashboard
> JENKINS-36377 bundle blueocean-autofavorite

- CONTRIBUTING.md
Updating link to better contribution documentation on https://wiki.jenkins-ci.org
> Updating contribution docs

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/less/core.less
See [JENKINS-39627](https://issues.jenkins-ci.org/browse/JENKINS-39627).
> JENKINS-39627 Alignment of cog is off on Result 

- blueocean-dashboard/src/main/js/components/PullRequest.jsx
- blueocean-dashboard/src/main/js/components/PullRequests.jsx
See [JENKINS-39202](https://issues.jenkins-ci.org/browse/JENKINS-39202
> [JENKINS-39202] PR column renames

- .gitignore
- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/PullRequest.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-dashboard/src/main/less/core.less
- blueocean-dashboard/src/test/js/branches-spec.js
- blueocean-dashboard/src/test/js/pullRequest-spec.js
See [JENKINS-39336](https://issues.jenkins-ci.org/browse/JENKINS-39336).
Adds links to all columns so that right clicking works. 
Adding links to all items in the row allows the item to be
opened in a new tab with right click.
> [JENKINS-39336] Add links to  items for activities

- README.md
- blueocean-commons/README.md
- blueocean-core-js/README.md
- blueocean-events/README.md
From time to time it is good to spring clean things. 
Added some docs, edited others. Added some humour and links to important things. 
> Time to spring clean the readme/devdocs

- blueocean/pom.xml
Bumps the autofavorite and display url plugin versions.
> Update autofavorite and display url plugin versions

- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
See JENKINS-39889
Small change - should only see cog when non anon and logged in
> fix for cog and anon JENKINS-39889

- blueocean-dashboard/src/main/less/core.less
See [JENKINS-39853](https://issues.jenkins-ci.org/browse/JENKINS-39853).
> bug/JENKINS-39853-table-actions * Partial fix for Dashboard table issues

- blueocean-core-js/src/js/i18n/i18n.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/CreatePipelineLink.js
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-39849](https://issues.jenkins-ci.org/browse/JENKINS-39849).
> Jenkins 39849 failed requests for i18n bundles

- blueocean-core-js/package.json
- blueocean-core-js/src/js/ToastUtils.js
- blueocean-core-js/src/js/components/RunButton.jsx
- blueocean-core-js/src/js/i18n/i18n.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/test/js/pipeline-spec.js
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- blueocean-web/src/main/js/main.jsx
See [JENKINS-39846](https://issues.jenkins-ci.org/browse/JENKINS-39846).
> Jenkins 39846 REGRESSION: incorrect capitalisation and stop button not visible in running build due to i18n

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineQueueContainer.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunSearch.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/pageable/Pageables.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/pageable/PagedResponse.java
See [JENKINS-39661](https://issues.jenkins-ci.org/browse/JENKINS-39661).
> JENKINS-39661# /runs and /activity performance fix

- blueocean/src/test/java/io/jenkins/blueocean/i18n/BlueI18nTest.java
> Add block in BlueI18nTest to wait until the JenkinsRule has the plugins installed

- blueocean-dashboard/src/main/js/components/MultiBranch.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
See [JENKINS-39852](https://issues.jenkins-ci.org/browse/JENKINS-39852).
Just needed to update to pager object. To test: load dashboard, click through to run details.
@reviewbybees
> [FIX JENKINS-39852] - loading worm not finishing

- blueocean-core-js/package.json
- blueocean-core-js/src/js/i18n/i18n.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-i18n/pom.xml
- blueocean-i18n/src/main/java/io/jenkins/blueocean/i18n/BlueI18n.java
- blueocean-i18n/src/test/java/io/jenkins/blueocean/i18n/BlueI18nTest.java
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- blueocean/src/test/java/io/jenkins/blueocean/i18n/BlueI18nTest.java
- js-extensions/package.json
Keeping my buddy @vivek happy !!
@reviewbybees
> Move the i18n rest endpoint under "rest"

- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/FlowNodeWrapper.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/InputStepImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeUtil.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueInputStep.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineStep.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
See [JENKINS-38491](https://issues.jenkins-ci.org/browse/JENKINS-38491).
Pipeline with Input step does following to the 'state' of Run, Node and Step:
- Run's state is PAUSED, result UNKNOWN
- Node containing input step's state is PAUSED, result UNKNOWN. If nested parallel or stage has input step then top level stage is marked PAUSED
- Step that's waiting for input has PAUSED state and UNKNOWN result
Following pipeline script can be used for testing.
- GET /jenkins/blue/rest/organizations/jenkins/pipelines/pipeline1/runs/1/ should report state==PAUSED, result==UNKNOWN
- GET /jenkins/blue/rest/organizations/jenkins/pipelines/pipeline1/runs/1/nodes/ should report state==PAUSED, result==UNKNOWN for nodes parallelStage and right.
- GET …
> Story/jenkins 38491 Status of stages/parallels waiting for input

- docu/I18N.md
I've made some small fixes to the I18N documentation which I saw, when I was reading it for my other PR (#654). Nothing big actually. ;)
> Small fixes for i18n documentation

- blueocean-dashboard/src/main/js/components/MultiBranch.jsx
No ATH test. That will come in the new year as a bigger ATH coverage for paging.
See [JENKINS-40463](https://issues.jenkins-ci.org/browse/JENKINS-40463).
@reviewbybees
> [JENKINS-40463] Show pager when data is loaded

- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
security PR to trigger version update
> [Update_version_numbers_of_jdl_and_cjs] Update version numbers

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderRunContainerImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueMultiBranchPipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRunContainer.java
See [JENKINS-38804](https://issues.jenkins-ci.org/browse/JENKINS-38804).
How to test this functionality:
properties([parameters([string(defaultValue: 'xyz', description: 'string param', name: 'param1')]), pipelineTriggers([])])
node(){
stage('build'){
echo "building"
}
}
curl -v http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/pipeline1/
````
{
"_class" : "io.jenkins.blueocean.rest.impl.pipeline.PipelineImpl",
"_links" : {...}
},
"actions" : [...],
"displayName" : "pipeline1",
"estimatedDurationInMillis" : 1426,
"fullDisplayName" : "pipeline1",
"fullName" : "pipeline1",
"lastSuccessfulRun" : "http://localhost:50643/jenkins/blue/rest/organizations/jenkins/pipelines/pipeline1/runs/1/",
"latestRun" : {...},
"name" : "pipeline1",
"organization" : "jenkins",
"parameters" …
```
> Story/jenkins 38804 Parameterized pipeline API

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- the JDL was added as a dep for core-js but not actually used. It needs to be removed.
@reviewbybees
> remove jdl dep from core-js

- blueocean-core-js/package.json
- blueocean-core-js/src/js/components/RunButton.jsx
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
ATH https://github.com/jenkinsci/blueocean-acceptance-test/pull/97 
See [JENKINS-40854](https://issues.jenkins-ci.org/browse/JENKINS-40854).
@reviewbybees
> [JENKINS-40854] Regression in run button on activity page

- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
Just bumping JDL, changes are to components not used in BO proper but editor needs...
@reviewbybees
> Bump JDL to .99

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
> Fix time sensitive failing tests

- docker/official/Jenkinsfile
> Set up the Docker 'official' Pipeline to execute weekly

- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
Changes to use a JDL that inlines a number of CSS resources into the JDL's css file. See https://github.com/jenkinsci/jenkins-design-language/pull/129
See [JENKINS-40932](https://issues.jenkins-ci.org/browse/JENKINS-40932).
@reviewbybees
> [FIX JENKINS-40932] combine css

- docker/official/build.sh
> Ensure that only the right blueocean-parent- tags get considered for dockering

- blueocean-commons/pom.xml
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/TreeResponse.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ClassAttributeBehaviour.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/CustomExportedBean.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/DataWriter.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Export.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ExportConfig.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/FieldProperty.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/FilteringTreePruner.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Flavor.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/JSONDataWriter.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/MethodHandleFactory.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/MethodProperty.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Model.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ModelBuilder.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/NamedPathPruner.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/NotExportableException.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Property.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Range.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/TreePruner.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/TypeUtil.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/XmlChars.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/package-info.java
- blueocean-commons/src/test/java/io/jenkins/blueocean/commons/stapler/export/ClassAttributeBehaviourTest.java
- blueocean-commons/src/test/java/io/jenkins/blueocean/commons/stapler/export/JSONDataWriterTest.java
- blueocean-commons/src/test/java/io/jenkins/blueocean/commons/stapler/export/ModelTest.java
- blueocean-commons/src/test/java/io/jenkins/blueocean/commons/stapler/export/NamedPathPrunerTest.java
- blueocean-commons/src/test/java/io/jenkins/blueocean/commons/stapler/export/RangeTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/CreateResponse.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/pageable/PagedResponse.java
> Internalize Stapler so we can move away from core releases

- blueocean-dashboard/src/main/js/Capabilities.js
- blueocean-dashboard/src/main/js/components/PipelineRowItem.jsx
- blueocean-dashboard/src/main/less/core.less
See [JENKINS-37427](https://issues.jenkins-ci.org/browse/JENKINS-37427).
ATH PR; https://github.com/jenkinsci/blueocean-acceptance-test/pull/99
@reviewbybees
> [JENKINS-37427] Matrix Jobs links to classic jenkins

- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/test/java/io/jenkins/blueocean/BlueOceanWebURLBuilderTest.java
- blueocean-github-pipeline/pom.xml
- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- blueocean-personalization/src/test/js/components/PipelineCard-spec.jsx
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderRunImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineJobFilters.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
- pom.xml
See [JENKINS-40299](https://issues.jenkins-ci.org/browse/JENKINS-40299).
@reviewbybees
> Jenkins 40299 fix remaining scmapi integration issues

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/js/i18n/i18n.js
- blueocean-core-js/src/js/index.js
- blueocean-core-js/src/js/logging.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- blueocean-web/src/main/java/io/jenkins/blueocean/BlueOceanUI.java
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
Allow use of the likes of the Quick Language Switcher for Chrome.
See [JENKINS-40761](https://issues.jenkins-ci.org/browse/JENKINS-40761).
@reviewbybees
> [FIX JENKINS-40761] i18next lang detection from htmlTag

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
> Hotfix core js 48

- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/test/java/io/jenkins/blueocean/BlueOceanWebURLBuilderTest.java
- blueocean-github-pipeline/pom.xml
- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- blueocean-personalization/src/test/js/components/PipelineCard-spec.jsx
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderRunImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineJobFilters.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
- pom.xml
This reverts commit 21286af0439053281830d6d6b98699f622ef1644.
@reviewbybees
> Revert "Jenkins 40299 fix remaining scmapi integration issues (#715)"

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/ErrorMessage.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/JsonConverter.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/ServiceException.java
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitPipelineCreateRequest.java
- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineCreateRequestImpl.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineContainer.java
See [JENKINS-41047](https://issues.jenkins-ci.org/browse/JENKINS-41047).
@cliffmeyers Its implemented as we discussed. I have fixed error messages for git and GitHub creation APIs. Please review.
```
POST http://localhost:8080/blue/rest/organizations/jenkins/pipelines/
{
"scmConfig" : { }
}
```
Should result in this error message:
```
{
"message" : "Failed to create Git pipeline",
"code" : 400,
"errors" : [ {
"message" : "name is required",
"code" : "MISSING",
"field" : "name"
}, {
"message" : "$class is required",
"code" : "MISSING",
"field" : "$class"
} ]
}
```
@reviewbybees
> JENKINS-41047# ErrorMessage improvement

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrganization.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubUserOrganization.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/scm/ScmOrganization.java
Small change for Cliff to allow exposing the User and Org avatar.
@reviewbybees
> Add organization avatar

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
See [JENKINS-39464](https://issues.jenkins-ci.org/browse/JENKINS-39464).
Try these pipeline scripts:
```
stage("stage1"){
echo "stage 1..."
}
parallel('branch1':{
node {
stage('Setup') {
sh 'echo "Setup..."'
}
stage('Unit and Integration Tests') {
sh 'echo "Unit and Integration Tests..."'
}
}
}, 'branch2': {
node {
stage('Setup') {
sh 'echo "Branch2 setup..."'
}
stage('Unit and Integration Tests') {
echo '"my command to execute tests"'
}
}
})
stage("stage2"){
echo "stage 2..."
}
```
Should result in to this pipeline graph:
```
parallel('branch1':{
node {
stage('Setup') {
sh 'echo "Setup..."'
}
stage('Unit and Integration Tests') {
sh 'echo "Unit and Integration Tests..."'
}
}
}, 'branch2': {
node {
stage('Setup') {
sh 'echo "Branch2 setup..."'
}
stage('Unit and Integration Tests') {
echo …
```
> JENKINS-39464# Wrap orphan prallels inside synthetic stage

- blueocean-dashboard/src/main/js/util/UrlUtils.js
See [JENKINS-41462](https://issues.jenkins-ci.org/browse/JENKINS-41462).
@scherler PTAL.
@reviewbybees
> JENKINS-41462# branch name encoding fix

- blueocean-dashboard/src/main/js/util/UrlUtils.js
This reverts commit 196d5fc2cd4f2a816553ba2014732f3fcae64ead.
ATH failed for PR https://github.com/jenkinsci/blueocean-plugin/pull/751: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/1129/. Unsure if its legit but its better to revert.
@reviewbybees
> Revert "JENKINS-41462# branch name encoding fix (#751)"

- blueocean/pom.xml
Fixes for:
*  [JENKINS-40446](https://issues.jenkins-ci.org/browse/JENKINS-40446)
*  [JENKINS-39580](https://issues.jenkins-ci.org/browse/JENKINS-39580)
Testing was done in the `display-url-api-plugin` and `blueocean-display-url-plugin`
@reviewbybees
> JENKINS-40446 JENKINS-39580 Bump display url to v1.4

- blueocean-web/src/main/js/main.jsx
Add an extension point for top nav links. Need this to publish the pipeline editor.
@reviewbybees
> Add top nav link extension point

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-dashboard/src/main/js/components/Step.jsx
- blueocean-dashboard/src/main/js/components/Steps.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/main/js/util/serverBrowserTimeHarmonize.js
- blueocean-dashboard/src/test/js/clientServerTimeHarmonize-spec.js
- blueocean-web/src/main/java/io/jenkins/blueocean/BlueOceanUI.java
- blueocean-web/src/main/js/config.js
- blueocean-web/src/main/js/main.jsx
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
See [JENKINS-40605](https://issues.jenkins-ci.org/browse/JENKINS-40605).
@reviewbybees
> FIX-JENKINS-40605_Time_reported_is_not_correct

- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitPipelineUpdateRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineUpdateRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrgFolderTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineCreateRequestImpl.java
See [JENKINS-41373](https://issues.jenkins-ci.org/browse/JENKINS-41373).
How to test:
- Create github accessToken credential id in system store and global scope
- Create a user in Jenkins and using matrix authorization give him overall read, job read permission
- Create GitHub org pipeline
```
curl -v -XPOST -H 'content-type: application/json' -u 'vivek:vivek' http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/ -d 
'{
"scmConfig" : {
"config" : {
"repos" : [
"PR-7"
],
"orgName" : "cloudbeers"
},
"uri" : "https://api.github.com",
"credentialId" : "vivek-github"
},
"$class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubPipelineCreateRequest",
"name" : "cb1"
}'
```
You should receive 403 error:
```
{
"message" : "Failed to create pipeline: failureproject2. User …
```
> JENKINS-41373# Permission error reporting in JSON

- blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
Just a quick text change
@reviewbybees
> Remove the cheeky The Castle reference. Confused a user :(

- blueocean/pom.xml
See [JENKINS-41576](https://issues.jenkins-ci.org/browse/JENKINS-41576).
@reviewbybees
> Bump autofavourite dependency to 0.6

- blueocean-web/src/main/js/main.jsx
- blueocean-web/src/main/less/flex.less
Need this to not split the links, argh.
@reviewbybees
> Top links extension point

- bin/checkshrinkwrap.js
For @scherler and @imeredith 
@reviewbybees
> this may pick up some nasties

- blueocean/pom.xml
Provide a description for the Blue Ocean plugin. We didn't have one!
@reviewbybees
> Plugin description

- blueocean-dashboard/README.md
Update readme to be enable to run blueocean-dashbord locally.
As it is documentation, no unit test is needed.
@reviewbybees 
@alecharp
> Update readme, fix steps description to run dashboard locally

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineJobFilters.java
> Cleanup where we check for PR on the backend

- pom.xml
cc @i386 @vivek I saw this warning, given it is required now, can be removed from test scope right? 
@reviewbybees
> Only need it once

- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages_en_au.properties
Added this back due to complaining Australians.
@reviewbybees
> Add back the The Castle refrence in Australian English translation

- pom.xml
@vivek noticed a few things that were not in my original PR when updating #789 
@reviewbybees
> Small dependency updates

- blueocean-core-js/package.json
- blueocean-core-js/src/js/components/ReplayButton.jsx
- blueocean-core-js/test/js/components/ReplayButton-spec.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-personalization/src/test/js/components/PipelineCard-spec.jsx
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
ATH https://github.com/jenkinsci/blueocean-acceptance-test/pull/113
See [JENKINS-38088](https://issues.jenkins-ci.org/browse/JENKINS-38088).
@reviewbybees
> [JENKINS-38088] Add rerun to all pipeline runs

- blueocean-dashboard/src/main/js/components/ScrollHelper.jsx
See [JENKINS-41784](https://issues.jenkins-ci.org/browse/JENKINS-41784).
@reviewbybees
> bug/JENKINS-41784-autoscroll * Fix auto-scroll regression

- blueocean/pom.xml
- pom.xml
Now the UC has propagated its now safe to bump this.
@reviewbybees
> update to blueocean-display-url 0.5.1

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
Change CSS for header links. Downstream of https://github.com/jenkinsci/jenkins-design-language/pull/144
See [JENKINS-41783](https://issues.jenkins-ci.org/browse/JENKINS-41783).
@reviewbybees
> [FIX JENKINS-41783] Update JDL for header link fix

- blueocean-config/src/main/java/io/jenkins/blueocean/config/BlueOceanConfigStatePreloader.java
- blueocean-core-js/package.json
- blueocean-core-js/src/js/config.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-41280](https://issues.jenkins-ci.org/browse/JENKINS-41280).
@reviewbybees
> [FIX JENKINS-41280] Hide organization prefix from UI

- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
- blueocean-dashboard/src/test/js/pipeline-graph-converter-spec.js
- blueocean-dashboard/src/test/json/pipeline-graph-converter/every-result.json
Couldnt reporduce live, so just unit tests.
See [JENKINS-41780](https://issues.jenkins-ci.org/browse/JENKINS-41780).
@reviewbybees
> [JENKINS-41780] Fixed aborted node style

- pom.xml
See [JENKINS-41832](https://issues.jenkins-ci.org/browse/JENKINS-41832).
@reviewbybees
> [FIX JENKINS-41832] pubsub 1.7 with fix for JENKINS-41832

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/stories/RunDetailsHeaderStories.js
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
* Pull in JDL update to fix aborted header colour
See [JENKINS-41779](https://issues.jenkins-ci.org/browse/JENKINS-41779).
@reviewbybees
> JENKINS-41779 - Aborted header colour

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
Using released version of plugins
@reviewbybees
> Bumb versions

- bin/cleanInstall.js
- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
> Make clean install faster

- blueocean-dashboard/src/main/js/creation/git/GitCompletedStep.jsx
- blueocean-dashboard/src/main/js/creation/git/GitConnectStep.jsx
- blueocean-dashboard/src/main/js/creation/git/GitDefaultOption.js
- blueocean-dashboard/src/main/js/creation/git/steps/GitRenameStep.jsx
- Just adding some classes to make ATH easier. Although this is trivial, I'll wait to merge until after release dances are done.
@reviewbybees
> [JENKINS-38597] add classNames to facilitate ATH

- blueocean-dashboard/src/main/js/Dashboard.jsx
- blueocean-dashboard/src/main/js/LoadingIndicator.js
- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
Loading worm was not being switched to white or showing up in certain cases...
Difficult to test, as it relies on timing and network latency...
See [JENKINS-41874](https://issues.jenkins-ci.org/browse/JENKINS-41874).
@reviewbybees
> [FIX JENKINS-41874] loading worm issues

- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
- blueocean-web/src/main/webapp/scripts/ie-detect.js
See [JENKINS-41664](https://issues.jenkins-ci.org/browse/JENKINS-41664).
Need IE Edge to test.
@reviewbybees
> [FIX JENKINS-41664] Detect MS IE Edge

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-41566](https://issues.jenkins-ci.org/browse/JENKINS-41566).
This PR could subsume https://github.com/jenkinsci/blueocean-plugin/pull/809
@reviewbybees
> [FIX JENKINS-41566] Fix reconnect ping request flood

- bin/cleanInstall.js
run cleanInstall in parallel
@reviewbybees
> [ParallelInstall] run install in parallel

- blueocean-core-js/package.json
- blueocean-core-js/src/js/config.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- blueocean-web/src/main/js/DevelopmentFooter.jsx
Build it and look at the footer.
NOTE: SNAPSHOT's have a longish version, release versions will be as expected.
See [JENKINS-41242](https://issues.jenkins-ci.org/browse/JENKINS-41242).
@reviewbybees
> JENKINS-41242: footer adjustments

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
Test included.
See [JENKINS-39521](https://issues.jenkins-ci.org/browse/JENKINS-39521).
@reviewbybees
> [JENKINS-39521] Force text plain onto log

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
See [JENKINS-42006](https://issues.jenkins-ci.org/browse/JENKINS-42006).
@reviewbybees
> JENKINS-42006# User permission should only returns permission of authenticated user

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
See [JENKINS-42006](https://issues.jenkins-ci.org/browse/JENKINS-42006).
@reviewbybees
> JENKINS-42006# Fix to return only authenticated user's permission

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
* Update JDL dependency to pull in graph fix
See [JENKINS-38753](https://issues.jenkins-ci.org/browse/JENKINS-38753).
@reviewbybees
> Jenkins 38753 truncate graph labels

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
use stable published versions
@reviewbybees
> [bumbVersionsThor] bump versions

- blueocean-core-js/package.json
- blueocean-core-js/src/js/components/ShowMoreButton.jsx
- blueocean-core-js/src/js/index.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/MultiBranch.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/js/components/PullRequests.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-39705](https://issues.jenkins-ci.org/browse/JENKINS-39705).
@reviewbybees
> [JENKINS-39705] Extracted Show more into a component

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-42196](https://issues.jenkins-ci.org/browse/JENKINS-42196).
Depends on https://github.com/jenkinsci/sse-gateway-plugin/pull/18
To test ... open the browser dev console. You should no longer see the `/ping` requests every ~30 seconds.
@reviewbybees
> [FIX JENKINS-42196] Eliminate overly-eager SSE ping request

- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueUserPermission.java
See [JENKINS-41941](https://issues.jenkins-ci.org/browse/JENKINS-41941).
curl -v -u user:password http://127.0.0.1:8080/jenkins/blue/rest/organizations/jenkins/users/vivek1/
```
{
"_links" : {
"self" : {
"_class" : "io.jenkins.blueocean.rest.hal.Link",
"href" : "/blue/rest/organizations/jenkins/users/vivek/"
},
"favorites" : {
"href" : "/blue/rest/organizations/jenkins/users/vivek/favorites/",
"_class" : "io.jenkins.blueocean.rest.hal.Link"
}
},
"id" : "vivek",
"permission" : {
"administrator" : true,
"pipeline" : {
"create" : true,
"read" : true,
"start" : true,
"stop" : true,
"configure" : true
},
"_class" : "io.jenkins.blueocean.service.embedded.rest.UserImpl$1",
"credential" : {
"create" : true,
"delete" : true,
"update" : true,
"manageDomains" : true,
"view" : true
}
},
"avatar" : …
```
> JENKINS-41941# Add credential permission to user.permission

- .gitignore
- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/js/paths/rest.js
- blueocean-core-js/src/js/services/ActivityService.js
- blueocean-core-js/src/js/services/DefaultSSEHandler.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/PipelineRoutes.jsx
- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/ColumnFilter.jsx
- blueocean-dashboard/src/main/less/extensions.less
- blueocean-dashboard/src/main/less/forms/column-filter.less
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-35768](https://issues.jenkins-ci.org/browse/JENKINS-35768).
Will add tests when this gets refactored to JDL.
Go to the Activity tab of a multibranch project and click the branch filter in the branch column header... works like this:
@reviewbybees
> [FIX JENKINS-35768] filter by branch

- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
Forgot to publish a public core-js
@reviewbybees
> Publish public core-js

- blueocean-dashboard/src/main/js/creation/github/steps/GithubCredentialStep.jsx
I put the wrong ticket in the branch name because I am an idiot. 
https://issues.jenkins-ci.org/browse/JENKINS-42273
This will set things up right for creation and editing
@reviewbybees 
@cliffmeyers @kzantow take a look
> link to oauth scopes

- README.md
https://issues.jenkins-ci.org/browse/JENKINS-42117
Some dev docs on the process for proposing upgrades
@reviewbybees 
@vivek @i386
> howto on upgrading deps

- blueocean-dashboard/src/main/js/creation/github/steps/GithubAlreadyDiscoverStep.jsx
- blueocean-dashboard/src/main/js/creation/github/steps/GithubRepositoryStep.jsx
See [JENKINS-42133](https://issues.jenkins-ci.org/browse/JENKINS-42133).
@reviewbybees
> JENKINS-42133 Label for any buttons to exit the creation flow

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages_de.properties
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages_es.properties
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages_fr.properties
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-41870](https://issues.jenkins-ci.org/browse/JENKINS-41870).
depends on: https://github.com/jenkinsci/jenkins-design-language/pull/152
@reviewbybees
> [JENKINS-41870] Use new JDL for time duration

- blueocean-dashboard/src/main/js/components/RunDetailsTests.jsx
See [JENKINS-42363](https://issues.jenkins-ci.org/browse/JENKINS-42363).
> [FIX JENKINS-42363] Add run details to test extensions

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
Reverts jenkinsci/blueocean-plugin#858
> Revert "Topic/include pr branch info in run"

- blueocean-dashboard/src/main/js/components/ColumnFilter.jsx
- blueocean-dashboard/src/main/less/forms/column-filter.less
* Min width of the filter should be 100% the width of the branch column
* Max width of the filter should be 250% the width of the branch column
* If text exceeds this limit then it should be ellipsed at the end
* Hovering over the item should reveal its full name
To test just have branches with very long names and some very short ones.
See [JENKINS-42366](https://issues.jenkins-ci.org/browse/JENKINS-42366).
PTAL @kzantow @brody
> JENKINS-42366 Column filter must handle long values

- blueocean-dashboard/src/main/js/creation/github/GithubAccessTokenManager.js
- blueocean-dashboard/src/main/js/creation/github/GithubAccessTokenState.js
- blueocean-dashboard/src/main/js/creation/github/GithubCreationState.js
- blueocean-dashboard/src/main/js/creation/github/GithubFlowManager.js
- blueocean-dashboard/src/main/js/creation/github/api/GithubCreationApi.js
- blueocean-dashboard/src/main/js/creation/github/api/GithubCredentialsApi.js
- blueocean-dashboard/src/main/js/creation/github/steps/GithubCompleteStep.jsx
- blueocean-dashboard/src/main/js/creation/github/steps/GithubCredentialStep.jsx
- blueocean-dashboard/src/main/js/creation/github/steps/GithubUnknownErrorStep.jsx
- blueocean-dashboard/src/main/less/creation/github.less
- See [JENKINS-42103](https://issues.jenkins-ci.org/browse/JENKINS-42103).
@reviewbybees
> Bug/jenkins 42103 GitHub revoked access token

- blueocean/pom.xml
`cd blueocean && mvn hpi:run -Djetty.contextPath=/bob`
then browse to `http://localhost:8080/bob`
> Use `mvn hpi:run -Djetty.contextPath=/bob` to change context path

- blueocean-core-js/package.json
- blueocean-core-js/src/js/User.js
- blueocean-core-js/test/js/User-spec.js
- blueocean-core-js/test/js/data/user-1.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/CreatePipelineLink.js
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
To test create a user without admin and job create permissions.
See [JENKINS-41434](https://issues.jenkins-ci.org/browse/JENKINS-41434).
@reviewbybees
> [JENKINS-41434] Hide link when no create permission

- blueocean-dashboard/src/main/less/creation/github.less
See [JENKINS-42126](https://issues.jenkins-ci.org/browse/JENKINS-42126).
> [FIX JENKINS-42126] Remove max-height from creation org list

- blueocean-core-js/package.json
- blueocean-core-js/src/js/User.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- blueocean-web/src/main/js/main.jsx
See [JENKINS-42408](https://issues.jenkins-ci.org/browse/JENKINS-42408).
> [Fix JENKINS-42408] Show Admin link only if user is admin

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/FlowNodeWrapper.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/NodeLogResource.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineNode.java
See [JENKINS-41350](https://issues.jenkins-ci.org/browse/JENKINS-41350).
This API gives logs of all steps in it, appended as single logs.
Get Node log:
```
curl -v localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/:id/runs/:id/nodes/:id/log
```
Download Node log:
```
curl -v localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/:id/runs/:id/nodes/:id/log/?download=true
```
```
[master] Running shell script
+ echo setting up selenium environment
setting up selenium environment
[master] Running shell script
+ sleep 5
[master] Running shell script
+ echo setting up selenium environment
setting up selenium environment
[master] Running shell script
+ sleep 5
[master] Running shell script
+ echo setting up selenium environment
setting up selenium environment
[master] …
```
> JENKINS-41350# Pipeline node log API

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/js/i18n/i18n.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-personalization/src/main/js/redux/FavoritesActions.jsx
- blueocean-personalization/src/main/resources/jenkins/plugins/blueocean/personalization/Messages.properties
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-41642](https://issues.jenkins-ci.org/browse/JENKINS-41642).
Depends on https://github.com/jenkinsci/jenkins-design-language/pull/156
Simple error styled toast for when there's an favoriting error.
> [FIX JENKINS-41642] Handle when favouriting a pipeline fails

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
To test  hit rerun while in rundetails
See [JENKINS-42040](https://issues.jenkins-ci.org/browse/JENKINS-42040).
> [FIX JENKINS-42040] Duration reset on rerun

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/js/components/stories/RunDetailsHeaderStories.js
* Update stories to exercise isMultiBranch flag
* Fix propertyTypes typo
* Return span into .u-label-value pair for branch label
See [JENKINS-42520](https://issues.jenkins-ci.org/browse/JENKINS-42520).
> JENKINS-42520 Branch label wraps

- Dockerfile.build
- Jenkinsfile
* Add UID and GID support so it can be built on any jenkins install. Jenkins doesn't always run as user 1000
* Add latest npm so it never fails on fsevents (optional dep)
* Add phantomjs to speed up runtime
> Minor fixes to Docker file and Jenkins file

- blueocean-dashboard/src/main/js/creation/github/GithubFlowManager.js
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineUpdateRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrgFolderTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- pom.xml
See [JENKINS-42450](https://issues.jenkins-ci.org/browse/JENKINS-42450).
[x] Upgrade workflow-multibranch plugin to 2.13 and fix multi-branch changeset test
> JENKINS-42450# optimized scan if there is one repo created.

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmSaveFileRequest.java
See [JENKINS-42646](https://issues.jenkins-ci.org/browse/JENKINS-42646).
On an empty GitHub repo, try to create a pipeline and then use pipeline editor to create Jenkinsfile and save it. 
cc: @kzantow @michaelneale
> JENKINS-42646# fix branch auto-creation logic for empty repo

- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-personalization/src/main/js/jenkins-js-extension.yaml
See [JENKINS-42650](https://issues.jenkins-ci.org/browse/JENKINS-42650).
Can't really test this until a new editor is released, or install and `hpi:hpl` a local install with this PR: https://github.com/jenkinsci/blueocean-pipeline-editor-plugin/pull/31
> [FIX JENKINS-42650] - sort extensions

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FavoriteContainerImpl.java
Does not show favorites that are folders now.
See [JENKINS-42490](https://issues.jenkins-ci.org/browse/JENKINS-42490).
> [JENKINS-42490] Skip a favorite if its a folder

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmSaveFileRequest.java
- blueocean/pom.xml
- pom.xml
- Removed beta from aggreagator name
- Upgraded pipeline editor to 0.2-rc1
> RC preparation

- blueocean-dashboard/src/main/js/components/LogToolbar.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsArtifacts.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/test/js/run-details-artifacts-spec.js
See [JENKINS-40526](https://issues.jenkins-ci.org/browse/JENKINS-40526).
> [JENKINS-40526] Download logs of stages

- pom.xml
> upgrade to pipeline-model-definition 1.1.1

- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
See [JENKINS-42736](https://issues.jenkins-ci.org/browse/JENKINS-42736).
> [FIX JENKINS-42736] - nodes with empty name break visualization

- pom.xml
Minor dependency bump of scm-api
> upgrade to scm-api 2.1.1

- blueocean-personalization/src/main/js/stories/PipelineCardStories.jsx
- blueocean-personalization/src/main/less/pipeline-card.less
See [JENKINS-42942](https://issues.jenkins-ci.org/browse/JENKINS-42942).
> Fix the issues shrinking down dashboard cards

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
See [JENKINS-42932](https://issues.jenkins-ci.org/browse/JENKINS-42932).
> [JENKINS-42932] Link to full log if no stages exist

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubContent.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmSaveFileRequest.java
See [JENKINS-43014](https://issues.jenkins-ci.org/browse/JENKINS-43014).
Skipping tests as this is highly dependent on Github integration.
> [FIX JENKINS-43014] save to github from non-master branch

- pom.xml
> Pipeline editor -> 0.2.0

- blueocean-dashboard/src/main/js/creation/github/Button.jsx
- blueocean-dashboard/src/main/js/creation/github/steps/GithubCredentialStep.jsx
- blueocean-dashboard/src/main/less/creation/index.less
- See [JENKINS-42123](https://issues.jenkins-ci.org/browse/JENKINS-42123).
> Task/jenkins 42123 GitHub access token progress

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
See https://issues.jenkins-ci.org/browse/JENKINS-42872
> [JENKINS-42872] Use input step to check submission rights

- docker/official/Jenkinsfile
@rtyler is it OK for us to run this daily?
> Trigger the run for docker hub daily

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
Just updates JDL dependency to the latest version.
See [JENKINS-41833](https://issues.jenkins-ci.org/browse/JENKINS-41833).
> Update to latest JDL

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ActionProxiesImpl.java
See [JENKINS-43208](https://issues.jenkins-ci.org/browse/JENKINS-43208).
> JENKINS-43208# Exclude job history config action

- blueocean-personalization/src/main/less/pipeline-card.less
Does what it says on the box.
See [JENKINS-41833](https://issues.jenkins-ci.org/browse/JENKINS-41833).
> Update dashboard fav card padding

- blueocean-dashboard/src/main/js/components/Activity.jsx
- See [JENKINS-43257](https://issues.jenkins-ci.org/browse/JENKINS-43257).
> bug / jenkins 43257 show more table blink

- blueocean-dashboard/src/main/less/connection-lost.less
- blueocean-web/src/main/less/toaster.less
See [JENKINS-38460](https://issues.jenkins-ci.org/browse/JENKINS-38460).
Warning: depends on https://github.com/jenkinsci/jenkins-design-language/pull/161.
> [JENKINS-38460] Move toaster from bottom left to bottom right

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/less/core.less
- blueocean-core-js/src/less/parameters-run-button.less
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- The old empty state set `color: white` and the nested `ParametersRunButton` was eventually inheriting that since the `Dialog` is a child element. This is actually fixed in master already since the new empty state doesn't set that color. However it seems prudent to set a reasonable default color for this form to avoid similar issues in other places.
- See [JENKINS-43259](https://issues.jenkins-ci.org/browse/JENKINS-43259).
> bug / jenkins 43259 parameterized form unstyled

- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- pom.xml
@michaelneale @i386 Better to keep master updated with rc4 version from release.
> Rc4 release pom update

- bin/cleanInstall.js
* Add the "dev" command line switch to bin/cleanInstall so it can update devDependencies as well
* A little bit of boyscouting
> Add devDependencies support to bin/cleanInstall

- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- pom.xml
Upgrade version to 1.1.0-SNAPSHOT for next dev cycle.
@michaelneale @i386 PTAL.
> 1.1.0-SNAPSHOT pom update

- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/js/components/placeholder/DashboardPlaceholder.jsx
- blueocean-dashboard/src/main/less/placeholder.less
- See [JENKINS-43265](https://issues.jenkins-ci.org/browse/JENKINS-43265).
> bug / jenkins 43265 dashboard missing extension point

- pom.xml
> Upgrade github, github-branch-source, declarative, token-macro, mockito

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
- pom.xml
See [JENKINS-43471](https://issues.jenkins-ci.org/browse/JENKINS-43471).
> JENKINS-43471 never delete the item on reenterant case

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
See [JENKINS-42636](https://issues.jenkins-ci.org/browse/JENKINS-42636).
> [FIXED JENKINS-42636] Fix duration and start time logic

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
> Add better error message for diagnosing JENKINS-43462

- pom.xml
> Update display URL

- pom.xml
Supports display URL for non-pipeline jobs https://github.com/jenkinsci/github-plugin/pull/167
> Update to github plugin 1.27.0

- blueocean-rest/pom.xml
- blueocean-rest/src/main/java/io/jenkins/blueocean/Routable.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/ApiRoutable.java
Enforce exclusion of `hudson.*` `jenkins.*` imports with some exemptions
> Enforce exclusion of hudson.* jenkins.* imports with some exemptions

- pom.xml
> update to workflow 2.13

- pom.xml
> autofavorite 0.7

- blueocean-core-js/package.json
> Upgrade version to 0.0.99-SNAPSHOT as laster release version is 0.0.98

- blueocean-events/src/main/java/io/jenkins/blueocean/events/BlueMessageEnricher.java
I left these in accidentally @vivek
> Remove unused log statements

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
> Null check fix reported by findbugs

- blueocean-core-js/package.json
> I accendently published 0.0.100 as non-beta, this syncs things up

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
See [JENKINS-43462](https://issues.jenkins-ci.org/browse/JENKINS-43462).
> JENKINS-43462# Fixed erroneous 403 error for favorite API

- pom.xml
Comes with this important fix https://issues.jenkins-ci.org/browse/JENKINS-43630
> Update git 3.3, matrix 1.10 and declarative 1.1.3

- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
> [bumbVersion] version dance

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
See [JENKINS-42809](https://issues.jenkins-ci.org/browse/JENKINS-42809).
> JENKINS-42809# Fix for correctly showing commitId

- blueocean-core-js/test/js/capability/branches-1.json
- blueocean-core-js/test/js/capability/favorites-1.json
- blueocean-core-js/test/js/capability/pipelines-1.json
- blueocean-core-js/test/js/data/pipeline-1.json
- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/test/js/data/branches/latestBranches.js
- blueocean-personalization/src/test/js/components/DashboardCards-spec.jsx
- blueocean-personalization/src/test/js/data/favorites.json
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineFolder.java
See [JENKINS-43252](https://issues.jenkins-ci.org/browse/JENKINS-43252).
> JENKINS-43252 Remove last successful run

- README.md
> node-gyp-readme

- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/RunMessageCell.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/RunDescription.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/main/less/run-details-header.less
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
- blueocean-dashboard/src/test/js/run-description-spec.js
- blueocean-dashboard/src/test/js/run-message-cell-spec.js
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
See [JENKINS-41769](https://issues.jenkins-ci.org/browse/JENKINS-41769).
> JENKINS-41769 Developer can see a description for a pipeline run

- blueocean-core-js/README.md
> instructions for core-js publishing

- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchContainerImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
See [JENKINS-43949](https://issues.jenkins-ci.org/browse/JENKINS-43949).
> JENKINS-43949 Branch filter should use same order as branch tab

- pom.xml
> Upgrade input step, durable task step, mockito

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BlueTestResultContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BlueTestResultContainerImplTest.java
> Fix bug where tests where not being filtered by state correctly.

- blueocean-dashboard/src/main/js/components/RunMessageCell.jsx
- blueocean-dashboard/src/main/less/lozenge.less
- blueocean-dashboard/src/main/less/run-message-cell.less
> Run message was missing ellipsis and update lozenge 

- pom.xml
See [JENKINS-43975](https://issues.jenkins-ci.org/browse/JENKINS-43975).
> BranchEventCause description fix: upgrade to branch-api 2.0.9

- blueocean-dashboard/src/main/js/components/PipelineRowItem.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineSearch.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
See [JENKINS-44176](https://issues.jenkins-ci.org/browse/JENKINS-44176).
> [FIX JENKINS-44176] Fix full display name when an organization is selected

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ExtensionClassContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ExtensionClassImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueExtensionClass.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueExtensionClassContainer.java
See [JENKINS-43249](https://issues.jenkins-ci.org/browse/JENKINS-43249).
> JENKINS-43249# Return empty capabilities for unknown class

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
It was not testing anything useful.
See [JENKINS-44223](https://issues.jenkins-ci.org/browse/JENKINS-44223).
> JENKINS-44223# Removed flaky test block

- blueocean-dashboard/src/main/js/components/Activity.jsx
The value of the input should be uri decoded because it comes from the "branch" url get param that is uri encoded
See [JENKINS-44260](https://issues.jenkins-ci.org/browse/JENKINS-44260).
> decodeURI text in branch filter

- Jenkinsfile
See [JENKINS-44230](https://issues.jenkins-ci.org/browse/JENKINS-44230).
> [JENKINS-44230] Stop selenium after docker.inside

- blueocean-core-js/package.json
- blueocean-core-js/src/js/utils/UrlUtils.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/creation/git/GitCreationApi.js
- blueocean-dashboard/src/main/js/creation/github/api/GithubCreationApi.js
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitPipelineCreateRequest.java
- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrgFolderTest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractPipelineCreateRequest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineContainer.java
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
This reverts commit 09700ee05723e9213b294ea5b3cba4eb0ecb9282.
> Revert "Bug/jenkins 44432 pipeline editor save (#1078)"

- acceptance-tests/src/main/js/page_objects/blueocean/bluePipelines.js
- acceptance-tests/src/test/js/edgeCases/folder.js
> Remove loigin for edgecase test

- blueocean-config/npm-shrinkwrap.json
- blueocean-config/package.json
- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- js-extensions/package.json
- js-extensions/spec/ResourceLoadTracker-spec.js
- js-extensions/src/ResourceLoadTracker.js
Feel free to __IGNORE__ for now.
No related Jenkins JIRA. Need this for something else I'm working on.
> Ability to get/resolve extension resources (JS, CSS etc) from an external host (Vs the Jenkins master

- CONTRIBUTING.md
- README.md
@kzantow @i386 I have clarified some docs on the current state of extension points. Make sense? 
a little arm wavy on purpose.
> documentation for extension points

- blueocean-dashboard/src/main/less/core.less
See example here that the 1px fixes https://ci.blueocean.io/blue/organizations/jenkins/blueocean/detail/PR-1095/3/pipeline/#step-29-log-1087
See [JENKINS-42865](https://issues.jenkins-ci.org/browse/JENKINS-42865).
> JENKINS-42865: white-space:nowrap log line numbers

- acceptance-tests/README.md
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/ResultsPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/ParallelNavigationTest/Jenkinsfile
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/ParallelNavigationTest/Jenkinsfile.input
See https://issues.jenkins-ci.org/browse/JENKINS-44530
This is my first attempt at new style acceptance tests. 
cc @imeredith @i386
> first cut at new style e2e tests for parallel

- pom.xml
- release/Jenkinsfile
See [JENKINS-43079](https://issues.jenkins-ci.org/browse/JENKINS-43079).
How this works:
- Release build is run in a docker container with Java8 and maven 3.3.9
- Works with user scoped credentials
- Create github credentials ( github username and accessToken) and Jenkins credentials (username and password) in **user store**
- Chose which user is doing release from the drop down. At present there are only few, we can add more as needed
For it to work we need changes in pom file where it must be `https://` url under scm developerConnection setting. _This means anyone releasing from their laptop (which we do not want anyways) will no longer be able to use their ssh keys. However there are ways to automate it using GitHub access token._
I have placed release pipeline script under `release` …
> JENKINS-43079# Trusted release related changes

- release/Jenkinsfile
This was used to release 1.1.0-beta-8 version.
> Fixes in release/Jenkinsfile

- blueocean-pipeline-scm-api/src/main/resources/index.jelly
> Fix tests in intellij

- acceptance-tests/pom.xml
- acceptance-tests/run.sh
- acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
- acceptance-tests/runner/scripts/maven.sh
- acceptance-tests/src/main/java/io/blueocean/ath/ATHJUnitRunner.java
- acceptance-tests/src/main/java/io/blueocean/ath/AthModule.java
- acceptance-tests/src/main/java/io/blueocean/ath/api/classic/ClassicJobApi.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/classic/LoginPage.java
- acceptance-tests/src/main/js/custom_commands/login.js
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/FavoritesTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/FolderTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/CommitMessagesTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
Installs later deps in ATH.
Other changes in PR make tests nicer to work with.
> Enable the use of multiple Jenkins versions

- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
move editor test case into its own class
> try this out

- Jenkinsfile
- acceptance-tests/run.sh
- acceptance-tests/src/main/java/io/blueocean/ath/ATHJUnitRunner.java
- acceptance-tests/src/main/java/io/blueocean/ath/AthModule.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/classic/LoginPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/FolderTest.java
A new webdriver instance is created and cleaned up before and after each test method now.
Adds screenshotting of ATH.
> Improved Webdriver lifecycle.

- blueocean-events/src/main/java/io/jenkins/blueocean/events/BlueMessageEnricher.java
- blueocean-events/src/test/java/io/jenkins/blueocean/events/SseEventTest.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/OrganizationStatePreloader.java
See [JENKINS-44644](https://issues.jenkins-ci.org/browse/JENKINS-44644).
> JENKINS-44644# Fix for custom org sse events for activity screen

- pom.xml
Ensures that customers are using a favorite plugin without the performance issue on delete.
See [JENKINS-44579](https://issues.jenkins-ci.org/browse/JENKINS-44579).
> upgrade to favorite 2.2.0

- pom.xml
Provides a fix for [JENKINS-41576](https://issues.jenkins-ci.org/browse/JENKINS-41576).
> Upgrade to autofavorite 1.0.0

- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- pom.xml
We've cut the release branch but we've not updated the snapshot versions.
> Change version to 1.2-beta-1-SNAPSHOT

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
also fix PRs showing double pop-up buttons
See [JENKINS-44462](https://issues.jenkins-ci.org/browse/JENKINS-44462).
> fix RunDetailsHeader showing "Pull Request" in header for non-multibranch jobs

- pom.xml
[There was an advisory for this plugin](https://jenkins.io/security/advisory/2017-06-06/).
> Upgrade favorite plugin for security issue for 1.1

- pom.xml
Fixes [JENKINS-38536](https://issues.jenkins-ci.org/browse/JENKINS-38536). Thought this one would be worth adding at this late stage as Sam had spent time working on it.
> Correct a stage timing bug with an upgrade of workflow-api 

- blueocean-core-js/package.json
- blueocean-core-js/src/js/config.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/OrganizationStatePreloader.java
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-44419]](https://issues.jenkins-ci.org/browse/JENKINS-44595]).
@reviewbybees cc. @scherler
> [FIX JENKINS-44595] - Use Organization Display Name

- docu/I18N.md
> Small editorial / typo fixes

- blueocean/pom.xml
- pom.xml
Commonly used but missing from our aggregator.
> Add pipeline build and milestone steps to aggregator

- PULL_REQUEST_TEMPLATE
- Remove the "Ran ATH against" PR checklist item from the PR template.
> remove ath from pr template checklist

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/TryBlueOceanMenu.java
See [JENKINS-44926](https://issues.jenkins-ci.org/browse/JENKINS-44926).
> JENKINS-44926 prevent stackoverflow in TryBlueOceanMenu

- blueocean-dashboard/src/main/js/creation/ClassicCreationLink.jsx
- blueocean-dashboard/src/main/less/creation/index.less
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
See [JENKINS-44931](https://issues.jenkins-ci.org/browse/JENKINS-44931).
> change the icon for the "go to classic" link, drop the "go to" from the link text

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
> Fix flaky testNewPipelineQueueItem

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
> Fix flakey getPipelineRunsStopTest

- acceptance-tests/src/test/js/log-karaoke/parametrisedPipeline.js
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
> remove redundant assertions and stabilise abort test

- pom.xml
> Upgrade to declarative 1.1.6

- acceptance-tests/src/main/java/io/blueocean/ath/AthModule.java
- acceptance-tests/src/main/java/io/blueocean/ath/factory/BranchPageFactory.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/ActivityPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/BranchPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/DashboardPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/NavigationTest.java
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/NavigationTest/Jenkinsfile
- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/PullRequest.jsx
- blueocean-dashboard/src/main/js/components/RunHistoryButton.jsx
> JENKINS-44866 1.1.x merge

- blueocean-dashboard/src/main/less/core.less
* Remove some old junk styles that were screwing up layout
See [JENKINS-44922](https://issues.jenkins-ci.org/browse/JENKINS-44922).
> JENKINS-44922 Remove incorrect margins from tables

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchContainerImpl.java
This resulted in some branches not appearing at the top of the branches table when the developer viewed the Branches or PR tab in the UI.
This is only an issue if there > 100 branches or pull requests
Discovered by @michaelneale and debugged over hangouts.
> We incorrectly sorted the page vs base collection for branches and PRs

- pom.xml
> Upgrade workflow-durable-task-step

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/less/run-details-header.less
See [JENKINS-43978](https://issues.jenkins-ci.org/browse/JENKINS-43978).
> JENKINS-43978 Stop really long cause messages from blowing out results screen

- blueocean-dashboard/src/main/less/run-details-header.less
See [JENKINS-45123](https://issues.jenkins-ci.org/browse/JENKINS-45123).
> fix github link disappearing when branch name is too long

- blueocean-dashboard/src/main/js/creation/github/steps/GithubCredentialStep.jsx
- See [JENKINS-44722](https://issues.jenkins-ci.org/browse/JENKINS-44722).
> improvement/jenkins 44722 GitHub token password field

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GitHubFactory.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
We did not set an abuse rate handler so we could see "mysterious" hangs in creation.
See [JENKINS-44107](https://issues.jenkins-ci.org/browse/JENKINS-44107).
> Ensure we use the limit and abuse rate handlers consistently

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/Caches.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/CachesTest.java
> Fix issue where nagative hits are put in the cache as null and it NPEs

- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/BrowserAndOperatingSystemAnalyticsProperties.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/BrowserAndOperatingSystemAnalyticsPropertiesTest.java
- pom.xml
Adds browser and client OS data to each analytics event
> Add browser and operating system stats to all event properties

- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
> CoreJS dance

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
> flaky test fixing as it is shitting me to tears

- blueocean-rest-impl/pom.xml
- pom.xml
Duplicate declarations of dependencies. Instance identity needs to be provided.
> fix pom warnings

- jenkins-design-language/package.json
- jenkins-design-language/src/js/components/forms/Dropdown.jsx
- jenkins-design-language/src/js/stories/DropdownStories.jsx
- jenkins-design-language/test/js/components/Dropdown-spec.jsx
See [JENKINS-45292](https://issues.jenkins-ci.org/browse/JENKINS-45292).
Adding feature, story book and test case.
> [JENKINS-45292] Dropdown should allow custom footer 

- blueocean-events/src/main/java/io/jenkins/blueocean/events/PipelineEventListener.java
- pom.xml
Uses more recently added listener APIs to avoid tricks with `RunListener`.
No special test coverage; presumably would be covered by existing tests.
@reviewbybees esp. @abayer
> Use GraphListener and FlowExecutionListener to receive events

- blueocean-dashboard/README.md
- blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
- blueocean-dashboard/src/main/less/core.less
- blueocean-dashboard/src/test/js/run-details-changes-spec.js
See [JENKINS-41833](https://issues.jenkins-ci.org/browse/JENKINS-41833).
> Update run changes tab to new tables

- Jenkinsfile
> ATH 2.60.1

- README.md
This is a very simple fix for a grammar error in the README.md.
> Simple grammar correction

- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/BranchPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
> JENKINS-44698: test new branch creation

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
See [JENKINS-45186](https://issues.jenkins-ci.org/browse/JENKINS-45186).
> Jenkins-45186 make header link a real anchor

- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubAddServerDialogPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubEnterpriseCreationPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEnterpriseCreationTest.java
api.github.com already in the list messes up the GHE test, as it wants to use it to test GHE (as github cloud is same API).
> Lets see if this makes it clearer

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerContainer.java
> Impersonate SYSTEM for addEndpoint

- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/ActivityPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubAddServerDialogPage.java
> Increase timeout on ATH

- pom.xml
> Update to pubsub 1.11-SNAPSHOT

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/HttpRequest.java
Improving error messages to help debug [JENKINS-45253](https://issues.jenkins-ci.org/browse/JENKINS-45253).
> Disembiguate generic "Not Found" error reported in JENKINS-45253

- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/ActivityPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubAddServerDialogPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubCreationPage.java
> relax more timings

- acceptance-tests/src/main/java/io/blueocean/ath/ATHJUnitRunner.java
- acceptance-tests/src/main/java/io/blueocean/ath/Retry.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEnterpriseCreationTest.java
> Add retry support for tests via @Retry(n)

- acceptance-tests/src/main/java/io/blueocean/ath/ATHJUnitRunner.java
- acceptance-tests/src/main/java/io/blueocean/ath/AthModule.java
> Take ScreenShots on any exception

- pom.xml
See https://github.com/jenkinsci/pubsub-light-module/pull/13.
> pubsub-1.12

- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubMockBase.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrgFolderPermissionsTest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrgFolderTest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/OrganizationStatePreloader.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/credential/CredentialContainer.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/preload/BlueOceanWebURLBuilderOrgOnFolderTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractPipelineCreateRequest.java
- pom.xml
This PR joins https://github.com/jenkinsci/blueocean-plugin/pull/1265 and https://github.com/jenkinsci/blueocean-plugin/pull/1252
> 1.1-steel: [JENKINS-45703][JENKINS-45442] [JENKINS-45482] [JENKINS-45360] Several fixes around organizations

- blueocean-commons/pom.xml
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/JSONDataWriter.java
- blueocean-commons/src/test/java/io/jenkins/blueocean/commons/stapler/export/JSONDataWriterTest.java
- pom.xml
Same patch as https://github.com/stapler/stapler/pull/122
See [JENKINS-45099](https://issues.jenkins-ci.org/browse/JENKINS-45099).
> JENKINS-45099 special JSON characters are not consistently quoted

- blueocean-core-js/package.json
- jenkins-design-language/package.json
Bump JDL and core-js to snapshot versions
> Bump JDL and core-js to snapshot

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineQueueContainer.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultibranchPipelineRunContainer.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderRunContainerImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineScm.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/KnownCapabilities.java
This is to allow pipeline editor to trigger indexing when it needs to trigger indexing on a MBP.
This can also allow blueocean UI to allow triggering.
See [JENKINS-45922](https://issues.jenkins-ci.org/browse/JENKINS-45922).
> JENKINS-45922# Add indexing capability to MBP

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/jira/BlueJiraIssue.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/jira/JIRAIssue.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListener.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetResource.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/jira/BlueJiraIssueTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListenerTest.java
- blueocean-rest/pom.xml
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/factory/BlueIssueFactory.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueChangeSetEntry.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueIssue.java
- pom.xml
When a JIRA issue is quoted in a comment message it should link to that ticket on JIRA.
Adds the following structure to every runs changesets:
```
{
"changeSet": [
{
"_class": "io.jenkins.blueocean.service.embedded.rest.ChangeSetResource",
"affectedPaths": [
"bug/asdsada"
],
"author": {
"_class": "io.jenkins.blueocean.service.embedded.rest.UserImpl",
"avatar": null,
"email": "noreply@github.com",
"fullName": "noreply",
"id": "noreply",
"permission": null
},
"commitId": "1e96c711d6e57f763e99eeb5b0843c7cf1585965",
"issues": [
{
"_class": "io.jenkins.blueocean.service.embedded.jira.BlueJiraIssue",
"id": "JENKINS-35808",
"url": "https://issues.jenkins-ci.org/browse/JENKINS-35808"
}
],
"msg": "JENKINS-35808 hello world",
"timestamp": "2017-08-02T08:53:45.000+1000",
"url": …
```
> JENKINS-45920 Backend for JIRA integration

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerEndpoint.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerEndpointContainer.java
- blueocean-bitbucket-pipeline/src/main/resources/io/jenkins/blueocean/blueocean_bitbucket_pipeline/Messages.properties
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerEndpointTest.java
See [JENKINS-45594](https://issues.jenkins-ci.org/browse/JENKINS-45594).
> JENKINS-45594# Updated min version requirement message for bb server

- pom.xml
> Dependency upgrades 7th August 2017

- Jenkinsfile
> Fixed 2.60.1 LTS version

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/APIHeadTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/ApiHead.java
See [JENKINS-46025](https://issues.jenkins-ci.org/browse/JENKINS-46025).
> [JENKINS-46025] - Set default cache control for REST API calls

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/APIHeadTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/ApiHead.java
Cherry Pick https://github.com/jenkinsci/blueocean-plugin/pull/1303
> Chery Pick - [JENKINS-46025] - Set default cache control for REST API calls (#1303)

- blueocean-dashboard/src/main/js/creation/bitbucket/steps/BbOrgListStep.jsx
- blueocean-dashboard/src/main/js/creation/bitbucket/steps/BbRepositoryStep.jsx
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
* Change wording for BB cloud orgs
See [JENKINS-45561](https://issues.jenkins-ci.org/browse/JENKINS-45561).
> Change wording for BB cloud orgs

- pom.xml
Resolves a dependency issue introduced in 2.4
> Update JIRA to 2.4.2

- blueocean-dashboard/src/main/js/components/RunDetailsArtifacts.jsx
- blueocean-dashboard/src/test/js/data/runs/latestRuns.js
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/htmlpublisher/HTMLArtifact.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/htmlpublisher/HTMLArtifactTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/htmlpublisher/HTMLArtifactTest.jenkinsfile
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ArtifactContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ArtifactImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/factory/BlueArtifactFactory.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueArtifact.java
- pom.xml
*Example Jenkinsfile*
```
node {
sh 'mkdir coverage'
sh 'touch coverage/foo.html'
sh 'echo "hello world" > coverage/index.html'
publishHTML (target: [
allowMissing: false,
alwaysLinkToLastBuild: false,
keepAll: true,
reportDir: 'coverage',
reportFiles: 'index.html',
reportName: "My Cool report"
])
}
```
*Showing on artifact screen*
See [JENKINS-40616](https://issues.jenkins-ci.org/browse/JENKINS-40616).
> JENKINS-40616 Show publishHTML() reports on Blue Ocean

- blueocean-dashboard/src/main/js/components/PullRequestRow.jsx
* Fix an issue passing translate function to child components
See [JENKINS-46070](https://issues.jenkins-ci.org/browse/JENKINS-46070).
> JENKINS-46070 PR page broken on dogfood

- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrgFolderPermissionsTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanRootAction.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
> Put overall READ permission check at API root

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueItemImpl.java
> Feedback from Alvaro

- blueocean-dashboard/src/main/js/creation/bitbucket/server/steps/BbChooseServerStep.jsx
- blueocean-dashboard/src/main/js/creation/github-enterprise/steps/GHEChooseServerStep.jsx
- blueocean-dashboard/src/main/less/creation/index.less
See [JENKINS-46187](https://issues.jenkins-ci.org/browse/JENKINS-46187).
> Make server disambiguation in Github/Bitbucket italic

- acceptance-tests/src/main/java/io/blueocean/ath/api/classic/ClassicJobApi.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/DashboardPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/dashboard/search/SearchTest.java
> JENKINS-44761: Fastsearch ATH coverage

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractPipelineCreateRequest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/factory/organization/OrganizationFactory.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineContainer.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineCreateRequest.java
Follow up - https://github.com/jenkinsci/blueocean-plugin/pull/1278#discussion_r131783811
Tracked as JENKINS-46125
> Use organization for PipelineCreateRequest

- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- See [JENKINS-45215](https://issues.jenkins-ci.org/browse/JENKINS-45215).
- Testing these changes via CI; will upgrade to prod release once verified.
> upgrade to latest js-builder-jest beta for testing

- blueocean-dashboard/src/main/js/creation/bitbucket/cloud/BbCloudFlowManager.js
- Small patch as discussed in #1327 here: https://github.com/jenkinsci/blueocean-plugin/pull/1327#pullrequestreview-56499888
> fix scenario where bitbucket creation was not redirecting

- blueocean-dashboard/src/main/js/creation/CreatePipelineScmListRenderer.jsx
- blueocean-dashboard/src/main/js/creation/bitbucket/cloud/BbCloudScmProvider.jsx
- blueocean-dashboard/src/main/js/creation/bitbucket/server/BbServerScmProvider.jsx
- blueocean-dashboard/src/main/js/creation/bitbucket/server/steps/BbChooseServerStep.jsx
- blueocean-dashboard/src/main/less/creation/github-enterprise.less
See [JENKINS-46218](https://issues.jenkins-ci.org/browse/JENKINS-46218).
> reorder source control buttons

- pom.xml
- Use latest published version of Editor plugin.
> hotfix / upgrade editor plugin

- acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
> Update ath deps 

- pom.xml
> Bump up editor version to 0.3.0-beta-5

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- jenkins-design-language/package.json
Publish JDL + Core JS, update deps
> Publish JDL + Core JS, update deps

- blueocean-pipeline-editor/pom.xml
> Remove scm settings and update wiki url

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- pom.xml
> bump up pom version for 1.3.0 development

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- pom.xml
> Prepare release version

- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages_zh.properties
- blueocean-personalization/src/main/resources/jenkins/plugins/blueocean/personalization/Messages_zh.properties
- blueocean-web/src/main/resources/jenkins/plugins/blueocean/web/Messages_zh.properties
updated: https://github.com/jenkinsci/blueocean-plugin/pull/1298
> Chinese l10n

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmSaveFileRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/HttpRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmContentProviderTest.java
- blueocean-github-pipeline/src/test/resources/api/__files/body-branches-master-BELLU.json
To test, create a pipeline using editor or edit existing pipeline using editor and save on new branch. 
See [JENKINS-46704](https://issues.jenkins-ci.org/browse/JENKINS-46704).
> JENKINS-46704# Fix for save content to new branch on github

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/less/run-button.less
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-pipeline-editor/npm-shrinkwrap.json
- blueocean-pipeline-editor/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- jenkins-design-language/less/components/material-icon.less
- jenkins-design-language/package.json
- jenkins-design-language/src/js/components/material-ui/SvgIcon/SvgIcon.js
Fix re-run button material icons svgs color and alignment problem
> Fix re-run button material icons svgs color and alignment problem

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListenerTest.java
- pom.xml
> JENKINS-46723# Pick httpclient from bitbucket plugin

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/ScmResourceImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderTest.java
See [JENKINS-46879](https://issues.jenkins-ci.org/browse/JENKINS-46879).
> [JENKINS-46879] Check permissions against the item where the pipeline  is in

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/ScmResourceImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderTest.java
…  is in (#1393)
Backport of PR #1393 to release/1.2
* [JENKINS-46879] Check permissions against the item where the pipeline is in
* [JENKINS-46879] Fix failing test
> [JENKINS-46879] Check permissions against the item for 1.2

- blueocean-personalization/src/main/js/components/FavoritePipeline.jsx
just added a check for multibranch pipelines that if they do not have any branches the favorite button should not appear
See [JENKINS-44033](https://issues.jenkins-ci.org/browse/JENKINS-44033).
> JENKINS-44033 hide the favorite button in the header of empty multibranch pipelines

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/factory/BlueIssueFactory.java
- blueocean-web/pom.xml
- pom.xml
Port PRs from 1.3 master to release/1.2:
https://github.com/jenkinsci/blueocean-plugin/pull/1371
https://github.com/jenkinsci/blueocean-plugin/pull/1384
> Remove metrics and defensive code

- blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListener.java
Just a cherry pick of https://github.com/jenkinsci/blueocean-plugin/pull/1364
> [JENKINS-46452] Don't reference null Jira session (#1364)

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
See [JENKINS-45333](https://issues.jenkins-ci.org/browse/JENKINS-45333).
Downstream of #1383 
This small change fixes the remaining failing test in the PCT after #1383 
@reviewbybees specially @michaelneale @vivek 
- [] Change is code complete and matches issue description
> [JENKINS-45333] Give some time to the test's job to really start

- acceptance-tests/README.md
- acceptance-tests/live.properties.sample
Adds required/optional roles to README and sample props file to save others time in the future.
No testing required.
> add required roles to acceptance-tests readme and props file

- blueocean-web/src/main/js/DevelopmentFooter.jsx
Removing all this logic since I don't think there's much value anyway.
With Git, the sha is enough to identify the exact code base associated to the thing in use. So I don't think it's worth spending any time making this work better/again.
I am still building this change locally to test it since I'm still mostly a React/jsx newbie, but pushing this for review as this seems relatively straightforward. I guess a code review is enough for testing, but again I'm building it locally to assess this anyway. 
See [JENKINS-46959](https://issues.jenkins-ci.org/browse/JENKINS-46959).
> [FIX JENKINS-46959] Remove unnecessary "no branch"

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketApi.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudApi.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/model/BbServerBranch.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/BlueOceanConfigProperties.java
- blueocean-github-pipeline/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/JwtAuthenticationFilter.java
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/src/main/java/io/blueocean/rest/pipeline/editor/PipelineMetadataService.java
- blueocean-rest-impl/pom.xml
- blueocean/pom.xml
- docker/official/pom.xml
- pom.xml
See [JENKINS-45333](https://issues.jenkins-ci.org/browse/JENKINS-45333).
> JENKINS-45333# PCT fix: upgrade plugin pom

- CODEOWNERS
Hey @vivek @kzantow 
this is as discussed with vivek. According to https://github.com/blog/2392-introducing-code-owner
this means that pom.xml changes have to be acked by vivek (or keith or myself if vivek is on a plane or something). This is to keep a close eye on versions especially as all the changes to comply with the PCT were merged in.
> code owners

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GitHubFactory.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubRepositories.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubRespositoryContainer.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerContainer.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/HttpRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubApiTest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmTest.java
See [JENKINS-47042](https://issues.jenkins-ci.org/browse/JENKINS-47042).
> JENKINS-47042# HTTP proxy support for github access

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GitHubFactory.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubRepositories.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubRespositoryContainer.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/HttpRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubApiTest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmTest.java
See [JENKINS-47042](https://issues.jenkins-ci.org/browse/JENKINS-47042).
> JENKINS-47042# HTTP proxy support for github access release/1.1

- blueocean-rest-impl/pom.xml
- pom.xml
A simple version bump. see 
https://issues.jenkins-ci.org/browse/JENKINS-47083
@abayer @kzantow anything more than this needed?
> upgrade declarative to the released version 1.2

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-pipeline-editor/npm-shrinkwrap.json
- blueocean-pipeline-editor/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- jenkins-design-language/package.json
See [JENKINS-46948](https://issues.jenkins-ci.org/browse/JENKINS-46948).
> Publish JDL and core-js and update deps

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/BlueOceanConfigProperties.java
- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/ssh/UserSSHKeyTest.java
Not really sure how this test is meant to work when parent sets the jwt mode to on in a static... so trying this...
> Set jwt disable const for test

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/BlueOceanConfigProperties.java
- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/ssh/UserSSHKeyTest.java
See https://issues.jenkins-ci.org/browse/JENKINS-47122
> Fix failing git ssh test

- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveRequest.java
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtils.java
- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
- blueocean-pipeline-editor/src/main/js/GitUtils.js
- blueocean-pipeline-editor/src/main/js/PipelineEditorLink.jsx
> Disable the editor for non-SSH git repositories

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-config/src/test/java/io/jenkins/blueocean/config/BlueOceanConfigFactoryTest.java
- blueocean-events/src/test/java/io/jenkins/blueocean/events/SseEventTest.java
- blueocean-jira/src/test/java/io/jenkins/blueocean/service/embedded/jira/BlueJiraIssueTest.java
- blueocean-jira/src/test/java/io/jenkins/blueocean/service/embedded/jira/JiraPluginJenkinsRule.java
- blueocean-jira/src/test/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListenerTest.java
- blueocean-jwt/src/test/java/io/jenkins/blueocean/auth/jwt/impl/JwtAuthenticationServiceImplTest.java
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/BlueOceanWebURLBuilderTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-editor/src/test/java/io/blueocean/rest/pipeline/editor/PipelineMetadataServiceTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BlueOceanWebURLBuilderTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/AnalyticsTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/KeenAnalyticsTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/BlueJUnitTestResultTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/DefaultRunImplTest.java
- pom.xml
Fixes running unit tests from inside IDEA.
See [JENKINS-47114](https://issues.jenkins-ci.org/browse/JENKINS-47114).
> JENKINS-47114# Upgrade plugin-pom and jenkins-test-harness

- jenkins-design-language/src/js/components/forms/TextInput.jsx
- jenkins-design-language/test/js/components/TextInput.spec.jsx
See [JENKINS-47148](https://issues.jenkins-ci.org/browse/JENKINS-47148).
@reviewbybees @cloudbees/team-astro
> [FIX JENKINS-47148] Add a11y support for textInput

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/less/extensions.less
- blueocean-dashboard/src/main/less/tab-badge-icon.less
Puts a little "notification" badge on the "Tests" when there are test failures.
See [JENKINS-46951](https://issues.jenkins-ci.org/browse/JENKINS-46951).
> feature/JENKINS-46951-highlight-test-failures 

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- pom.xml
We have release/1.3 branch off 1.3.0-beta-5. Master can now be updated to 1.4.0-beta-1-SNAPSHOT.
> Changed pom version for 1.4.0 development

- blueocean-dashboard/src/main/js/components/ActivityDetailsRow.jsx
See [JENKINS-46657](https://issues.jenkins-ci.org/browse/JENKINS-46657).
> JENKINS-46657 Show run name in run column on the activity tab instead of run id

- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java
This has helped in the past - a less contrived pipeline
> change test pipeline for full create

- acceptance-tests/src/main/java/io/blueocean/ath/WaitUtil.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubCreationPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java
If unable to auto redirect, load the activity page (which is future functionality)
> Redirect on timeout

- acceptance-tests/src/main/java/io/blueocean/ath/WaitUtil.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubCreationPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java
from master... to correct timing out test
> 1.3 branch: Redirect on timeout (#1453)

- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
See https://issues.jenkins-ci.org/browse/JENKINS-47246
> Fix test number '0' issue 

- blueocean-dashboard/src/main/less/core.less
Hot-fix to resolve ResultItem overflow without JDL update (only on 1.3)
* NOT FOR MASTER * This will break if combined with #1440 
See [JENKINS-47211](https://issues.jenkins-ci.org/browse/JENKINS-47211).
> JENKINS-47211 Hot-fix for 1.3 to resolve ResultItem overflow

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/disableDescription.jenkinsfile
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
Adds a system property to disable run descriptions
See [JENKINS-45719](https://issues.jenkins-ci.org/browse/JENKINS-45719).
> JENKINS-45719 allow disabling of run description

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-pipeline-editor/npm-shrinkwrap.json
- blueocean-pipeline-editor/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- jenkins-design-language/package.json
- jenkins-design-language/src/js/components/ResultItem.jsx
- jenkins-design-language/src/js/stories/resultItemStories.jsx
See [JENKINS-47211](https://issues.jenkins-ci.org/browse/JENKINS-47211).
> JENKINS-47211 ResultItem headers overflowing in Dashboard

- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-pipeline-editor/package.json
- blueocean-web/package.json
see: https://issues.jenkins-ci.org/browse/JENKINS-47304 
lint should be done as mvnbuild not test phase
> do lint at earlier stage

- pom.xml
See [JENKINS-41578](https://issues.jenkins-ci.org/browse/JENKINS-41578).
> JENKINS-41578 Upgrade to display-url-api 2.1.0

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ModelBuilder.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Property.java
https://github.com/stapler/stapler/pull/127
See [JENKINS-47338](https://issues.jenkins-ci.org/browse/JENKINS-47338).
> Backport Stapler performance improvements

- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
Couldn't use the TextInput component for this because of the way it manages its state value
See [JENKINS-46104](https://issues.jenkins-ci.org/browse/JENKINS-46104).
> Do not allow the new branch input in the editor to accept space chars

- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
Fixes cases where the editor attempts to display a credential dialog but it is hidden.
See [JENKINS-47310](https://issues.jenkins-ci.org/browse/JENKINS-47310).
> [FIX JENKINS-47310] Handle various cases of credential errors when loading the editor

- blueocean-core-js/package.json
- blueocean-core-js/src/js/config.js
See [JENKINS-47368](https://issues.jenkins-ci.org/browse/JENKINS-47368).
> [JENKINS-47368] 1.3: Regression: core-js config.js forces to have windows.location

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- pom.xml
version update in preparation for 1.3.0 release.
> version update in preparation for 1.3.0 release

- blueocean-pipeline-editor/src/main/js/components/editor/EditorMain.jsx
- blueocean-pipeline-editor/src/main/js/services/PipelineStore.js
See [JENKINS-47249](https://issues.jenkins-ci.org/browse/JENKINS-47249).
Same as #1445
> [FIX JENKINS-47249] Remove name parallel group dialog (master)

- blueocean-dashboard/src/main/js/creation/git/GitConnectStep.jsx
- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
- blueocean-pipeline-editor/src/main/js/GitUtils.js
- blueocean-pipeline-editor/src/main/js/PipelineEditorLink.jsx
> [FIX JENKINS-47248] Show warning about non-SSH repositories not supporting editing (master)

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/util/GlobMatcher.java
Used to find out what the bad pattern is thats causing the exception. See the exception on the JIRA issue.
See [JENKINS-47396](https://issues.jenkins-ci.org/browse/JENKINS-47396).
> Add the bad pattern to the exception for debugging

- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
See [JENKINS-47361](https://issues.jenkins-ci.org/browse/JENKINS-47361).
> JENKINS-47361 remove single quotes from loaded repositories msg

- blueocean-events/pom.xml
> UX-668# Remove jsch, its not used

- blueocean-core-js/src/js/config.js
See [JENKINS-47368](https://issues.jenkins-ci.org/browse/JENKINS-47368).
same as #1471 but for master
> [JENKINS-47368-master] prevent npe when no window.location

- blueocean-core-js/src/js/components/RunButton.jsx
Fixes a minor typo in the stopp(p)ing toast.
> Fix typo in stop button toast default value.

- acceptance-tests/src/test/js/failingStages.js
- acceptance-tests/src/test/js/log-karaoke/noStages.js
- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Step.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Steps.jsx
Disable log tailing during karaoke mode unless user has explicitly expanded a step
See [JENKINS-45182](https://issues.jenkins-ci.org/browse/JENKINS-45182).
> JENKINS-45182 In progress log should be collapsed by default

- blueocean-pipeline-editor/src/test/java/io/blueocean/rest/pipeline/editor/PipelineMetadataServiceTest.java
See [JENKINS-47504](https://issues.jenkins-ci.org/browse/JENKINS-47504).
>  JENKINS-47504# Fix declarativeAgents test so that it works with later versions of model definition plugin

- acceptance-tests/README.md
> Update docs for recent ATH improvements

- CODEOWNERS
hey @scherler @kzantow @cliffmeyers thoughts on this? Just means github will nag you any time there is a change in here.
> Add some code reviewers for JDL

- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
> Fix invalid username/password message for Bitbucket

- blueocean-dashboard/src/main/js/components/PipelineRowItem.jsx
- jenkins-design-language/less/components/expandable-path.less
- jenkins-design-language/src/js/components/ExpandablePath.jsx
See [JENKINS-47648](https://issues.jenkins-ci.org/browse/JENKINS-47648).
> JENKINS-47648 re-add expander folder icon in the dahsboard

- blueocean-dashboard/src/main/less/core.less
increase css specificity of the show more button so the it center alignes 
See [JENKINS-47580](https://issues.jenkins-ci.org/browse/JENKINS-47580).
> JENKINS-47580 Center align show more button

- acceptance-tests/run.sh
disable stats when running ATH
> Disable usage statistics when running ATH tests

- pom.xml
There is not JIRA issue since this is small change with no user impact.
> Added the licensing definition on this Maven project

- pom.xml
See [JENKINS-47847](https://issues.jenkins-ci.org/browse/JENKINS-47847).
> JENKINS-47847# Upgrade bitbucket-branch-source to 2.2.5

- blueocean-dashboard/src/main/js/components/karaoke/rest/KaraokeApi.js
In the process of preparing https://github.com/jenkinsci/blueocean-plugin/pull/1517, I identified some duplication in the processing of API responses that can be removed.
> Simplify the dashboard API client a little

- blueocean-dashboard/src/main/js/components/karaoke/services/Augmenter.js
This is probably enough for most people’s pipelines. Alternative approach to https://github.com/jenkinsci/blueocean-plugin/pull/1530.
See [JENKINS-41205](https://issues.jenkins-ci.org/browse/JENKINS-41205).
There's no tests to modify/augment.
> [JENKINS-41205] Request 10,000 nodes at a time

- jenkins-design-language/src/js/components/forms/Dropdown.jsx
This PR adjust the position of the dropdown element to prevent sticking out of the viewport.
See [JENKINS-47788](https://issues.jenkins-ci.org/browse/JENKINS-47788).
> JENKINS-47788 Adjust the position of the dropdown element

- blueocean-core-js/src/less/run-button.less
Make the run button visible on the PR tab (it was white against the white background making it invisible)
See [JENKINS-47888](https://issues.jenkins-ci.org/browse/JENKINS-47888).
> JENKINS-47888 make run button visible on the PR tab

- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubCreationPage.java
- Try to deflake the GithubEditorTest by using `wait.click` which has retry behavior and inital check for "elementIsClickable" baked in.
- Eventually we'll switch this to use the `find`/`click` `SmartWebElement` stuff again probably once #1529 lands
> hotfix / github editor test deflake

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MatrixProjectImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/util/Capabilities.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/util/FavoriteUtil.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/util/CapabilitiesTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/KnownCapabilities.java
See [JENKINS-47835](https://issues.jenkins-ci.org/browse/JENKINS-47835).
> Favoriting a multi-configuration job breaks blueocean favourites

- blueocean-dashboard/src/main/js/components/karaoke/services/Augmenter.js
As reported in the ticket, port of PR #1531 fixes this issue. 
See [JENKINS-47480](https://issues.jenkins-ci.org/browse/JENKINS-47480).
> [JENKINS-47480] Jenkins rendering error fix in 1.3.0

- blueocean-pipeline-editor/src/main/less/editor.less
See [JENKINS-47354](https://issues.jenkins-ci.org/browse/JENKINS-47354).
> JENKINS-47354 fix ie11 stage config styling

- docker/official/Dockerfile
See [JENKINS-47918](https://issues.jenkins-ci.org/browse/JENKINS-47918).
> [JENKINS-47918] "plugins" dir is created as root

- pom.xml
Allows users to control autofavorite behaviour from their user profile.
See [JENKINS-47214](https://issues.jenkins-ci.org/browse/JENKINS-47214).
> Upgrade autofavorite 1.2.0

- blueocean-dashboard/src/main/js/components/karaoke/components/LogConsole.jsx
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/UserImplPermissionTest.java
Cherry pick of fixes for unit tests for newer core, a flaky test that PCT picked up, and log performance improvements. 
https://github.com/jenkinsci/blueocean-plugin/pull/1521
https://github.com/jenkinsci/blueocean-plugin/pull/1552
https://github.com/jenkinsci/blueocean-plugin/pull/1571
> 1.3 small fixes for compatibility and performance

- blueocean-dashboard/src/main/js/components/ActivityDetailsRow.jsx
- blueocean-dashboard/src/main/js/components/BranchDetailsRow.jsx
- blueocean-dashboard/src/main/js/components/LinkifiedText.jsx
- blueocean-dashboard/src/main/js/components/RunMessageCell.jsx
- blueocean-dashboard/src/main/less/core.less
- blueocean-dashboard/src/main/less/extensions.less
- blueocean-dashboard/src/main/less/mixins/overflow-ellipsis.less
- blueocean-dashboard/src/main/less/mixins/text-overflow.less
- blueocean-dashboard/src/main/less/run-details-header.less
- blueocean-dashboard/src/main/less/run-message-cell.less
- jenkins-design-language/less/components/dropdown.less
- jenkins-design-language/less/components/jtable.less
- jenkins-design-language/less/components/table.less
- jenkins-design-language/less/mixins.less
- jenkins-design-language/less/mixins/overflow-ellipsis.less
- jenkins-design-language/less/mixins/text-overflow.less
- jenkins-design-language/src/js/components/CommitId.jsx
See [JENKINS-47649](https://issues.jenkins-ci.org/browse/JENKINS-47649), [JENKINS-48268](https://issues.jenkins-ci.org/browse/JENKINS-48268).
> Jenkins-47649&48268 fix activity and branch rows ellipsis issues and clicking areas

- blueocean-events/src/main/java/io/jenkins/blueocean/events/BlueMessageEnricher.java
cherry pick of: 
https://github.com/jenkinsci/blueocean-plugin/pull/1594
improving: https://issues.jenkins-ci.org/browse/JENKINS-48587
> 1.3: Harden message enricher (#1594)

- blueocean/pom.xml
Probably need to include the new modules as direct dependencies of the aggregator.
> Add jdl & core-js to aggregator. Whoops!

- blueocean-events/src/test/java/io/jenkins/blueocean/events/SseEventTest.java
Replacement for https://github.com/jenkinsci/blueocean-plugin/pull/1601. cc: @michaelneale 
Related to: [JENKINS-48531](https://issues.jenkins-ci.org/browse/JENKINS-48531).
> Make sure failing tests fails the tests

- docu/I18N.md
> fix i18next plural link

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlObjectImpl.java
Reverts jenkinsci/blueocean-plugin#1606
> Revert "JENKINS-48322# Fix replaceIfNotAtTopLevel warning"

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlObjectImpl.java
See [JENKINS-48322](https://issues.jenkins-ci.org/browse/JENKINS-48322).
> JENKINS-48322# remove ModelObject reference from BlueOceanUrlObjectImpl

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/KeenAnalyticsImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/AnalyticsTest.java
We need to work out how much data we are actually sending back before this gets turned on
> Disable analytics

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Version update for 1.4.0 release

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Version update for 1.5.0 development

- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEnterpriseCreationTest.java
- blueocean-dashboard/src/main/js/creation/github-enterprise/GHEAddServerDialog.jsx
While adding a new GHE server, if the url is invalid, check if the URL ends with "/api/v3" and if not, append it and re-try adding the server. This way if the url is being re-writen by a reverse proxy it will still work.
See [JENKINS-47395](https://issues.jenkins-ci.org/browse/JENKINS-47395).
> JENKINS-47395 for github server pipeline creation if url is invalid try appending /api/v3

- acceptance-tests/src/test/java/io/blueocean/ath/offline/pipeline/ArtifactsTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
This PR removes the download link if there are no artifacts to download
See [JENKINS-45037](https://issues.jenkins-ci.org/browse/JENKINS-45037).
> [JENKINS-45037] Remove download link if there are no artifacts

- CODEOWNERS
Hopefully I'll still find time to contribute a few PR's here or there but for now probably sensible to remove me from this list. :/
> remove cliffmeyers from JDL codeowners

- acceptance-tests/README.md
- blueocean-rest/README.md
- docu/I18N.md
Propose a couple of spelling corrections
just a small doc change
> Propose a couple of spelling corrections - trailing whitespace ?

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ExportInterceptor.java
A cherry pick from https://github.com/jenkinsci/blueocean-plugin/pull/1625
cc @vivek @sophistifunk I think this makes sense for a 1.4.1 release.
> 1.4 cherry pick: JENKINS-48198 - Add logging when a property is skipped (#1625)

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketApiFactory.java
Sezpoz actually doesn't care, but well let's reduce the WTF/line ratio :P.
I didn't file a JIRA since this is a small and pretty obvious fix. But if you feel this ought to have one, please let me know.
@reviewbybees
> Use the right ExtensionPoint class

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
Just a little extra logging (with run id for context) when things go wrong to aid troubleshooting.
See [JENKINS-48198](https://issues.jenkins-ci.org/browse/JENKINS-48198).
> Log run identifier when something goes wrong walking the execution graph

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
See https://github.com/jenkinsci/blueocean-plugin/pull/1648
> hotfix/JENKINS-48198-node-graph-logging * Cherry pick #1648 to 1.4

- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-web/src/main/resources/jenkins/plugins/blueocean/web/Messages.properties
- jenkins-design-language/src/js/components/favorite/Favorite.jsx
Adds a missing tooltip for the configure cog in the pipeline and run details screens and fixes the favourite/remove favourite icon tooltips
See [JENKINS-47386](https://issues.jenkins-ci.org/browse/JENKINS-47386).
> JENKINS-47386 fix icon tooltips

- jenkins-design-language/package.json
published a new version of the JDL
See [JENKINS-47022](https://issues.jenkins-ci.org/browse/JENKINS-47022).
> publish new version of the JDL for JENKINS-47022

- pom.xml
Bump up bitbucket-branch-source to 2.2.9, it includes multiple fixes around lightweight checkout and general improvements.
See [JENKINS-47978](https://issues.jenkins-ci.org/browse/JENKINS-47978).
> JENKINS-47978# Includes fixes related to lightweight PR merge

- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java
See [JENKINS-48571](https://issues.jenkins-ci.org/browse/JENKINS-48571).
> JENKINS-48571# Create MBP SCMSource with Id

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractBlueRunSummary.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStylePipeline.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/TestProject.java
* JENKINS-48868# Dashboard page load performance fix
Cherry pick 
FYI @vivek I think @kshultzCB  wanted to give this a kick around though?
> 1.4: JENKINS-48868# Dashboard page load performance fix (#1635)

- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/ParallelNavigationTest/Jenkinsfile.nosteps.nostages
- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
- jenkins-design-language/less/components/alert.less
show full log in case of no steps and no stages for a failed run
See [JENKINS-48074](https://issues.jenkins-ci.org/browse/JENKINS-48074).
> JENKINS-48074 show full log in case of no steps and no stages for a failed run

- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEnterpriseCreationTest.java
- blueocean-dashboard/src/main/js/creation/github-enterprise/GHEAddServerDialog.jsx
JENKINS-47395 for github server pipeline creation if url is invalid try appending /api/v3 (#1624)
* for github server if url is invalid try appending /api/v3
* modified test so a GHE url is still invalid (this new feature made the old url valid)
See [JENKINS-47395](https://issues.jenkins-ci.org/browse/JENKINS-47395).
> 1.4 cherry pick: JENKINS-47395 for github server pipeline creation if url is invalid try appending /api/v3 (#1624)

- blueocean-events/src/test/java/io/jenkins/blueocean/events/SseEventTest.java
> Fix for flaky sse events tests

- README.md
See [JENKINS-47464](https://issues.jenkins-ci.org/browse/JENKINS-47464).
> Add prettier.js setup instructions to README

- acceptance-tests/src/test/java/io/blueocean/ath/offline/pipeline/DownstreamLinkTest.java
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/main/js/components/downstream-runs/DownstreamRuns.jsx
- blueocean-dashboard/src/main/js/components/downstream-runs/DownstreamRunsView.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
- blueocean-dashboard/src/main/js/components/karaoke/services/Augmenter.js
- blueocean-dashboard/src/main/js/components/stories/DownstreamRunsStories.js
- blueocean-dashboard/src/main/js/components/stories/index.js
- blueocean-dashboard/src/main/js/util/logDisplayHelper.js
- blueocean-dashboard/src/main/less/run-details-header.less
- blueocean-dashboard/src/main/less/tables.less
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
- blueocean-dashboard/src/test/js/components/DownstreamRuns-spec.js
- jenkins-design-language/src/js/components/jtable/JTable.jsx
See [JENKINS-38339](https://issues.jenkins-ci.org/browse/JENKINS-38339).
> Downstream job links UI

- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/ParallelNavigationTest/Jenkinsfile.input.param.classic.link
- blueocean-core-js/src/js/utils/UrlUtils.js
- blueocean-dashboard/src/main/js/components/karaoke/components/InputStep.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Step.jsx
This fixes the link to classic in the case of an invalid input param
See [JENKINS-45334](https://issues.jenkins-ci.org/browse/JENKINS-45334).
> JENKINS-45334 go to classic link missing in invalid input param

- blueocean-dashboard/src/main/js/components/karaoke/components/InputStep.jsx
this removes the duplicate code introduced in https://github.com/jenkinsci/blueocean-plugin/pull/1676
See [JENKINS-45334](https://issues.jenkins-ci.org/browse/JENKINS-45334).
> remove duplicate code introduced in fix for JENKINS-45334

- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/NavigationTest.java
- blueocean-core-js/src/js/paths/rest.js
- blueocean-core-js/src/js/services/ActivityService.js
- blueocean-core-js/src/js/utils/jenkins-encode.js
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
See [JENKINS-48027](https://issues.jenkins-ci.org/browse/JENKINS-48027).
> [JENKINS-48027] Properly encode branch names

- acceptance-tests/src/main/java/io/blueocean/ath/AthModule.java
- acceptance-tests/src/main/java/io/blueocean/ath/GitRepositoryRule.java
- acceptance-tests/src/main/java/io/blueocean/ath/factory/RunDetailsTestsPageFactory.java
- acceptance-tests/src/main/java/io/blueocean/ath/model/AbstractPipeline.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/RunDetailsTestsPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/TestDetailsTest.java
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/edgeCases/TestDetailsTest/Jenkinsfile
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/edgeCases/TestDetailsTest/TEST-failure.TestThisWillFailAbunch.xml
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/edgeCases/TestDetailsTest/TEST-failure.TestThisWontFail.xml
- blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
- blueocean-dashboard/src/main/js/components/testing/TestService.js
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
- blueocean-dashboard/src/test/js/testResult-spec.js
See [JENKINS-43892](https://issues.jenkins-ci.org/browse/JENKINS-43892).
> [JENKINS-43892] Show passing tests

- jenkins-design-language/src/js/components/jtable/JTable.jsx
See [JENKINS-49702](https://issues.jenkins-ci.org/browse/JENKINS-49702).
remove columns from props
> [FIX-JENKINS-49702] JTable produces a console warning

- acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesCardsTest.java
- blueocean-dashboard/src/main/js/components/BranchDetailsRow.jsx
- blueocean-dashboard/src/main/js/components/PullRequestRow.jsx
- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- blueocean-personalization/src/main/less/pipeline-card.less
- jenkins-design-language/less/components/jtable.less
- jenkins-design-language/less/theme.less
See [JENKINS-45634](https://issues.jenkins-ci.org/browse/JENKINS-45634).
> JENKINS-45634 Table action buttons hidden until hover

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/stepsFromPost.jenkinsfile
See [JENKINS-49297](https://issues.jenkins-ci.org/browse/JENKINS-49297).
> JENKINS-49297# Capture missing input steps from post declarative block

- blueocean-rest/README.md
> Fix JWT documentation

- blueocean-core-js/src/js/UrlBuilder.js
- blueocean-core-js/src/js/utils/UrlUtils.js
- blueocean-dashboard/src/main/js/components/downstream-runs/DownstreamRunsView.jsx
- blueocean-dashboard/src/main/js/util/UrlUtils.js
Fix the issue with downstream build URL generation, and add some snarky FIXMEs which I will address in a seperate PR
See [JENKINS-50406](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
> JENKINS-50406 "Triggered Build" links broken with cloudbees-folder

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeUtil.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/parallelStepsFromPost.jenkinsfile
See [JENKINS-48884](https://issues.jenkins-ci.org/browse/JENKINS-48884).
> JENKINS-48884 Fix parallel stages not rendering properly if skipped by failed previous stage

- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveService.java
See [JENKINS-50487](https://issues.jenkins-ci.org/browse/JENKINS-50487).
> JENKINS-50487# Fix for java.util.NoSuchElementException error

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
See [JENKINS-50452](https://issues.jenkins-ci.org/browse/JENKINS-50452).
> JENKINS-50452# Fix node graph visitor log levels

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Update to 1.6.0-beta-1-SNAPSHOT for next development cycle

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Change pom version from beta to 1.5.0-SNAPSHOT for release

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-material-icons/package.json
- blueocean-material-icons/src/js/components/SvgIcon/SvgIcon.js
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-pipeline-editor/npm-shrinkwrap.json
- blueocean-pipeline-editor/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- jenkins-design-language/npm-shrinkwrap.json
- jenkins-design-language/package.json
- jenkins-design-language/src/js/components/pipeline/PipelineGraph.jsx
[JENKINS-50325-spread] using spread instead to polyfill
See [JENKINS-50325](https://issues.jenkins-ci.org/browse/JENKINS-50325).
>  [JENKINS-50325] Some part of the code uses object.assign which needs to be polyfill to support IE11 

- blueocean-dashboard/src/main/less/forms/index.less
This change makes all the text in the InputStep component render respecting all space and '\n' chars
I don't think a test is suitable for this change
See [JENKINS-45251](https://issues.jenkins-ci.org/browse/JENKINS-45251).
> JENKINS-45251 make all text in an input step format according to new lines chars

- blueocean-core-js/package.json
> Add types field to core-js package.json

- blueocean-dashboard/src/main/js/creation/github/steps/GithubCredentialStep.jsx
- blueocean-dashboard/src/main/js/credentials/github/GithubCredentialsPicker.jsx
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
Updates a few pieces of text shown during pipeline creation. To test, verify the text changes on the create pipeline page.
> Update text on create pipeline page

- blueocean-pipeline-api-impl/pom.xml
- blueocean-rest-impl/pom.xml
> fix duplicate dependencies 

- pom.xml
See [JENKINS-51206](https://issues.jenkins-ci.org/browse/JENKINS-51206) and [JENKINS-51387](https://issues.jenkins-ci.org/browse/JENKINS-51387).
> [JENKINS-51206] [JENKINS-51387] jira-plugin 3.0.0

- blueocean-dashboard/src/main/js/components/stories/moments.js
- jenkins-design-language/src/js/components/TimeDuration.jsx
- jenkins-design-language/test/js/components/TimeDuration-spec.jsx
remove title from timeDuration in order to reduce CPU usage
See [JENKINS-51161](https://issues.jenkins-ci.org/browse/JENKINS-51161).
> remove title from timeDuration in order to reduce CPU usage

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Upgrade pom version for 1.7.0 development

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/BlueUrlTokenizer.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/FavoritesStatePreloader.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/PipelineActivityStatePreloader.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/PipelineBranchRunStatePreloader.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/PipelineStatePreloader.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/RESTFetchPreloader.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/preload/BlueUrlTokenizerTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- pom.xml
See [JENKINS-51956](https://issues.jenkins-ci.org/browse/JENKINS-51956).
> [JENKINS-51956] upgrade to plugins parent 3.15

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunSearch.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/RunMultiThreadLoadTest.java
- blueocean-rest-impl/src/test/resources/io/jenkins/blueocean/service/embedded/rest/RunMultiThreadLoadTest.jenkinsfile
See [JENKINS-52101](https://issues.jenkins-ci.org/browse/JENKINS-52101.
> [JENKINS-52101] protect against possible IllegalArgumentException

- blueocean-dashboard/src/main/js/creation/credentials/CredentialsApi.js
- blueocean-dashboard/src/main/js/creation/credentials/CredentialsManager.js
- blueocean-dashboard/src/main/js/creation/git/GitFlowManager.jsx
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/CredentialApiTest.java
> Remote generation of user filesystem SSH key

- blueocean-dashboard/src/main/js/creation/credentials/CredentialsApi.js
- blueocean-dashboard/src/main/js/creation/credentials/CredentialsManager.js
- blueocean-dashboard/src/main/js/creation/git/GitFlowManager.jsx
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/CredentialApiTest.java
> PORT 1.5 -> 1.6: remove generation of user filesystem SSH key (#1759)

- blueocean-dashboard/src/main/js/creation/credentials/CredentialsApi.js
- blueocean-dashboard/src/main/js/creation/credentials/CredentialsManager.js
- blueocean-dashboard/src/main/js/creation/git/GitFlowManager.jsx
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/CredentialApiTest.java
> PORT 1.5 -> master -- remove generation of user filesystem SSH key (#1759)

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
See [JENKINS-52281](https://issues.jenkins-ci.org/browse/JENKINS-52281). Some occasional plugin-compat-tester flakiness has been observed from [PipelineNodeTest](https://github.com/jenkinsci/blueocean-plugin/blob/e7de3f1b8d766173854cd9b68da31b5626905f48/blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java). This PR is an attempt to help mitigate that. It:
- Removes calls to this deprecated constructor for [`CpsFlowDefinition`](https://github.com/jenkinsci/workflow-cps-plugin/blob/da9846447fa6a17b4fca63e39a31555e2e4d4a25/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java#L72)
- Fixes many of the sample Pipelines in use, so that they no longer use deprecated syntax. In its current form, there are many examples of …
> [JENKINS-52281] Un-deprecation of some constructor calls and pipeline code

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/JsonConverter.java
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/htmlpublisher/HTMLArtifact.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineQueueContainer.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/RestartStageTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/TEST-io.blueocean.NoErrorMessage.xml
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/TEST-io.blueocean.StdoutStderr.xml
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/restartStage.jenkinsfile
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueItemImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueUtil.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineNode.java
- pom.xml
See [JENKINS-52332](https://issues.jenkins-ci.org/browse/JENKINS-52332).
> [JENKINS-52332] Node Api enhancement restartable flag and restart command

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MatrixProjectImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/RestartStageTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
See [JENKINS-52307](https://issues.jenkins-ci.org/browse/JENKINS-52307).
> [JENKINS-52307] fix npe with empty matrix projects

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
Update to pom to remove beta release version string to prepare for release.
> Prepare 1.7.0 release branch for release

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
Prepare for 1.8.0 development.
> Prepare for 1.8.0 development

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/PipelineActivityStatePreloader.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/LinkResolverImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultibranchPipelineRunContainer.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/StageDurationTrend.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/LinkResolverImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/junit/BlueJUnitTrend.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
See [JENKINS-52307](https://issues.jenkins-ci.org/browse/JENKINS-52307).
> [JENKINS-52307] add more null check

- CODEOWNERS
This will ensure that I am automatically included in Blue Ocean PRs.
> Adding Jenn Briden (jennbriden) to code owners

- pom.xml
No related JIRA as this is a small change, and https://github.com/jenkinsci/plugin-pom/blob/master/CHANGELOG.md#changelog only references changes that should be limited to build time anyway.
~~- [ ] Link to JIRA ticket in description, if appropriate.~~
> Update to latest parent

- blueocean-events/src/main/java/io/jenkins/blueocean/events/PipelineEventListener.java
See [JENKINS-52862](https://issues.jenkins-ci.org/browse/JENKINS-52862).
> [JENKINS-52862] use a guava cache with weakkeys

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/sequentialParallel.jenkinsfile
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineNode.java
See [JENKINS-49779](https://issues.jenkins-ci.org/browse/JENKINS-49779).
> [JENKINS-49779] Feature/sequentiel add more tests

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/sequentialParallelWithPost.jenkinsfile
Related to [JENKINS-49779](https://issues.jenkins-ci.org/browse/JENKINS-49779) and [JENKINS-49050](https://issues.jenkins-ci.org/browse/JENKINS-49050)
Probably still needs a UI-side test?
> [JENKINS-49779] Verify sequential parent stage post steps end up in child stage

- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-editor/src/main/java/io/blueocean/rest/pipeline/editor/ExportedPipelineFunction.java
- blueocean-pipeline-editor/src/main/java/io/blueocean/rest/pipeline/editor/ExportedPipelineStep.java
- blueocean-pipeline-editor/src/main/java/io/blueocean/rest/pipeline/editor/PipelineMetadataService.java
- blueocean-pipeline-editor/src/test/java/io/blueocean/rest/pipeline/editor/PipelineMetadataServiceTest.java
- blueocean-pipeline-editor/src/test/js/StepMetadata.json
- blueocean-pipeline-editor/src/test/js/services/PipelineSyntaxConverter-spec.js
- pom.xml
See [JENKINS-50148](https://issues.jenkins-ci.org/browse/JENKINS-50148).
> [FIXED JENKINS-50148] Handle SimpleBuildWrappers in editor

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Prepare for 1.9 devlopment

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Prepare for 1.8 release

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
> correctly close ByteBuffer in try-with-resources clause

- Jenkinsfile
wasn't needed, and hipchat is going away...
> get rid of hipchat send

- Jenkinsfile
- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
- blueocean-dashboard/src/main/js/components/karaoke/services/pagers/PipelinePager.js
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
Backports  #1788, #1791, #1792.
> Cherry pick fixes to release 1.8

- pom.xml
https://jenkins.io/security/advisory/2018-03-26/#SECURITY-536
> upgrade jira plugin to 3.0.1 removing perforce plugin security advisory

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
> [JENKINS-53175] avoid 404 by returning an empty BlueTestSummary

- Jenkinsfile
- pom.xml
> Surefire and jacoco plugins upgrade

- pom.xml
See [JENKINS-53667](https://issues.jenkins-ci.org/browse/JENKINS-53667).
> JENKINS-53667: Update to sse-gateway-plugin 1.16

- pom.xml
No JIRA. Please just tell me if you need one for this kind of change too.
~~- [ ] Link to JIRA ticket in description, if appropriate.~~
~~- [ ] Change is code complete and matches issue description~~
~~- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests~~
~~- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.~~
> Update to latest 3.23 parent pom

- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScm.java
See [JENKINS-53697](https://issues.jenkins-ci.org/browse/JENKINS-53697).
init scmSource
> [JENKINS-53697] 

- blueocean-config/src/main/resources/io/jenkins/blueocean/config/RollbarDecorator/header.jelly
- blueocean-web/src/main/resources/io/jenkins/blueocean/PageStatePreloadDecorator/header.jelly
Update some Jelly files to align with upcoming Jenkins core changes.
> Update jelly escaping defaults

- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
Remove unused zombie dependency that was breaking my build
> Remove unused zombie dependency

- pom.xml
This fixes many nasty bugs. I would like to benefit from all the bugs fixed in this long list here: https://wiki.jenkins.io/display/JENKINS/Bitbucket+Branch+Source+Plugin#BitbucketBranchSourcePlugin-Version2.2.12(July5,2018)
I'm not sure I need to create a Jenkins-tracked issue here as this is just a patch version bump.
> Bump bitbucket branch source version to 2.2.12

- blueocean-config/src/main/resources/io/jenkins/blueocean/config/RollbarDecorator/header.jelly
- blueocean-web/src/main/resources/io/jenkins/blueocean/PageStatePreloadDecorator/header.jelly
> Update jelly escaping defaults - 1.5 (#1820)

- blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/BlueJiraIssue.java
- blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListener.java
- blueocean-jira/src/test/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListenerTest.java
See [JENKINS-53320](https://issues.jenkins-ci.org/browse/JENKINS-53320).
> cherrypick of fix for JENKINS-53320 into 1.8 branch

- blueocean-config/src/main/resources/io/jenkins/blueocean/config/RollbarDecorator/header.jelly
- blueocean-web/src/main/resources/io/jenkins/blueocean/PageStatePreloadDecorator/header.jelly
> Update jelly escaping defaults - master (#1820)

- blueocean-config/src/main/resources/io/jenkins/blueocean/config/RollbarDecorator/header.jelly
- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/htmlpublisher/HTMLArtifactTest.java
- blueocean-web/src/main/resources/io/jenkins/blueocean/PageStatePreloadDecorator/header.jelly
> Update jelly escaping defaults - 1.3 (#1820)

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Prepare for 1.9 release

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
> Prepare for 1.10 development

- acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- pom.xml
> Upgrade workflow log api

- pom.xml
> Jira plugin upgrade 3.0.3

- pom.xml
> Downgrade workflow-job to 2.25 till JENKINS-54073 is fixed

- blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListener.java
- pom.xml
See [JENKINS-54144](https://issues.jenkins-ci.org/browse/JENKINS-54144).
> [JENKINS-54144] Improve protection against issue with jira plugin

- CODEOWNERS
A changing of the guard. 
*sheds a single tear*. Pour one out.
> remove mic and add olivier

- .mvn/extensions.xml
- .mvn/maven.config
- Jenkinsfile
- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-core-js/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- jenkins-design-language/pom.xml
- pom.xml
This will allow generating and consume incremental releases for Blue Ocean in Evergreen if needed.
```
mvn incrementals:incrementalify
```
Cf. https://jenkins.io/blog/2018/05/15/incremental-deployment/ and
https://github.com/jenkinsci/jep/tree/master/jep/305 to dig into this more.
Relates to https://issues.jenkins-ci.org/browse/JENKINS-50686
~~- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.~~
> [JEP-305] Incrementalify Blue Ocean

- pom.xml
> pipeline plugin upgrade

- blueocean-dashboard/src/main/js/creation/ScmProvider.js
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages_zh.properties
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmSaveFileRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerContainer.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
- licenses/octicons-license.txt
> spelling: GitHub

- pom.xml
> jira plugin 3.0.5

- pom.xml
No JIRA created for this. Please do not hesitate to request it if your process prefers this.
> Bump to latest 3.28 parent pom

- pom.xml
> Upgrade bitbucket-branch-source to 2.2.15

- pom.xml
> Prepare for 1.10.0 release

- pom.xml
Reverts jenkinsci/blueocean-plugin#1893
> Revert "Prepare for 1.10.0 release"

- acceptance-tests/src/main/js/page_objects/blueocean/bluePipelineActivity.js
- acceptance-tests/src/main/js/page_objects/blueocean/bluePipelineRunDetail.js
- acceptance-tests/src/test/js/failing.js
- acceptance-tests/src/test/js/failingStages.js
- acceptance-tests/src/test/js/log-karaoke/stages-block.js
- acceptance-tests/src/test/js/log-karaoke/stages-new.js
- acceptance-tests/src/test/js/log-karaoke/stages-old.js
- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
parallel seq stages don't have the isParallel flag set so we need to
check the "firstParent" vs "parent" properties
See [JENKINS-55127](https://issues.jenkins-ci.org/browse/JENKINS-55127).
> [JENKINS-55127] make parallel input stages individually selectable

- pom.xml
> upgrade version for development

- release/Jenkinsfile
> Updated Jenkinsfile to match the one used on release instance

- pom.xml
My goal is to propagate [JENKINS-54099](https://issues.jenkins-ci.org/browse/JENKINS-54099) that was fixed in https://github.com/jenkinsci/sse-gateway-plugin/pull/28 (which was in turn approved by @kzantow and @michaelneale, and merged by @scherler).
Diff between current 1.16 and 1.17: https://github.com/jenkinsci/sse-gateway-plugin/compare/sse-gateway-1.16...sse-gateway-1.17
cc @davidbees @halkeye who recently got also release permissions. Thanks!
> Bump to sse-gateway:1.17

- acceptance-tests/src/main/java/io/blueocean/ath/sse/SSEClientRule.java
Pull in updated SSE Client rule that supports later Jenkins versions.
> Update SSE client lib used in ATH

- blueocean-web/src/main/resources/jenkins/plugins/blueocean/web/Messages.properties
See [JENKINS-47286](https://issues.jenkins-ci.org/browse/JENKINS-47286).
> [JENKINS-47286] Adding translation for common.state.skipped

- pom.xml
bitbucket-branchsource 2.4.0 is updated with jsch:0.1.55 that includes fix for security vulnerabilities.
See [SECURITY-1278](https://issues.jenkins-ci.org/browse/SECURITY-1278).
> [SECURITY-1278] Update version of bitbucket-branchsource

- acceptance-tests/src/main/java/io/blueocean/ath/sse/SSEClientRule.java
- blueocean-dashboard/src/main/js/components/StageRestartLink.tsx
- blueocean-dashboard/src/test/js/data/pipelines/pipelinesSingle.js
- blueocean-dashboard/src/test/js/stageRestart-spec.js
Hides the "Restart Stage" link in case start permissions are not granted
See [JENKINS-55986](https://issues.jenkins-ci.org/browse/JENKINS-55986).
> [JENKINS-55986] Don't show the "Restart Stage" link if permissions do not allow it

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/Caches.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/CachesTest.java
Add support for pulling branch name from the SCM source, at least until all scm source implement object metadata
See [JENKINS-54518](https://issues.jenkins-ci.org/browse/JENKINS-54518).
> JENKINS-54518 - Support SCM Systems that don't implement ObjectMetadataAction

- pom.xml
> [NO-TICKET] Remove minimum java 11 from plugin. BO works fine in 8+

- blueocean-core-js/src/js/bundleStartup.js
Doesn't seem to break or fix anything either way, but I'm sure it does.
Chrome network tab has 404s
ATH Console output has
```
02:34:05 INFO  - 1550889239589 - SEVERE - http://172.17.0.2:53229/adjuncts/f8471b88/io/jenkins/blueocean/blueocean.js 58135:12 "Unhandled Rejection: \"Error: fetch failed: 404 for http://172.17.0.2:53229/blue/rest/classes/io.jenkins.blueocean.rest.impl.pipeline.MultiBranchPipelineImpl/\\n    at FetchFunctions.checkStatus (http://172.17.0.2:53229/adjuncts/f8471b88/io/jenkins/blueocean/blueocean-core-js.js:54655:25)\""
```
Figured this was a nice cleanup.
> Fix for random 404s on startup / ATH

- CODEOWNERS
Update Codeowners to match the current list of developers.
> Add most of the developers to the codeowners list

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImplTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/singleScm.jenkinsfile
See [JENKINS-55497](https://issues.jenkins-ci.org/browse/JENKINS-55497).
> PipelineRunSummary should include a change set

- acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
- blueocean-executor-info/.babelrc
- blueocean-executor-info/package-lock.json
- blueocean-executor-info/package.json
One of the recent merges seemed to have deleted a bunch of files in the executor plugin.
This PR just adds them back in.
> Fix executor plugin

- Jenkinsfile
- acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
- acceptance-tests/src/main/java/io/blueocean/ath/WaitUtil.java
- acceptance-tests/src/main/java/io/blueocean/ath/api/classic/ClassicJobApi.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/ActivityPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/FavoritesDashboardPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GithubCreationPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/RunDetailsPipelinePage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/dashboard/search/SearchTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/FolderTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/CommitMessagesTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesCardsTest.java
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/personalization/FavoritesCardsTest/Jenkinsfile
- blueocean-executor-info/.babelrc
- blueocean-executor-info/package-lock.json
- blueocean-executor-info/package.json
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImplTest.java
Trying to fix some tests that keep failing on CI
> Fix ATH flaky tests

- Jenkinsfile
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/ServiceException.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/JsonBody.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Model.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Property.java
- pom.xml
lets see if this works,
copied sorta from @batmat's https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/99
> Try out the new java11 fancyness for builds

- blueocean-dashboard/src/main/js/components/RunDetailsArtifacts.jsx
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
See [JENKINS-56672](https://issues.jenkins-ci.org/browse/JENKINS-56672).
> JENKINS-56672 - Add a link to display artifact in new window

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImplTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetContainerImpl.java
See [JENKINS-57200](https://issues.jenkins-ci.org/browse/JENKINS-57200).
> JENKINS-57200 - Exit out early if replay's run isn't available so we dont infinitely loop

- .github/release-drafter.yml
Downstream of https://github.com/jenkinsci/.github/pull/1 . Uses the standard Release Drafter configuration, except some project-specific overrides.
> Release Drafter: Inherit settings from Global configuration

- pom.xml
See [JENKINS-51057](https://issues.jenkins-ci.org/browse/JENKINS-51057).
> [JENKINS-51057] Use see-gateway plugin 1.18

- pom.xml
> Prepare for next development version

- pom.xml
Project URL changed to use Github.
> Hacktoberfest - Project URL updated to use Github instead of Wiki

- pom.xml
merge back this from release branch 1.22.0
> RequireUpperBoundDeps jodatime

- pom.xml
> release bump 1.23.0

- pom.xml
Upgrade sse-gateway 1.21 to fix issue for Windows/Edge
See [JENKINS-59291](https://issues.jenkins-ci.org/browse/JJENKINS-59291).
> [JENKINS-59291] upgrade to sse-gateway 1.21

- acceptance-tests/pom.xml
- acceptance-tests/runner/runtime-plugins/fake-security-realm-plugin/pom.xml
- acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
- acceptance-tests/runner/runtime/pom.xml
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudApi.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerContainer.java
- blueocean-jira/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/AbstractAnalytics.java
- jenkins-design-language/pom.xml
- pom.xml
> Upgrade Jira plugin to 3.0.14

- acceptance-tests/run.sh
- acceptance-tests/runner/scripts/download.sh
Fixes extremely slow jenkins-war download.
> Move jenkins-war downloading to use maven instead of raw curl

- Jenkinsfile
- pom.xml
> Upgrade to pom-4.1

- blueocean-jwt/README.md
- blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/JwtAuthenticationService.java
- blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/JwtSigningKeyProvider.java
- blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/SigningPublicKey.java
- blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/JwtAuthenticationServiceImpl.java
- blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/SigningKeyProviderImpl.java
- blueocean-jwt/src/test/java/io/jenkins/blueocean/auth/jwt/impl/JwtAuthenticationServiceImplTest.java
See [JENKINS-62666](https://issues.jenkins-ci.org/browse/JENKINS-62666).
Many thanks to @lenaing with whom I coded this
> [JENKINS-62666] Adding a /jwt-auth/jwks endpoint that follows the RFC7517

- .mvn/extensions.xml
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- pom.xml
Trying to use https://github.com/jenkinsci/incrementals-tools/pull/16 so that PCT can work on #2084.
> [JENKINS-58716] Allow gitHubRepo to be overridden

- pom.xml
PCT compat w/ https://github.com/jenkinsci/jenkins/pull/4944.
> Update parent & use recommended jenkins-test-harness

- blueocean/pom.xml
> Make executor plugin optional

- pom.xml
> upgrade sse-gateway plugin to 1.24

- pom.xml
> Upgrade commons-codec to 1.15

- pom.xml
> use slf4j 1.7.30

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/guice/Slf4jTypeListener.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/Export.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/TreeResponse.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/JSONDataWriter.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Model.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ModelBuilder.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/NamedPathPruner.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Property.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/TypeUtil.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/XMLDataWriter.java
- blueocean-commons/src/test/java/io/jenkins/blueocean/commons/stapler/export/RangeTest.java
Minor refactoring in commons:
* diamond operator
* Replaced deprecated Jenkins.getInstance() with get() call
* removed superflous semicolons
* use `Objects.equals()` where applicable
If this is useful at all, I would add some other PRs for other parts of this plugin?!
> Minor refactoring in blueocean-commons

- pom.xml
> Bump parent version 4.16, bom version 25

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
- blueocean-jira/pom.xml
- blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/BlueJiraIssue.java
* Do not bundle `commons-codec` (again).
* Do not use maven apis that will blow up a scanner at some point when maven has an API.
* Do not bundle `guava`
This has has no testing performed (not even running unit tests - because I am on windows and building it is not a possibility in a reasonable time frame)
@olamy
> Fix incorrect bundling

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScmContentProvider.java
> get rid of commons-codec usage

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
See [JENKINS-65593](https://issues.jenkins-ci.org/browse/JENKINS-65593).
It fixes a test failure for Jenkins over or equal to 2.281.
I can't request reviewers. Pinging people:
- @car-roll 
- @olamy 
- @dwnusbaum 
- @joseblas
> [JENKINS-65593] Fix test error for Jenkins >= 2.281

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
Current master branch is failing. I think casting should fix the error.
> Fixed build with: cast to string

- pom.xml
> blueocean-maven-plugin 0.0.3

- blueocean-pipeline-api-impl/pom.xml
Removed duplicate dependency (already present in parent pom).
> Removed duplicate dependency (already present in parent pom)

- .github/workflows/maven.yml
> use setup-java cache

- Jenkinsfile
> use already built image

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudApi.java
- blueocean-bitbucket-pipeline/src/test/resources/api/cloud/mappings/mapping-2.0-teams-49APQ.json
> [JENKINS-68065] fix Bitbucket cloud job creation via wizard

- blueocean-core-js/README.md
Rather than "master" use "main"
!-- Please describe your pull request here. -->
~Ensure you have provided tests - that demonstrate the feature works or fixes the issue~
> Make a comment more inclusive

- blueocean-core-js/README.md
Reverts jenkinsci/blueocean-plugin#2282
> Revert "Make a comment more inclusive"

- acceptance-tests/pom.xml
- acceptance-tests/run.sh
- acceptance-tests/runner/runtime/src/test/java/io/jenkins/blueocean/AllTest.java
- acceptance-tests/runner/scripts/maven.sh
> fix missing dependency for ATH tests and simplify using -ntp option

- blueocean/pom.xml
Beginning to remove the optional dependencies from the blue ocean aggregator.
> remove blueocean-jira from aggregator

- blueocean/pom.xml
> remove blueocean-autofavorite from aggregator

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunSearch.java
I noticed while working on #2385 that I would sometimes get a failure
```
org.junit.ComparisonFailure: expected:<[2]> but was:<[1]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at io.jenkins.blueocean.rest.impl.pipeline.PipelineBaseTest.validateRun(PipelineBaseTest.java:335)
at io.jenkins.blueocean.rest.impl.pipeline.PipelineBaseTest.validateRun(PipelineBaseTest.java:331)
at io.jenkins.blueocean.rest.impl.pipeline.MultiBranchTest.getMultiBranchPipelineRuns(MultiBranchTest.java:408)
```
where the test expects to get a REST response with `p/master#2` followed by `p/master#1` but in fact gets the reverse. I was able to trace this to a regression introduced by @olamy in #1744: the `RunList` / `RunMap` serves builds in reverse order but …
> `RunSearch.collectRunsParallel` returned nondeterministic order

- acceptance-tests/pom.xml
- acceptance-tests/src/main/java/io/blueocean/ath/pages/classic/LoginPage.java
- ath need xml bind
- fix xpath because of core upgrade, Log -> Sign
> fix some ATH 

- blueocean-jira/src/main/resources/index.jelly
Trivial typo - skipping paperwork.
> Fix typo in description

- blueocean-jwt/src/test/java/io/jenkins/blueocean/auth/jwt/impl/JwtAuthenticationServiceImplTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/TryBlueOceanMenuTest.java
- pom.xml
Closes #2441
Tested locally with `mvn clean verify` on Java 11.
> Adapt to HtmlUnit migration

- Jenkinsfile
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlActionTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/ArtifactImplTest.java
- pom.xml
As the ecosystem moves closer toward Java 17, it is appropriate to run the tests on Java 17 by default.
> Test with Java 17

- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtilsTest.java
> Disable signing when test commit with jgit

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlObjectImpl.java
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages.properties
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_ko.properties
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_ru.properties
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_zh_CN.properties
This reverts commit 141210595871aeed971be729cb1fc1bb77f799b6.
> Revert "Allow the user to tell the difference between a helpful open button and a generic one (#2442)"

- blueocean-rest-impl/pom.xml
- pom.xml
Also remove any dependency management entries that are no longer needed.
> Update plugin BOM

- pom.xml
> no need to declare javadoc plugin just inherit that

- acceptance-tests/pom.xml
- acceptance-tests/runner/runtime/pom.xml
> Upgrade surefire 3.1.2

- blueocean-git-pipeline/pom.xml
Bump org.eclipse.jgit : org.eclipse.jgit.ssh.jsch from 6.6.0.202305301015-r to 6.6.1.202309021850-r
> Bump org.eclipse.jgit from 6.6.0.202305301015-r to 6.6.1.202309021850-r

- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveTest.java
- Updates testing code to make it able to be tested on an IPv6 environment
> Adapt to run test on IPv6

- Jenkinsfile
- blueocean-bitbucket-pipeline/pom.xml
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScm.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerEndpoint.java
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-branches-default-C98AD.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-browse-README-head-master.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-empty-repo-branches-default-head.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-redirect-test.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-repos-pipeline-demo-test-PcCw8-1.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server_wrong_version/mappings/bitbucket_rest_api_10_projects_testp_repos_pipeline-demo-test_browse_somefile-7269cd83-1af6-4134-9161-82360d678dcc.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server_wrong_version/mappings/mapping-1.0-application-properties-q4jwO.json
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScm.java
- blueocean-github-pipeline/pom.xml
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/scm/AbstractScm.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/RunImplTest.java
- blueocean-rest-impl/pom.xml
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/pageable/PagedResponse.java
- pom.xml
Preparing to migrate this plugin to EE 9 by updating the core baseline and modernizing the plugin Java build.
> Require Jenkins 2.479.3 or newer and Java 17 or newer

- blueocean-web/package-lock.json
- blueocean-web/package.json
- blueocean-web/src/main/js/ErrorUtils.js
- blueocean-web/src/main/js/blueocean.js
- blueocean-web/src/main/js/components/BackendConnectFailure.jsx
- blueocean-web/src/main/js/components/ToastDrawer.jsx
- blueocean-web/src/main/js/main.jsx
This PR removes unused variables (`PropTypes`,`closeHandler`,`ErrorUtils`,`Link`) and resolves `no-unused-vars` warnings.  
Additionally, it replaces `console.log()` with `log.error()` where necessary to follow project conventions.  
✅ Lint check passed  
✅ No functionality is affected  
Please review and let me know if any changes are needed.  
Thanks! 🚀
> Fix: Removed unused variables and resolved ESLint warnings

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScm.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScmContentProvider.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketPipelineCreateRequest.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketPipelineCreateRequestTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/RunImplTest.java
- pom.xml
This PR would prepare the blueocean-bitbucket-pipeline to the changes done in bitbucket-source-branch-plugin 936.0.1
> Prepare the blueocean-bitbucket-pipeline to the changes in bitbucket-source-branch-plugin version 936.0.1

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/Export.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/NodeLogResource.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
Replace usages of deprecated functionality with non-deprecated equivalents.
> Remove usages of deprecated Stapler method

- Dockerfile.build
> docker: bump java from 11 to 21
