- blueocean-dashboard/src/main/js/PipelineRoutes.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
When opening the pipeline details view (modal window) and then navigating between tabs and finally dismissing the window, the afterClose navigation url is not correct, and is showing an empty page.
First part of the fix is at routing, so that we can define fallback redirect (pipelines/activity) and then we have to be aware that opener url (previous) is passed from context when component is initialised and should not be set from render method, which is of course called every time we switch between tabs.
@reviewbybees
> Fixing afterClose navigation on Pipeline detail view (modal window)

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
.
.
.
@reviewbybees 
This header was added but after call to ServletResponse.getWriter(). Servlet
spec doesn't talk about it explicitly but certain servlet container implementation
commits the response such that headers added after call to ServletResponse.getWriter()
are ignored. Fix was to move this code before call to ServletResponse.getWriter().
> UX-504# Log response has missing X-Text-Size header

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/util/FavoriteUtil.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineFolder.java
.
.
.
@reviewbybees 
- Folder contains other pipelines and folder and other buildable items
- Nested folder or pipeline can be accessed using recursive REST path
- Access p1 pipeline nested inside a folder:
/organizations/jenkins/pipelines/folder1/pipelines/folder2/pipelines/p1
- Folder vs pipeline detection to happen with data extensibility/capability work
> UX-196# API for walking folder tree

- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-dashboard/src/test/js/branches-spec.js
- blueocean-dashboard/src/test/js/pullRequest-spec.js
Related to issue # UX-297. 
* use TimeDuration
* remove moment/duration usages
* ~~fix a test regression in recent update to CommitHash~~
> feature/ux 297: use TimeDuration component in dashboard

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
@michaelneale previous log fix caused this regression where default behavior changed to serve text/html logs. To prevent future regression a test to check text/plain being default type is added.
@reviewbybees
> UX-553# In case accept header is */* or text/*, defaults to text/plain.

- blueocean-dashboard/package.json
- blueocean-web/package.json
- blueocean-web/src/main/js/init.jsx
- js-extensions/@jenkins-cd/subs/extensions-bundle.js
- js-extensions/package.json
Related to issue [UX-431](https://cloudbees.atlassian.net/browse/UX-431). 
Externalizes some of the NPM packages used in the web and dashboard  plugins.
I had to make a bugfix to js-builder and so also included a possible fix for [JENKINS-35180](https://issues.jenkins-ci.org/browse/JENKINS-35180)
@reviewbybees
> [UX-431] Externalize some packages

- blueocean-web/gulpfile.js
- blueocean-web/package.json
- blueocean-web/src/main/java/io/jenkins/blueocean/TryBlueOceanPageDecorator.java
- blueocean-web/src/main/js/try.js
- blueocean-web/src/main/less/try.less
- blueocean-web/src/main/less/variables.less
- blueocean-web/src/main/resources/io/jenkins/blueocean/TryBlueOceanPageDecorator/header.jelly
Related to issue [UX-561](https://cloudbees.atlassian.net/browse/UX-561). 
A button on the classic Jenkins top nav bar (on every page), helping new users to get to blue ocean (vs having to type in the URL) + a constant reminder to existing users to go back to Blue Ocean.
I think I'd like to make the button contextual i.e. depending on where you are in Jenkins, clicking on the button will bring you to the most appropriate place in Blue Ocean e.g. if you're in a Job, clicking on it brings you to that job in Blue Ocean etc ... on the page for a specific job run ... go to the run details page etc etc.
> [UX-561] Add a "Try Blue Ocean UI" button in classic Jenkins

- blueocean-dashboard/.eslintrc
- blueocean-dashboard/src/main/js/PipelineRoutes.jsx
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
Related to issue # UX-512. 
* wire up all instances of "orgName / pipelineName" to link to the appropriate URL
* fix a bug when closing modal related to URL refactor in UX-310
NOTE: need to merge jenkinsci/jenkins-design-language#42 and publish new JDL before merging this
NOTE: acceptance tests may need update before merge
@reviewbybees
> Feature/ux 512 - linkify header elements for dashboard, org name, pipeline name

- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/OrganizationPipelines.jsx
- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/PullRequest.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-web/package.json
Related to issue # JENKINS-35690 . 
* Fix a bug where the Activity view was using an incorrect value for the estimation run duration
* Add store logic for the Branches and PR tabs to update as jobs start/stop
@reviewbybees
> feature/jenkins 35690 - adding live indicator for job start/stop on Branches and PR's; fix estimated duration for Activity

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineNodeGraphBuilder.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineNodeTest.java
.
.
.
@reviewbybees 
State of a pipeline node is determined by looking at EndNode. In case of
parallel, if steps are running/not completed yet the reported status should be
UNKNOWN/RUNNING.
> JENKINS-35999# Fixed computation of parallel step if its running

- blueocean-dashboard/src/main/js/components/MultiBranch.jsx
- blueocean-dashboard/src/main/js/components/PullRequests.jsx
Related to issue # JENKINS-35994. 
* Branches and Pull Requests tabs now check the pipeline to see if branch names are available. If not, it immediately renders an empty state message and suppresses any REST API calls that would otherwise produce 404.
@reviewbybees
> feature/JENKINS-35994 - freestyle missing empty states

- blueocean-dashboard/src/main/js/components/LogToolbar.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
**----
NOTE: Cannot be merged until jenkinsci/blueocean-plugin#56 is merged, published and our package.json files are updated
----**
Related to issue # JENKINS-35912. 
* Simple change to pass result or state down to header
@reviewbybees
> [JENKINS-35912] use either the result or state for the header status

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/util/UrlUtils.js
- blueocean-dashboard/src/test/js/UrlUtils-spec.js
Related to issue # JENKINS-36000. 
* Fix broken tab links that were broken with branch names that included special chars
* Fix a regression from a prior commit
@reviewbybees
> bug/jenkins 36000 - tab links need escaping

- blueocean-dashboard/src/main/js/components/LogToolbar.jsx
Related to issue # . JENKINS-36064
.
.use start param to show full log
.
@reviewbybees
> [feature/JENKINS-36064] use start param to show full log

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
Related to issue # JENKINS-36074. 
The change to `getCommitId()` resolves a null pointer exception for an
edge case where a job with an SCM configuration was run, but the run
failed because the SCM configuration was faulty (bad URL, unable to
connect to private repo, etc)
The change to `getActions()` is unrelated to JENKINS-36074, but I needed
to fix that after pulling the latest changes in order to see the
`getCommitId()` fix working. I do not understand why an action would be
`null`; this behavior seems to have been introduced in the past few days,
as it did not occur when I originally fixed `getCommitId()` a few days ago
@reviewbybees
> Fixes JENKINS-36074

- blueocean-web/src/main/js/DevelopmentFooter.jsx
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
Related to issue #JENKINS-36100. 
. Add a fallback for DevelopmentFooter, when the json file can't be found
@reviewbybees
> [FIXED JENKINS-36100] - fallback for DevelopmentFooter version string

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BranchContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BranchImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/MultiBranchTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueMultiBranchPipeline.java
.
.
.
@reviewbybees 
Fixes:
- Link generation of multi branch project nested inside a folder
- BlueMultiBranchPipeline is a BluePipelineFolder now
- branches are reachable via /pipelines/:id/branches/:id or /pipelines/:id/pipelines/:id.
This makes it consistent with generic folder as multibranch project is really a folder.
> JENKINS-36278# Fixed Link generation of Multibranch project

- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BranchImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineSearch.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/Query.java
> Bug/jenkins 36273 pipeline search api organization support 

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineNodeGraphBuilder.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineStepImpl.java
> [JENKINS-36514] durationInMillis can be null so use Long instead of long

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FavoriteContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FavoriteImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/util/FavoriteUtil.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/MultiBranchTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueFavorite.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueFavoriteAction.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueFavoriteContainer.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- /users/:id/favorites/ response format change. It inlines favorite item. If the item is a branch branch object gets serialized
- For MBP if master branch is not found returns 400 instead of 500
- Nested MBP project not fixed yet, see https://issues.jenkins-ci.org/browse/JENKINS-36488.
@imeredith Please review
@cliffmeyers I think I have taken care of all you need for this enhancement, please review.
@reviewbybees
> JENKINS-36506# Favorite API improvement: inlined favorite items.

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
**Decription**
https://issues.jenkins-ci.org/browse/JENKINS-36639
[hotfix/JENKINS-36211] Bind onScroll and handleKeys to this -> current master throws an exception 
The  "Scrolling down to the bottom of actively tailing log should reactivate karaoke" had not been implement but I can do that when working on the "jump around" issue
@reviewbybees
> [hotfix/JENKINS-36211] Bind onScroll and handleKeys to this

- blueocean-rest-impl/pom.xml
This is needed as the scm api required by branch source is newer (we think...)
by @vivek & me
@reviewbybees
> this is needed to work with a fresh workspace

- blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
- blueocean-dashboard/src/main/less/testing.less
- blueocean-dashboard/src/test/js/testResult-spec.js
Related to issue #JENKINS-36302. 
. Add test total display to test results page
@reviewbybees
> [FIXED JENKINS-36302] - show test totals in blue ocean

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
**Decription**
* Fix the bug by encoding the project name correctly in the fallbackUrl
* I invested several hours into trying to write a unit test for this scenario. The idea was to expose a property "navigateToLocation:func" on RunDetails that would be called with the correct URL, then use sinon.spy to spy on it and assert that the URL was correct. Unfortunately this won't work because the callback is only invoked after the modal closes, which is requires some React state transitions to fire off first. The test execution won't wait, so it just shows the callback as not having been invoked. Maybe there's a way to delay it but I'm at a loss. I will push up a feature branch of the testing work so we have it for later in case someone else wants to take a look. Adding this bug to …
> bug/jenkins-36619 - close modal 404

- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-web/package.json
* Bug was originally fixed in a5709c3. Last publisher forgot to "npm install" before publish, so files went missing.
* Added validation to gulp build in lieu of a test:  jenkinsci/jenkins-design-language/pull/79
* Load up app and validate that 404 for octicons does not appear
@reviewbybees
> [JENKINS-36701] - tick JDL to get new version

- blueocean-dashboard/package.json
- pom.xml
See [JENKINS-36704](https://issues.jenkins-ci.org/browse/JENKINS-36704) and [JENKINS-36763](https://issues.jenkins-ci.org/browse/JENKINS-36763).
Depends on https://github.com/jenkinsci/sse-gateway-plugin/pull/5
This pulls in a new version of the SSE Gateway NPM package (above PR). This new version has:
1. [JENKINS-36704](https://issues.jenkins-ci.org/browse/JENKINS-36704): Client-side logging around SSE activity that will hopefully make it easier to debug problems that are perceived to be related to SSE. There's no real automated/unit tests that can be reasonably done to automate testing of this (I say "reasonably" because there's prob some convoluted/unreasonable way of testing logging).
1. [JENKINS-36763](https://issues.jenkins-ci.org/browse/JENKINS-36763): A fix to the …
> [FIX JENKINS-36704] New sse-gateway NPM package version - SSE diag logging

- blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
Related to issue # JENKINS-36336 - show list of fixed tests. 
. Add block of fixed tests in test results
(Note: other changes to this screen are handled by https://github.com/jenkinsci/blueocean-plugin/pull/337 and https://github.com/jenkinsci/blueocean-plugin/pull/334)
@reviewbybees
> [FIXED JENKINS-36336] - show list of fixed tests

- blueocean-dashboard/src/main/js/Dashboard.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-web/src/main/js/config.js
- blueocean-web/src/main/js/main.jsx
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
**Decription**
Context path was not handled properly from Java, use typical Java handling: always begin things appended to it with a `/`. I can't test this properly without an ATH test...
To test: verify the app works as expected (including sse) under root context and `/jenkins` context.
@reviewbybees
> JENKINS-36829 - fix context path passed to blue ocean - don't end with /

- blueocean-web/src/main/java/io/jenkins/blueocean/BlueOceanUI.java
- blueocean-web/src/main/js/DevelopmentFooter.jsx
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
**Decription**
Check the footer of dashboard, should show commitId instead of version
@reviewbybees 
BlueOceanUI is a bootstrap and core infrastructure class, we do want to
keep it fiarly abstract and indepedent of direct Jenkins dependency.
Rollbar or any such analytics tool integration should be done out of blueocean-web
possibly inside a separate plugin or some place else that makes sense.
Footer version to display the commitId/branch
> JENKINS-36481# Rollbar and it.pluginVersion() removed

- blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
- blueocean-dashboard/src/main/less/testing.less
**Decription**
"Erroneous" message about missing keys on the test reporting page due to use of an array. Unsure how to test for react warning messages to console, don't think it's necessary. To test: go to test report page with some failures, validate there are no react warning messages in the browser console log.
@reviewbybees esp. @cliffmeyers
> [FIXED JENKINS-36712] Get rid of React warning about duplicate/missing keys on test page

- blueocean-dashboard/src/main/js/components/LogConsole.jsx
- blueocean-dashboard/src/main/js/components/LogToolbar.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/main/js/components/Step.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-dashboard/src/main/js/util/UrlUtils.js
- blueocean-dashboard/src/main/less/core.less
- blueocean-dashboard/src/main/less/variables.less
**Decription**
AT: https://github.com/jenkinsci/blueocean-acceptance-test/pull/21
@reviewbybees
> Jenkins 36131 "Show all" link required anywhere a log is displayed

- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- blueocean-personalization/src/test/js/components/PipelineCard-spec.jsx
* Simple logic to escape the branch name
* Favorite a branch with a git-flow style name, e.g. "feature/JENKINS-123", then return to dashboard and ensure the branch name is properly displayed.
* Added a unit test
@reviewbybees
> [JENKINS-37020] fix bug where branch name was not decoded

- pom.xml
Quick fix to allow ATH connect to SSE gateway. This was an ATH regression introduced by TomF (bad boy !!!) when adding store and forward.
This is a super trivial fix. I tested it with the ATH and it fixed the issues locally, so hoping it will fix the ATH CI job.
> Updated SSE Gateway to 1.7 to fix ATH

- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/PipelineRoutes.jsx
- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-personalization/package.json
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineQueueContainer.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueItemImpl.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueQueueItem.java
- blueocean-web/package.json
Adds an /activities endpoint to the backend so that queued items are returned in same call as runs. Those items are mapped into psuedo runs in actions.js.
See [JENKINS-36209](https://issues.jenkins-ci.org/browse/JENKINS-36209).
@vivek please review the backend changes
JDL changes are https://github.com/jenkinsci/jenkins-design-language/pull/85
> [JENKINS-36209] Queued activity items

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineImpl.java
Fixes 2 recent regressions with karoke mode and extra data in pipeline api.
See [JENKINS-37268](https://issues.jenkins-ci.org/browse/JENKINS-37268).
Gist of pipeline data https://gist.github.com/imeredith/05aa904a3a783ce729387ac46228168c
* `this` is now bound for _onSseEvent
* pipeline data now no longer inlines activies
> [JENKINS-37268] Fixed karoke + pipeline data bloat

- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-web/package.json
- js-extensions/@jenkins-cd/js-builder.js
- js-extensions/package.json
An attempt to address [JENKINS-37200](https://issues.jenkins-ci.org/browse/JENKINS-37200).
It definitely seems to work better on FF when we build everything with `NODE_ENV=production` (i.e. doesn't hang on my machine, but did hang before), but not totally convinced this is the only issue. Still, I think this is worth doing.
There are no unit tests for this and imo it doesn't make sense to create any. I did run the ATH, but it is failing. I do not think it is relating to these changes. Seems like karaoke mode is broken. Looking into that now.
... defaulting to "production" mode so as to disable react dev tools, which seems to grind Firefox to a crawl
> [JENKINS-37200] Set NODE_ENV via js-extensions js-builder plugin

- blueocean-dashboard/src/main/js/components/LogConsole.jsx
- blueocean-dashboard/src/main/js/components/Step.jsx
- blueocean-dashboard/src/main/less/core.less
Developer should see an indeterminate progress bar when the step is loading.
See [JENKINS-36771](https://issues.jenkins-ci.org/browse/JENKINS-36771).
Implemented behaviour is that the progressbar is visible while loading but the code block not.
See https://www.youtube.com/watch?v=LxwnlxcYTfw&feature=youtu.be for preview
> Jenkins 36771 Developer should see an indeterminate progress bar when the step is loading

- blueocean-dashboard/src/main/js/components/Step.jsx
- blueocean-dashboard/src/main/js/util/logDisplayHelper.js
Steps with no logs should not be expandable
See [JENKINS-36171](https://issues.jenkins-ci.org/browse/JENKINS-36171) especially the comment about steps that can have logs but do not have them. The PR covers those that do not provide the possibility to have logs (no more 404 for those logs urls)
TESTS: https://github.com/jenkinsci/blueocean-acceptance-test/pull/24
…not do not make the resultItem expandable.
> [JENKINS-36171] Steps with no logs should not be expandable

- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MatrixProjectImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
See https://issues.jenkins-ci.org/browse/JENKINS-37104
- Create a matrix project mp1 with two axis with two values each and run it, you should get total of 4 builds, one for each combination and there should be build for mp1 as well.
- Do curl -v http://localhost:8080/jenkins/blue/rest/search/?q=type:pipeline;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject to get list of pipelines, here we are asking not to inline MatrixProject children.
- The list of pipeline should have mp1 project with self href pointing to "/job/mp1/"
- curl -v http://localhost:8080/jenkins/blue/rest/classes/io.jenkins.blueocean.rest.impl.pipeline.MatrixProjectImpl/ should give list of capabilities that includes hudson.matrix.MatrixProject …
> JENKINS-37104# Matrix project handling

- blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
- blueocean-dashboard/src/main/less/core.less
Update changes tab style so message can span multiple lines
See [JENKINS-36772](https://issues.jenkins-ci.org/browse/JENKINS-36772).
AT would be way to much effort for this.
> [JENKINS-36772] Update changes tab style so message can span multiple lines

- blueocean-config/package.json
- blueocean-dashboard/gulpfile.js
- blueocean-dashboard/package.json
- blueocean-personalization/gulpfile.js
- blueocean-personalization/package.json
- blueocean-web/gulpfile.js
- blueocean-web/package.json
- blueocean-web/src/main/js/init.jsx
- checkdeps.js
- js-extensions/@jenkins-cd/js-builder.js
- js-extensions/@jenkins-cd/subs/extensions-bundle.js
- js-extensions/package.json
- js-extensions/spec/ExtensionStore-spec.js
- js-extensions/spec/ResourceLoadTracker-spec.js
See [JENKINS-37006](https://issues.jenkins-ci.org/browse/JENKINS-37006).
Depends on these PRs (most of the changes are there):
* https://github.com/jenkinsci/js-modules/pull/2
* https://github.com/jenkinsci/js-builder/pull/5
`js-modules` support for version range/wildcard module `import` + support for `export` of internal deps (e.g. exporting `react` and `react-dom` from the main `blueocean-web` bundle).
So, the explicit export code in the `init.jsx` in `blueocean-web` is gone now. Exports (and imports) are now done in the `package.json` i.e.
```javascript
"jenkinscd": {
"import": [
"history",
"immutable",
"keymirror",
"react-redux",
"react-router",
"redux",
"redux-thunk"
],
"export": [
"@jenkins-cd/js-extensions",
"@jenkins-cd/design-language",
"react",
"react-dom"
]
}
```
> Of course, …
> [JENKINS-37006] Improved module resolution/loading/sharing across browser bundles

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ActionProxiesImpl.java
See https://issues.jenkins-ci.org/browse/JENKINS-36980
Hard to reproduce, but following might reproduce:
* create a parameterized freestyle job with a parameter and run couple of builds
* install rebuild plugin, restart, try rebuilding the jobs by clicking 'rebuild last' link
* then call GET on http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/:jobName/runs/
If underlying plugin threw NPE reported in the JIRA ticket, the exception will be logged on console and a proper response will be returned instead of failure.
Alternatively you could click on the pipeline/job name link in blueocean UI and you should see all the runs listed properly, if underlying plugin threw exception it will be logged in the server log.
https://ci.blueocean.io/job/Acceptance%20Tests%20Param/45/ …
> JENKINS-36980# Handle NPE from actions gracefully

- blueocean-web/src/main/js/main.jsx
- blueocean-web/src/main/js/reload.js
See [JENKINS-36054](https://issues.jenkins-ci.org/browse/JENKINS-36054).
To test ... open classic and BO UIs ... start builds in classic and see events kick activity in BO ui ... shut the lid on your laptop and leave it shut for 30 seconds or so ... reopen and check that the above still works and events trigger activity etc.
No real automated test possible.
@i386 It just does a reload atm and I think it's fine as a v1, but you might want to display something to the user of the form "Your connection to the server was lost. Please reload to continue ..." or whatever.
> [JENKINS-36054] Page reload after hibernate

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
See [JENKINS-37704](https://issues.jenkins-ci.org/browse/JENKINS-37704).
Scroll up handler were never subscribed. To reproduce go to a running build and scroll up with the mouse, before this PR that did nothing, now it should be the same behaviour as pressing the arrow-up (which works fine before and after): stopping karaoke mode.
The AT is covering the key up but not the scrollUp since we would need to simulate that.
> [hotfix/JENKINS-37704] fix typo when things were renamed

- blueocean-web/src/main/js/main.jsx
- blueocean-web/src/main/js/reload.js
See [JENKINS-36054](https://issues.jenkins-ci.org/browse/JENKINS-36054).
A rerun of earlier attempt to handle machine hibernation ... reverting the revert and lengthening the time tolerance from 2 to 20 seconds.
The risk of having it too long is that someone could, in theory, bring a machine into and out of hibernation fast enough for us to ignore it (< 20s ?).
If this does not work then we're going to have try a more complex solution, pinging the server with a request that contains a UUID of some sort, asking the server to try send it back to us over SSE and if we don't get that we then reload, assuming SSE `EventSource` is clobbered and can't be recovered. There are risks that that might not work perfectly either because it too will depend on a time tolerance.
@jenkinsci/code-reviewers …
> [FIX JENKINS-36054] Lengthen page reload time tolerance from 2 to 20 seconds

- blueocean-dashboard/src/main/js/redux/actions.js
See [JENKINS-37722](https://issues.jenkins-ci.org/browse/JENKINS-37722).
To test, create a new Github org folder, build a project with multiple branches, and ensure the activity is updated properly, rather than all to exactly the same branch at the end. A test repo is here: git@github.com:kzantow/failure-project.git
Not really sure how to get this set up in tests, being dependent on a repo with multiple branches.
> JENKINS-37722 - SSE updates were matching against runId only

- blueocean-dashboard/src/main/js/redux/actions.js
- blueocean-dashboard/src/main/js/util/UrlUtils.js
See [JENKINS-37708](https://issues.jenkins-ci.org/browse/JENKINS-37708).
This needs an ATH test, JS tests are insufficient.
To test: set executors to 0, queue a freestyle build, click the queued item validate the 'item is waiting to run' page shows.
> [FIX JENKINS-37708] queued item regression

- blueocean-config/package.json
- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-web/package.json
- js-extensions/package.json
See [JENKINS-37714](https://issues.jenkins-ci.org/browse/JENKINS-37714).
This pulls in fixes from https://github.com/jenkinsci/js-builder/pull/8
No manual tests possible aside from making sure the plugins all build and the ATH runs, all of which is automated.
> [FIX JENKINS-37714] js-builder bundle transform not taking dedupe into account when translating fullPaths to Ids

- blueocean-pipeline-api-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanRootAction.java
- blueocean/pom.xml
- pom.xml
See https://issues.jenkins-ci.org/browse/JENKINS-37744.
- cd blueocean && mvn hpi:run
- Create a kyoto style pipeline, you can clone vivek/hellokyoto
- Run this pipeline all stages and parallels should appear well
- Create legacy pipeline and all should work well
- Make sure anonymous read is disabled (default on fresh install), access http://localhost:8080/jenkins/blue or any other path inside blue should result in redirection to login page.
Ran ATH master branch locally, all tests pass.
- Upgrades Jenkins core to 2.7.3 LTS
- Fixes regression where if JWT is disabled and anonymous read is not allowed access
to /blue/... results in 403, resulting in to classic redirecting user to login page
> JENKINS-37744# Support for Kyoto plugin

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphBuilder.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
See https://issues.jenkins-ci.org/browse/JENKINS-38176
* create pipeline project with script https://gist.github.com/vivek/5b8068b47aa6cae8e85383db4128ce1b
* Build it, check it in BO, you should see 2 parallels left and right
* Not modify the script with https://gist.github.com/vivek/ca1d45e71a781bcd0d4f362088c125cb and trigger build
* Now click on left you should see all its steps, last step being 'waiting for interactive input'
* Click on right nothing happens, thats bug https://issues.jenkins-ci.org/browse/JENKINS-37962
Couldn't run ATH locally, fails with signature failure. can reviewer try running?
> JENKINS-38176# fix for steps API for incomplete parallels

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MatrixProjectImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ExtensionClassContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueExtensionClass.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueExtensionClassContainer.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueFavorite.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueMultiBranchPipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueOrganization.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineFolder.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineNode.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineStep.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueQueueItem.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueUser.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/GenericResource.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/KnownCapabilities.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/Resource.java
See https://issues.jenkins-ci.org/browse/JENKINS-38136
To test classes map functionality:
`curl -v -X POST  http://localhost:8080/jenkins/blue/rest/classes/ -d '{"q":["io.jenkins.blueocean.service.embedded.rest.PipelineImpl","io.jenkins.blueocean.service.embedded.rest.MultiBranchPipelineImpl"]`
Can't run ATH it started failing with "Error: Signature author is required." If reviewer can run, will be great.
- Also pulls in well known capabilities in to a class as constant
- Fixes typo in PullRequest capability
> JENKINS-38136# capability map API changed to POST

- blueocean-dashboard/src/main/js/components/PullRequest.jsx
- blueocean-dashboard/src/test/js/pullRequest-spec.js
Create a GH org with pull requests, click to open the latest run for a pull request. You can use `kzantow` as the org, then filter repositories to `failure-project`. 
See [JENKINS-38300](https://issues.jenkins-ci.org/browse/JENKINS-38300).
> [FIX JENKINS-38300] Fix pull requests within an org folder

- bin/build-in-docker.sh
- blueocean-docker-dev-image/pom.xml
- blueocean-docker-dev-image/src/assembly/docker-dev-image.xml
- blueocean-docker-dev-image/src/main/docker/Dockerfile
- blueocean-pipeline-api-impl/pom.xml
- build-in-docker.sh
- pom.xml
See [JENKINS-37141](https://issues.jenkins-ci.org/browse/JENKINS-37141).
This is currently a work in progress to discuss the approach. Dependency resolution of plugins doesn't work correctly unfortunately. It's based on `install-plugins.sh` script for the official Jenkins image, but it seems this script suffers from some issues (see [JENKINS-36828](https://issues.jenkins-ci.org/browse/JENKINS-36828))
The main idea is to use Maven Assembly plugin to gather all BlueOcean plugins files in a folder used as a build context for Docker. Maven can't be used to resolve plugin dependencies from the POM because POM depends on JAR artifacts of plugins but not HPI one. When running Jenkins locally, dependency resolution is done by maven-hpi-plugin. Could be an option to add a new target to this plugin …
> [JENKINS-37141] rework Dockerfile for development image

- pom.xml
Depends on https://github.com/jenkinsci/sse-gateway-plugin/pull/11
See [JENKINS-38252](https://issues.jenkins-ci.org/browse/JENKINS-38252).
Test would be to just make sure e.g. the run button pops up the STARTED toast. Other than that, we need to see if SSE config still appears in the list of blocked requests when BO comes under load.
> [JENKINS-38252] Updated SSE Gateway plugin to 1.10

- blueocean-dashboard/.eslintrc
- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
- blueocean-dashboard/src/test/js/pipeline-graph-converter-spec.js
Fix to show null node results as "not built" instead of "queued" on completed runs.
See [JENKINS-38247](https://issues.jenkins-ci.org/browse/JENKINS-38247).
josh/JENKINS-38247-notbuilt-indicator * Lint
josh/JENKINS-38247-notbuilt-indicator * Fix the bug when watching a live build transition to failed, and add
josh/JENKINS-38247-notbuilt-indicator * Fixed when loading, but not yet when watching a build go from running -> finished
> Fix: Unbuilt stages of a run are showing the wrong indicator

- blueocean-dashboard/src/main/js/components/Step.jsx
See [JENKINS-38044](https://issues.jenkins-ci.org/browse/JENKINS-38044).
In some cases the log returned without logArray which then stopped refetching the log. 
@jenkinsci/code-reviewers @reviewbybees @rtyler 
…ry to fetch again
> [FIX JENKINS-38044] Following runs in Blue Ocean doesn't show console output

- .dockerignore
- Dockerfile
- bin/build-in-docker.sh
- bin/git-helper.sh
- pom.xml
Replaces #523. I had to push my branch to jenkinsci repository in order to get it built by PR builder.
This is a follow-up to JENKINS-37141.
Depends on a fixed Jenkins LTS version instead of latest to ensure reproducible builds.
Don't bypass installation wizard by default as it's here to enforce security.
With this, Docker image built from master branch should be usable for dogfooding, which would make https://github.com/cloudbees/blueocean-docker-image obsolete
> Standardize dogfood and small fixes

- Jenkinsfile
See [JENKINS-37918](https://issues.jenkins-ci.org/browse/JENKINS-37918).
So when a branch is pushed to Blue Ocean and it builds successfully, this change will try trigger the ATH, first trying to trigger a branch of the same name, falling back to master if there is none.
Lets see if https://ci.blueocean.io/job/blueocean/job/trigger-ath/ triggers https://ci.blueocean.io/job/ATH-Jenkinsfile/job/trigger-ath/
> Trigger the ATH, with matching branch name support

- Jenkinsfile
[JENKINS-37918](https://issues.jenkins-ci.org/browse/JENKINS-37918)
Assemble a tar of the plugins needed by BO and the ATH to run, saving the ATH run a lot of overhead/ See https://github.com/jenkinsci/blueocean-acceptance-test/pull/47
> Assemble and archive plugins

- blueocean-core-js/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
Updating es6-promise to 3.3.1
See changelog at https://github.com/stefanpenner/es6-promise/blob/master/CHANGELOG.md#331
Difference between 3.2.1 and 3.3.1.
> Update es6-promise to 3.3.1

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
Seen on https://rollbar.com/i386/blueocean/items/95/ this PR prevents that error from being thrown. I thought every node will provide the edges but on a single node run this problem could be present itself
> [npeFix] prevent npe on edges

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
See [JENKINS-37017](https://issues.jenkins-ci.org/browse/JENKINS-37017).
> [FIX JENKINS-37017] Github Org folder projects detail screen missing org name in path

- blueocean-web/pom.xml
- blueocean-web/src/main/java/io/jenkins/blueocean/BlueOceanUI.java
- blueocean-web/src/main/java/io/jenkins/blueocean/ResourceCacheControl.java
- blueocean-web/src/test/java/io/jenkins/blueocean/ResourceCacheControlTest.java
- pom.xml
See [JENKINS-38013](https://issues.jenkins-ci.org/browse/JENKINS-38013).
Will see about writing a unit test.
Fyi, before making this change it would always make an `If-Modified-Since` request to the browser, resulting in at least an empty requests/response sequence, which can be costly if you live in the boonies in Australia. E.g. .... see the following wireshark log from before the change (activity page - with "Regular 3G" throttling enabled in the dev tools - rough mimic of slow connection) ....
After making this change, those `If-Modified-Since` requests were eliminated for normal browsing (note these are sill present if you hit the reload button in the browser - in Chrome anyway) 
...
> [JENKINS-38013] Set the Cache-Control header for static and adjunct resources

- blueocean-dashboard/.mvn_exec_node
- blueocean-dashboard/package.json
- blueocean-personalization/.mvn_exec_node
- blueocean-personalization/package.json
- blueocean-web/.mvn_exec_node
- blueocean-web/gulpfile.js
- blueocean-web/package.json
- pom.xml
Update the build to use the new plugin parent pom (2.17). This involved a few small tweaks to some of the `package.json` files, adding `mvnbuild` and `mvntest` scripts (executed by the maven profiles).
> Update to use the new plugin parent pom (2.17)

- blueocean-dashboard/src/main/js/components/PipelineRowItem.jsx
- blueocean-dashboard/src/test/js/pipeline-spec.js
See [JENKINS-38042](https://issues.jenkins-ci.org/browse/JENKINS-38042).
There is no unit test as the displayed value of the `Link` in `PipelineRowItem` is not tested at this point. 
I "manually" validated the change: I created a job which I named `my-ugly-project` and set its __Display name__ to `My Beautiful project`. I also reacted another project without changing the __Display name__ to validate it didn't affect the current behavior. But as the `displayName` is filled with the `fullName` when it's not specified, then the front part of this plugin has no impact on this.
I couldn't run a complete build of the project as the current `master` branch has code inspections issues (lines being too longs) even before I coded my patch.
> Prefer the displayName rather than the fullName for prettier display

- Jenkinsfile
It's not necessary to run hpi:assemble-dependencies to prepare the ATH plugin archive. It's already done in https://github.com/jenkinsci/blueocean-plugin/blob/master/blueocean/pom.xml#L132 to make plugins available for building the development Docker image.
This should reduce build time by 1 minute.
> Don't run hpi:assemble-dependencies again

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/README.md
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
See [JENKINS-38335](https://issues.jenkins-ci.org/browse/JENKINS-38335).
Running ATH locally fails. If @michaelneale can give it shot will be great otherwise will try it tomorrow and ask for help around.
numberOfRunningPipelines is very expensive call, pretty much results in to
iteraring over all builds in the pipeline. With Search API, it gets worse as we
recursively iterate over each job/pipeline and determine if its running or not.
There is no esay way in Jenkins to compute this value optimally.
There is no UI code that needs this field and also numberOfQueuedPipelines field
is not used. As part of this fix, I am removing these fields from Pipeline API response.
> JENKINS-38335# Slow search API response fix

- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/incompatibleie.jelly
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
See [JENKINS-38811](https://issues.jenkins-ci.org/browse/JENKINS-38811).
This broke because of a change we made in js-builder a few weeks ago wrt how it generates the paths to bundle assets.
> [FIX JENKINS-38811] Fix IE adjunt loading

- blueocean-personalization/src/test/js/components/DashboardCards-spec.jsx
- blueocean-personalization/src/test/js/data/favorites.json
- These tests began failing in JENKINS-38023 but due to a gulp / mocha config issues, the failures were not reported in CI. 38013 exposed the failures but somehow were merged to master. This PR fixes the failures.
> fix tests that began failing in 38023 / 38013

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
See [JENKINS-39296](https://issues.jenkins-ci.org/browse/JENKINS-39296).
To manually test, create pipeline job to create unstable run with steps that are successful. Also create job with failing and successful steps, each sep should demonstrate correct status.
**Please note:**
* Underlying Pipeline library (and bismuth library) doesn't give a ways to determine ABORTED or UNSTABLE result at individual Step FlowNode level. So if a Run is aborted, the step that gets aborted is reported as simply error. There is not status to say if its unstable.
Triggered https://ci.blueocean.io/job/ATH-Jenkinsfile/job/master/227/
> JENKINS-39296# Fix to show step's status correctly

- blueocean/pom.xml
Bundles the Blue Ocean display URL plugin. When this plugin is installed it replaces all the classic URIs issued in emails, hipchat, slack, etc with Blue Ocean URIs.
See [JENKINS-39206](https://issues.jenkins-ci.org/browse/JENKINS-39206).
> JENKINS-39206 - BlueOcean Display URL Plugin

- blueocean-dashboard/src/main/js/OrganizationPipelines.jsx
- blueocean-dashboard/src/main/js/components/Branches.jsx
- blueocean-dashboard/src/main/js/components/MultiBranch.jsx
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/js/components/PullRequest.jsx
- blueocean-dashboard/src/main/js/components/PullRequests.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/components/Runs.jsx
- blueocean-dashboard/src/test/js/branches-spec.js
- blueocean-dashboard/src/test/js/pipelines-spec.js
- blueocean-dashboard/src/test/js/pullRequest-spec.js
In some circumstances, that are not reproducible, the listing of pipelines has shown a blank list.
I do not why I had this circumstances, but the usage of context had been wrong anyhow in this place.
https://issues.jenkins-ci.org/browse/JENKINS-39587
> [FIX JENKINS-39587] refactor to not use context but use standard properties

- blueocean-web/src/main/less/try.less
When custom Jenkins styling is used, like [jenkins-contrib-themes][1], 
the "Try" button breaks the style and looks [alien][2]. This patch fixes 
[this][3] by removing blue background, allowing to reuse global one.
[1]: https://jenkins-contrib-themes.github.io/jenkins-material-theme
[2]: http://i.imgur.com/R8B6sKS.png
[3]: http://i.imgur.com/hwxJwBj.png
> Use global style colors for try ocean button

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueUser.java
See [JENKINS-39764](https://issues.jenkins-ci.org/browse/JENKINS-39764).
To test install the gravatar plugin and have a gravatar registered for your Jenkins email address. Hit the rest resource for your user and you should see an avatar field in the response.
> Generate URL to user avatar on User resource

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
See [JENKINS-39775](https://issues.jenkins-ci.org/browse/JENKINS-39775).
To reproduce, run the code below and see karaoke, you should see the stack trace.  With this fix, it will go away. 
```
stage 'test'
parallel 'unit':{
node{
echo "Unit testing..."
sh 'sleep 1000'
}
}
```
> JENKINS-39775# EmptyStackException fix

- blueocean-dashboard/src/main/js/util/smart-fetch.js
- While working on an unrelated bug, I noticed that React errors were being silently swallowed on some screens. On the Activity tab, if an error occurred during render after data fetch, the screen would break with no error being printed in console. I tracked this down to the use of `catch()` in the `smart-fetch` library. I switched it to use a fault handler instead and now errors display as expected.
- Relevant discussion: https://github.com/facebook/react/issues/4199
…t React errors aren't swallowed
> bug / smart fetch fault handler

- blueocean-web/src/main/less/try.less
In the #598 PR I did a big mistake and forgot to fix border color of the button as well while I did everything right locally as screenshot shows. I just notices that issue after plugin update, when it overrided mine patched one. Sorry for that! ):
> Fix border color for try blue ocean button

- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/test/js/activity-spec.js
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineQueueContainer.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
Root cause with a divide by zero error in backend. 
See [JENKINS-39981](https://issues.jenkins-ci.org/browse/JENKINS-39981
ATH PR: https://github.com/jenkinsci/blueocean-acceptance-test/pull/68
> [JENKINS-39981] Show activities properly when no activities exist

- blueocean-dashboard/src/main/js/components/MultiBranch.jsx
Check for multibranch capabilities sooner stops javascript error.
See [JENKINS-39979](https://issues.jenkins-ci.org/browse/JENKINS-39979).
ATH Pr to cover this https://github.com/jenkinsci/blueocean-acceptance-test/pull/67
> [JENKINS-39979] Check for multibranch capabilities sooner

- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- js-extensions/package.json
- In #572 I accidentally forgot to release a prod version of `js-extensions` so version "0.0.31-sandbox1" was accidentally merged to master. This PR fixes this. Tested locally and looks good; will self-merge once CI passes.
> release prod version of latest js-extensions; update blueocean to use it

- docker/official/Dockerfile
- docker/official/build.sh
- docker/official/pom.xml
See [JENKINS-39804](https://issues.jenkins-ci.org/browse/JENKINS-39804).
This is my first take at providing a set of scripts to build an official BlueOcean image. Code is based off the script used to build Jenkins weekly images (see https://github.com/jenkinsci/docker/blob/master/weekly.sh). Like for Jenkins weekly images, the idea would be to trigger `build.sh` after every release.
The image is based on top of the latest Jenkins LTS. It bundles all BO plugins and their dependencies.
> [JENKINS-39804] Script to build the official BlueOcean image

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
See [JENKINS-40135](https://issues.jenkins-ci.org/browse/JENKINS-40135).
Following script cause NPE, this PR fixes that. Similar script in ATH (src/test/resources/multibranch_1 ) fails with same NPE. I think this used to pass on master, perhaps underlying workflow-api was upgraded. In any case MemoryFlowChunk.getLastNode() is returning null that its not supposed to and that resulted in NPE. A non-null check has been added and https://issues.jenkins-ci.org/browse/JENKINS-40200 is raised.
```
node {
stage 'Stage 1'
stage 'Stage 2'
echo 'hello'
}
```
@reviewbybees 
Root cause is MemoryFlowChunk.getLastNode() returns null, its supposed to be @Nonnull.
JENKINS-40200 raised, as work around null check is added.
> JENKINS-40135# NPE fix with non-block stages without steps in between

- blueocean-web/src/main/java/io/jenkins/blueocean/ResourceCacheControl.java
- blueocean-web/src/test/java/io/jenkins/blueocean/ResourceCacheControlTest.java
See [JENKINS-40116](https://issues.jenkins-ci.org/browse/JENKINS-40116).
@reviewbybees
> [FIX JENKINS-40116] Fix for null return on request.getPageInfo() in ResourceCacheControl

- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/Branches.jsx
Makes latest commit message show on activity and branches tabs. To test, make a change and rerun a branch and the latest commit should how on both.
See [JENKINS-40296](https://issues.jenkins-ci.org/browse/JENKINS-40296).
ATH PR: https://github.com/jenkinsci/blueocean-acceptance-test/pull/85
@reviewbybees
> [JENKINS-40296] Display latest commit messages

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/OrganizationImpl.java
No additional tests should be needed. This will only affect spanish versions of Jenkins by removing the space from the end of the jenkins org.
See [JENKINS-39907](https://issues.jenkins-ci.org/browse/JENKINS-39907).
@reviewbybees
> [JENKINS-39907] Hardcode default org to always be jenkins

- docker/official/Jenkinsfile
See [INFRA-987](https://issues.jenkins-ci.org/browse/INFRA-987).
Provides a Jenkinsfile to build on Jenkins infra.
@rtyler
> [INFRA-987] Jenkinsfile to build the official docker image

- blueocean-dashboard/src/main/js/components/Activity.jsx
See https://issues.jenkins-ci.org/browse/JENKINS-40434
fetchNextPage should be used instead of fetchMore. 
After this change, should delete all trace of fetchMore as AFAICT it isn't used other than in test code. 
Also - need to have an ATH for this but I have done my tour of duty there for this week. 
@reviewbybees
> fetchMore is no longer used.. also someone needs a test for this

- blueocean-dashboard/src/main/java/io/jenkins/blueocean/BlueOceanWebURLBuilder.java
- blueocean-dashboard/src/test/java/io/jenkins/blueocean/BlueOceanWebURLBuilderTest.java
See [JENKINS-40137](https://issues.jenkins-ci.org/browse/JENKINS-40137): "Open in blue ocean button does not work for runs when the branch name contains a /".
See ATH PR: https://github.com/jenkinsci/blueocean-acceptance-test/pull/92
@reviewbybees
> [FIX JENKINS-40137] Fix encoding of job name in "Open Blue Ocean" URLs

- blueocean-dashboard/src/main/java/io/jenkins/blueocean/BlueOceanWebURLBuilder.java
See [JENKINS-39842](https://issues.jenkins-ci.org/browse/JENKINS-39842).
1. Create an MBP down inside a folder tree e.g. a/b/c.
1. Click on one of the folders on that tree (e.g. "b"), but not the MBP folder itself (the leaf folder).
1. Click on the "Open Blue Ocean" button.
Should bring the user to the main top-level pipelines page in BO Vs a blank page in BO, as is the case without the fix.
ATH Test PR: https://github.com/jenkinsci/blueocean-acceptance-test/pull/96
@reviewbybees
> [FIX JENKINS-39842] Open Blue Ocean button should not try to load /activity for a folder

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/js/capability/CapabilityStore.js
- blueocean-core-js/src/js/i18n/i18n.js
- blueocean-core-js/src/js/storage.js
- blueocean-core-js/test/js/capability/CapabilityStore-spec.js
- blueocean-core-js/test/js/storage-clear-spec.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-personalization/src/test/js/CapabilityTestUtils.js
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
.. and the infra for caching other data we might want and eliminate more backend calls.
See [JENKINS-40080](https://issues.jenkins-ci.org/browse/JENKINS-40080). This JIRA was a higher priority a few weeks ago but, for some reason, has dropped out completely now.
These changes eliminate all but the min calls to get class info from the backend by storing the class info in the browser `localStorage` (via a new [@jenkins-cd/storage](https://www.npmjs.com/package/@jenkins-cd/storage) package).
The main part of the changes though (and most interesting from a wider perspective) are the parts around the `localStorage` (see 2392247), how it's invalidated etc. These are bits of infra that we can use for caching other such data on the client and so eliminate more backend calls (e.g. localization …
> [FIX JENKINS-40080] Cache class info in browser storage

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ActionProxiesImpl.java
… FlowGraphAction) from REST responses.
I was able to get a 53x improvement on dashboard load times. Longer term we should be fetching only the actions we need.
*Before*
*After*
PTAL @vivek 
See [JENKINS-40741](https://issues.jenkins-ci.org/browse/JENKINS-40741).
@reviewbybees
> Exclude poorly performing FlowGraphAction from action proxy results

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ActionProxiesImpl.java
> Move null check into predicate function

- blueocean-web/src/main/js/main.jsx
'Administration' Link now links to /manage. IT only shows if user is logged in OR if security is disabled (and therefore anyone can access it).
No ATH changes as we cant log in with ath at this time.
See [JENKINS-36975](https://issues.jenkins-ci.org/browse/JENKINS-36975).
@reviewbybees
> [JENKINS-36975] Show admin link at the correct times

- Dockerfile
This should fix the PR deployer which is failing to build Docker images because `npm` is not available in standard Jenkins image.
Regression introduced in #665
@reviewbybees @michaelneale @cliffmeyers
> don't try to run npm, it's not available in official jenkins image

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/AbstractGithubOrganization.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrganization.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubUserOrganization.java
Only serve up github avatars at 50x50px to reduce size. As @cliffmeyers discovered some avatars can be unreasonably big.
PTAL @vivek @cliffmeyers 
@reviewbybees
> GH avatar sizes

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
Bug was in union of nodes, specifically if current dag is partial and
current node is a parallel then it's edges were not stiched properly
with projected future nodes.
There is also NPE and other minor fixes.
See [JENKINS-41159](https://issues.jenkins-ci.org/browse/JENKINS-41159).
Try this pipeline: https://github.com/i386/app-store-demo and see karaoke on new build and multiple builds. 
You might notice ""Declarative: Checkout SCM"" stage appear instead of 'Build' node, there is a bug in declarative plugin where this stage added by declarative plugin has missing SYNTHETIC_STAGE TagAction, this causes API to return the DAG.   An issue has been opened to take care of this issue: https://issues.jenkins-ci.org/browse/JENKINS-41243
@scherler, @michaelneale, @i386 PTAL. 
@reviewbybees
> JENKINS-41159# Karaoke bug fix - disappearing parallels

- blueocean-web/src/main/js/main.jsx
Correct the default spelling of Administration navigation menu.
> Fix spelling of Administration

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepVisitor.java
See [JENKINS-40466](https://issues.jenkins-ci.org/browse/JENKINS-40466).
I tried this script:
```
pipeline {
agent none
stages {
stage ('first') {
agent { 
label 'first' 
}
steps{
sh 'echo "from first"'
}
}
}
}
```
GET http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/:pipelineId/runs/:runId/nodes/
```
[
{
"state" : "QUEUED",
"result" : "UNKNOWN",
"startTime" : "2017-01-10T13:35:30.688-0800",
"id" : "4",
"actions" : [],
"_links" : {},
"durationInMillis" : 8690535,
"causeOfBlockage" : "Waiting for next available executor",
"_class" : "io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeImpl",
"displayName" : "first",
"edges" : [],
"input" : null
}
]
```
@reviewbybees
> JENKINS-40466# Reflect cause of blockage in synthetic step

- pom.xml
pubsub 1.5 of pubsub was not appearing in the update centre because its pom was missing a `<url>` setting.
See [JENKINS-41487](https://issues.jenkins-ci.org/browse/JENKINS-41487).
@reviewbybees
> [FIX JENKINS-41487] Hotfix --- 1.6 and 1.15 of the pubsub and sse-gateway plugins

- blueocean-personalization/src/main/js/components/DashboardCards.jsx
- blueocean-personalization/src/test/js/components/DashboardCards-spec.jsx
See [JENKINS-41053](https://issues.jenkins-ci.org/browse/JENKINS-41053).
Fix bug when favorite had no previous run and add unit test for that case
@reviewbybees
> [FIX-JENKINS-41053] error in personalization when selecting job with no runs

- blueocean-config/npm-shrinkwrap.json
- blueocean-config/package.json
- blueocean-config/src/main/java/io/jenkins/blueocean/config/JenkinsJSExtensions.java
- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/js/config.js
- blueocean-core-js/src/js/i18n/bundle-startup.js
- blueocean-core-js/src/js/i18n/i18n.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/gulpfile.js
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- blueocean-web/src/main/js/blueocean.js
- blueocean-web/src/main/js/init.js
- blueocean-web/src/main/js/jenkins-js-extension.yaml
- blueocean-web/src/main/js/jenkins-js-extensions.yaml
- js-extensions/@jenkins-cd/js-builder.js
- js-extensions/@jenkins-cd/subs/extensions-bundle.js
- js-extensions/package.json
- js-extensions/src/ExtensionStore.js
So we can attach async "startup scripts" to bundles, allowing us to ensure that e.g. i18n resources are loaded before the bundle executes ( [JENKINS-39345](https://issues.jenkins-ci.org/browse/JENKINS-39345) ).
Depends on https://github.com/jenkinsci/js-builder/pull/11
Other probably uses of this feature would be js extension metadata, allowing us to ensure that it's loaded before the extensions are executed etc. CC @kzantow.
Not really possible to write any additional meaningful automated tests for this imo (we actually already have an ATH test), unless someone has a good idea that I'm missing. To manually test ... just switch languages and see that the switch happens immediately, where as before, it only switched after clicking on something in the ui and causing a rerender. …
> [JENKINS-39345] Async bundle startup scripts

- blueocean-core-js/package.json
- blueocean-core-js/src/js/parameter/components/Boolean.jsx
- blueocean-core-js/src/js/parameter/components/Password.jsx
- blueocean-core-js/src/js/parameter/components/String.jsx
- blueocean-core-js/src/js/parameter/components/Text.jsx
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
Fix for regression caused by https://github.com/jenkinsci/blueocean-plugin/pull/771
Fooled by one of the ES6 "enhancements". Need to explicitly name the object property, otherwise the `name` property doesn't get mapped onto the input element.
@reviewbybees
> JENKINS-41162-regression-hotfix - explicitly name prop

- blueocean-dashboard/src/main/js/components/MultiBranch.jsx
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
To test create a multibranch job with a SCM configured, then go to branches tab and empty state should now show.
See [JENKINS-40627](https://issues.jenkins-ci.org/browse/JENKINS-40627).
ATH https://github.com/jenkinsci/blueocean-acceptance-test/pull/115
@reviewbybees
> [JENKINS-40627] Show branches empty state correctly

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ActionProxiesImpl.java
On my test data it took a total of 245 ms (15.75KB) to load 48 runs. After this change it took 174ms (13.5KB) to load the same data **resulting in a 71% improvement**.
OOTB it reduces the amount of actions returned for a WorkflowRun BlueRun from 12 to 5.
See [JENKINS-40880](https://issues.jenkins-ci.org/browse/JENKINS-40880).
@reviewbybees
> Do not return action proxies that are not exported beans

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueUser.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueUserPermission.java
See [JENKINS-41433](https://issues.jenkins-ci.org/browse/JENKINS-41433).
- Create two users on Jenkins with different pipeline permissions, keep one of the user admin and another not
- curl -v -u userid:password http://localhost:8080/jenkins/blue/rest/organizations/jenkins/users/:uid/
```
{
"permission" : null,
"avatar" : null,
"_class" : "io.jenkins.blueocean.service.embedded.rest.UserImpl",
"fullName" : "admin",
"_links" : {
"favorites" : {
"href" : "/blue/rest/organizations/jenkins/users/admin/favorites/",
"_class" : "io.jenkins.blueocean.rest.hal.Link"
},
"self" : {
"href" : "/blue/rest/organizations/jenkins/users/admin/",
"_class" : "io.jenkins.blueocean.rest.hal.Link"
}
},
"email" : "admin@c.com",
"id" : "admin"
}
```
> User with admin privilege can see other user's permissions. …
> JENKINS-41433# User permission api

- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepVisitor.java
- pom.xml
See [JENKINS-41421](https://issues.jenkins-ci.org/browse/JENKINS-41421).
Basic change in PipelineStepImpl.java rest is to adopt to the v. 2.5 of pipeline-input-step
@reviewbybees
> [FIX-JENKINS-41421] Extend StepImpl to pass along submitterParameter

- blueocean-dashboard/src/main/java/io/jenkins/blueocean/BlueOceanWebURLBuilder.java
- blueocean-dashboard/src/main/java/io/jenkins/blueocean/TryBlueOceanURLs.java
- blueocean-dashboard/src/main/resources/io/jenkins/blueocean/TryBlueOceanPageDecorator/header.jelly
- blueocean-dashboard/src/test/java/io/jenkins/blueocean/BlueOceanWebURLBuilderTest.java
- blueocean-dashboard/src/test/java/io/jenkins/blueocean/preload/StatePreloaderTest.java
- blueocean-web/src/main/js/try.js
... so that it no longer matters if the configured Jenkins URL is different to current browser URL e.g. from outside a proxy.
See [JENKINS-41638](https://issues.jenkins-ci.org/browse/JENKINS-41638).
To test ... run a local Jenkins with this change ... run something like `ngrok` locally ... browse to the Jenkins via the `ngrok` URL  e.g. browsing to `http://555862b4.ngrok.io/jenkins/job/ATH/job/activateFolder/` should result in an "Open Blue Ocean" linking to `http://555862b4.ngrok.io/jenkins/blue/organizations/jenkins/ATH/branches` Vs it trying to use the configured Jenkins URL (`localhost:8080` etc)..
@reviewbybees
> [FIX JENKINS-41638] "Open Blue Ocean" construction by replacing the classic object path with the blue ocean object path

- blueocean-core-js/package.json
- blueocean-core-js/src/js/security.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/PipelinePage.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
See [JENKINS-40755](https://issues.jenkins-ci.org/browse/JENKINS-40755).
Hmmm ... not sure how we can do an ATH test for this without the ability to login and set permissions. Manual testing obviously involves adding a user with just read permissions and checking that they don't get the settings link.
@reviewbybees
> [FIX JENKINS-40755] Disable settings link when user does not have edit permissions

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/js/services/DefaultSSEHandler.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
[See JENKINS-42068](https://issues.jenkins-ci.org/browse/JENKINS-42068)
Side effect of the new MBP indexing events. Results in an "undefined" row inserted into the list of branches in a MBP.
@reviewbybees esp @cliffmeyers
> [FIX JENKINS-42068] Ignore queue-enter MBP indexing event in `core-js:services/DefaultSSEHandler.js`

- blueocean-dashboard/src/main/js/creation/github/GithubCreationState.js
- blueocean-dashboard/src/main/js/creation/github/GithubFlowManager.js
- blueocean-dashboard/src/main/js/creation/github/api/GithubCreationApi.js
- blueocean-dashboard/src/main/js/creation/github/steps/GithubCompleteStep.jsx
- As discussed, if the user selects "single repo", indexing finishes and the pipeline wasn't created, we'll assume there is no Jenkinsfile and provide a button that opens the editor. Note: editor doesn't actually open yet, pending some integration done presumably in a separate PR.
- I added a lot more console logging to more easily debug what's going on. In Chrome, open dev tools, go to "Application" tab, then on the left "Storage" -> "Local Storage" for your jenkins (localhost:8080 typically) then find `jenkins-instance/logging/categories:io.jenkins.blueocean.github-pipeline` and make sure it's set to `DEBUG` - you may have to run the app once for this key to appear automatically. After setting the value, refresh your browser for it to take effect.
- See …
> [JENKINS-42148] single repo missing jenkinsfile

- blueocean/pom.xml
- pom.xml
We can include the editor this way, worked for me locally. See how this works. 
cc @i386 @kzantow I think this is how it could happen - right? 
https://issues.jenkins-ci.org/browse/JENKINS-42134
> why not include editor, the proper way

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/ServiceException.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineUpdateRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
See [JENKINS-41439](https://issues.jenkins-ci.org/browse/JENKINS-41439).
@cliffmeyers Revoked tokens or tokens whose scope is changed to not carry required scope is reported as 428 error.
Regarding other issue of reporting error if credential's access token is invalid and report it as error while rendering credentialId: its not going to be possible. Main reason is, credentialId is a property in the bean and we can't fail serialization of entire bean as stapler has already started writing to output stream. Besides there are issues of calling GitHub api eagerly and might impact rate limit.
@reviewbybees
> JENKINS-41439# Fix to handle invalid access token correctly

- blueocean-core-js/npm-shrinkwrap.json
- blueocean-core-js/package.json
- blueocean-core-js/src/js/config.js
- blueocean-core-js/src/js/index.js
- blueocean-core-js/src/js/utils/UrlUtils.js
- blueocean-core-js/src/less/header.less
- blueocean-core-js/test/js/UrlUtils-spec.js
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- blueocean-web/src/main/js/main.jsx
- blueocean-web/src/main/resources/jenkins/plugins/blueocean/web/Messages.properties
See [JENKINS-38751](https://issues.jenkins-ci.org/browse/JENKINS-38751).
Can be manually tested. Look for the "escape to app" widget in the headers (main and run details).
ATH tests: https://github.com/jenkinsci/blueocean-acceptance-test/pull/123
@reviewbybees
> [FIX JENKINS-38751] Escape back to Jenkins classic

- blueocean-dashboard/src/main/less/forms/column-filter.less
ended up being translated to `max-width: 200% !important !important` when the less was compiled and browser marked the max-width property as invalid, causing the width to be as long as the content
> max-width of column filter was incorrect

- blueocean-web/src/main/js/try.js
See [JENKINS-42293](https://issues.jenkins-ci.org/browse/JENKINS-42293).
To manually test ... go to the plugin manager in classic and press the "Open Blue Ocean" button ... it should work.
> [FIX JENKINS-42293] use <head> rooturl when there's no Stapler object to extract the root context from

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/InputStepImpl.java
See [JENKINS-41662](https://issues.jenkins-ci.org/browse/JENKINS-41662).
`io.jenkins.blueocean.rest.impl.pipeline.InputStepImpl` has some unusual code, resetting the ID of the underlying pipeline `InputStep` instance to a random ID. The result of this ... two browsers load the same input step ... the first browser is screwed because the id it is using to submit against no longer corresponds to a valid ID because the load from the second browser caused it to be changed via `io.jenkins.blueocean.rest.impl.pipeline.InputStepImpl`.
@vivek hey Vivek ... can you look at this and tell us what was the intention behind the original impl, if you can still remember (I know you are like me and getting old ... memory failing ;) ).
> [FIX JENKINS-41662] Input submissions not working if another browser loads the same input step

- blueocean-github-pipeline/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- pom.xml
@michaelneale @vivek a number of new pipeline updates are available we should integrate and test with.
@reviewbybees
> Bump pipeline and git dependencies

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BaseTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/pageable/PagedResponse.java
See [JENKINS-41372](https://issues.jenkins-ci.org/browse/JENKINS-41372).
GET http://localhost:8080/jenkins/blue/rest/organizations/jenkins/pipelines/?start=0
should print Link header start parameter to be 0.
```
Link:</jenkins/blue/rest/organizations/jenkins/pipelines/?start=0&limit=100>; rel="next"
```
> JENKINS-41372# Fix to show correct Link header start parameter

- js-extensions/package.json
- js-extensions/spec/ExtensionRenderer-spec.js
- js-extensions/src/ExtensionRenderer.jsx
Something I need in order to do the table migration nicely; add some classNames to ExtensionRenderer and the ability to specify additional classes from client code.
See [JENKINS-41833](https://issues.jenkins-ci.org/browse/JENKINS-41833).
> Adding some classNames to ExtensionRenderer

- blueocean-dashboard/src/main/js/PipelineRoutes.jsx
- blueocean-dashboard/src/main/js/components/Activity.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
Switchs branch filtering to use query params. Has side effect of ativity tab button staying selected. @michaelneale is there any other places that redirect to a filtered branch that you know of?
See [JENKINS-42920](https://issues.jenkins-ci.org/browse/JENKINS-42920).
> [FIX JENKINS-42920] Switch to using query params for branch filtering

- blueocean-dashboard/src/main/js/components/Activity.jsx
See [JENKINS-43203](https://issues.jenkins-ci.org/browse/JENKINS-43203).
In short: the options branch dropdown is unsorted currently. 
***Why no UT added***: kinda like `decodeURIComponent`, the sort is a method provided by js runtime which works stable.
***How to test***: Open any pipeline and open the branch dropdown 😃
> JENKINS-43203, sort branch options alphabetically

- docker/official/Dockerfile
This makes it easy to demo and use the container for Dockery workloads, which makes the Pipeline Editor muy bueno.
For example, with this commit: `docker run -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean`
Will allow the user to get started right away with Jenkinsfiles such as:
```groovy
pipeline {
agent { docker { image 'maven:3-alpine' }
stages {
stage('Build') {
steps {
sh 'mvn'
}
}
}
}
```
> Support docker-from-docker more easily

- README.md
As we talked in gitter, `blueocean-sample-pipeline-result-ext-plugin` is deprecated😃
> Remove deprecated plugin-dev reference

- blueocean-dashboard/src/main/js/components/testing/TestCaseResultRow.jsx
To test have some skipped tests in the pipeline and ensure they have the not built indicator rather than the yellow "unstable".
See [JENKINS-42417](https://issues.jenkins-ci.org/browse/JENKINS-42417).
> JENKINS-42417 Skipped tests should not use "unstable" coloring

- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
`@jenkins-cd/preferences` was not transpiled, breaking IE 11
See [JENKINS-43896](https://issues.jenkins-ci.org/browse/JENKINS-43896).
> [FIX JENKINS-43896] Non-transpiled dependency broke IE 11

- blueocean-config/npm-shrinkwrap.json
- blueocean-config/package.json
- blueocean-dashboard/npm-shrinkwrap.json
- blueocean-dashboard/package.json
- blueocean-personalization/npm-shrinkwrap.json
- blueocean-personalization/package.json
- blueocean-web/npm-shrinkwrap.json
- blueocean-web/package.json
- js-extensions/package.json
Related to [JENKINS-39657](https://issues.jenkins-ci.org/browse/JENKINS-39657).
Depends on https://github.com/jenkinsci/js-builder/pull/16.
Basically ... a `js-builder` that generates metadata that can be used by https://github.com/tfennelly/jenkins-js-modules-chrome-ext for runtime analysis of bundles.
> @jenkins-cd/js-builder@0.0.57 on dependants

- blueocean-dashboard/src/main/less/core.less
Made the html tag have a 100vw width that will ignore the appearance or disappearance of the vertical scrollbar on systems that have a mouse attached, this bug did not manifest when only a touchpad was present.
A possible problem with this fix would appear if we need to ever horizontal scroll the html tag. If we ever need to do that, an alternate fix to this bug is to make the vertical scrollbar always appear on systems that have a mouse connected but this fix is preferred because the the vertical scrollbar won't appear if it is not needed.
No tests are necessary because the fix consists of only css changes
See [JENKINS-44048](https://issues.jenkins-ci.org/browse/JENKINS-44048).
> fix content jumping when vertical scrollbar appears/disappears

- docker/official/build.sh
This tags the image additionally with the LTS id. Thus in theory, if a new LTS is published before a new blue ocean, it will then publish a the same blue ocean but with the new LTS. 
I don't have the environment to test this in, so up to @rtyler to approve or reject this.
> Automatically republish if a new LTS is available

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
See [JENKINS-44270](https://issues.jenkins-ci.org/browse/JENKINS-44270).
> [JENKINS-44270] - BlueOcean organization root ItemGroup not taken into account for Links and fullName on the API

- blueocean-dashboard/src/main/js/components/RunMessageCell.jsx
- blueocean-dashboard/src/test/js/run-message-cell-spec.js
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
This change is fairly nuanced but results in a more relevant experience for users.
Included in this change:
* When we detect the replay cause on the current run we lookup the original run and return its changesets.
* It turns out the first cause in the array is the least significant - replayed runs never had the correct cause displayed and is now fixed.
* If there are two or more causes on the run then the last cause in the array is more important to the user than the changeset message when viewing Activity or Branches tabs.
- Create a pipeline and run it so that it contains a few changesets
-  Message column on Activity should be the changeset
- Replay the run
- Message column on Activity should be "Replayed #?" where ? is the run number of the original run
See …
> JENKINS-44258 Replayed runs have same changeset as original

- blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
- blueocean-dashboard/src/main/js/components/records.jsx
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderRunImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueuedBlueRun.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/Containers.java
- See [JENKINS-44321](https://issues.jenkins-ci.org/browse/JENKINS-44321).
> bug / JENKINS 44321 changes tab doesn't load

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
Fixes bug where the incorrect cause for a replayed run would be shown.
In `RunMessage.jsx` we do this:
`const cause = run.causes[run.causes.length-1].shortDescription;`
You can see the bug here:
> Fix cause on run details

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
Return latest 'limit' number of runs across all branches.
See https://issues.jenkins-ci.org/browse/JENKINS-44501
> MBP pipeline run pagination fix

- blueocean-commons/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/scm/ScmContainer.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineJobFiltersTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- pom.xml
See [JENKINS-43916](https://issues.jenkins-ci.org/browse/JENKINS-43916).
Test coverage improved to 100% class and 75% line. We need to move out `scm.*` classes over to rest module as they are strictly abstract models for SCM api. These are excluded from coverage in this module as their coverage is in `blueocean-github-pipeline`.
> JENKINS-43916# blueocean-pipeline-api-impl test coverage improvement

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/JsonConverter.java
- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/ServiceException.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmContentProvider.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmSaveFileRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/HttpRequest.java
- blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/JwtAuthenticationServiceImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineQueueContainer.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/ScmResourceImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/credential/CredentialSearch.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/credential/CredentialsUtils.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractPipelineCreateRequest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BlueTestResultContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineSearch.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunSearch.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/Query.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/Utils.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineContainer.java
Better late than never? :-)
I've done the change in a way that normally anyone using `BadRequestExpception` already, even catching it shouldn't see a difference (since I made it a subclass).
I have built the whole `blueocean-plugin` locally, and if this also builds in CI I guess this would already show the change is actually backward compatible.
The `ServiceException.BadRequestExpception` class was renamed  `ServiceException.BadRequestException` (typo removed).
Not filing a JIRA for a non-user facing change, but if you generally do, just tell me and I'll happily follow the current process.
- ~~[ ] Link to JIRA ticket in description, if appropriate.~~
- ~~[ ] Change is code complete and matches issue description~~
- ~~[ ] Ran Acceptance Test Harness against PR changes.~~
> Fix typo: BadRequestExpception => BadRequestException

- pom.xml
This is probable fix for flakiness we observed that might be due to
other dpendencies bringin in later version of JTH that fails with some
tests failing in blueocean.
> Use fixed jenjins-test-harness version to 2.15

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineSearch.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineSearchTest.java
Ensures that the search patterns detailed in [this document](https://docs.google.com/a/cloudbees.com/document/d/1riU62MGFF7A9cInJx04gIwZQ8PGwN9MkQQORC3dGq40/edit?usp=sharing) can be run against the search API.
See [JENKINS-38982](https://issues.jenkins-ci.org/browse/JENKINS-38982).
@michaelneale @imeredith @NicuPascu this means the search API can accept all the types we discussed in the use case document a few weeks ago
Target of this PR is set to @NicuPascu's branch for https://github.com/jenkinsci/blueocean-plugin/pull/1043
> Search API enhancements

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
Attempt to fix `causeofBlockage` related test flakiness. This test has been observed to fail fetching a node that doesn't exist and the stack trace is due to deserialization failure.
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
at [Source: {
"message" : "Stage 11 not found in pipeline pipeline1.",
"code" : 404,
"errors" : [ ]
}; line: 1, column: 1]
at io.jenkins.blueocean.rest.impl.pipeline.PipelineBaseTest.get(PipelineBaseTest.java:142)
at io.jenkins.blueocean.rest.impl.pipeline.PipelineBaseTest.get(PipelineBaseTest.java:120)
at io.jenkins.blueocean.rest.impl.pipeline.PipelineBaseTest.get(PipelineBaseTest.java:111)
at io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeTest.testBlockedStep(PipelineNo …
```
> Fix flaky pipeline blocking test

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
cc @vivek  PTAL
The old test was using parallel - which I don't think is needed there (we test that elsewhere actually, including inputs, in the ATH). I think that resulted in things not always being in the right order. Made it simpler and less brittle.
> this may solve flaky test

- blueocean-dashboard/src/main/js/components/Pipelines.jsx
If blueocean dashboard is accessed in context of organization route it
always showed organizations ignoring organizations.emabled flag. This
fix encorces this flag to show organization name on dashboard.
See [JENKINS-44631](https://issues.jenkins-ci.org/browse/JENKINS-44631).
> JENKINS-44631# Fix to show organization name on Dashboard

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/PageStatePreloader.java
See [JENKINS-44686](https://issues.jenkins-ci.org/browse/JENKINS-44686).
To test it, just call `ExtensionList.lookup(io.jenkins.blueocean.commons.PageStatePreloader.class)` in the script console, before the fix the result is `[null, null, null, null]`, after the fix it is `[com.cloudbees.opscenter.server.bluesteel.BlueSteelCJOCJSContext@52ffb95c, io.jenkins.blueocean.config.BlueOceanConfigStatePreloader@22de629e, io.jenkins.blueocean.config.JenkinsJSExtensionsStatePreloader@6ea2a76c]`
There is nothing to test as there is nothing broken for a user AFAICT.
> [JENKINS-44686] Wrong imported class

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/UserStatePreloader.java
See [JENKINS-44725](https://issues.jenkins-ci.org/browse/JENKINS-44725).
Current tests should be covering this change (it is not adding or modifying any feature). For manual test: just check that the logout button appears correctly when navigating from classic to BO and the user was already authenticated.
> [JENKINS-44725] Move UserStatePreloader to a more appropiate location

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/earlyUnstableStatusShouldReportPunStateAsRunningAndResultAsUnknown.jenkinsfile
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
Pipeline that is set as unstable early in the execution is never shown as running
*Problem*
Pipeline that is set as unstable early in the execution is never shown as running
*What you should see*
The run should always be shown as running if it is still executing
*Screencast for bug*
See [JENKINS-44736](https://issues.jenkins-ci.org/browse/JENKINS-44736).
> JENKINS-44736 - Fix for unstable status

- blueocean-dashboard/src/main/js/components/Pipelines.jsx
fixes the search param not being url safe by encoding the value before pushing it to the url
See [JENKINS-44759](https://issues.jenkins-ci.org/browse/JENKINS-44759).
> encode search string when pushing it to the url string

- docker/official/Dockerfile
- docker/official/build.sh
install-plugins.sh script downloads a too recent version of workflow-job
let's force it to latest compatible version with 2.46 LTS to quickly fix
the Official image.
This is in order to fix the actual 1.1.0 image. 
@i386 @rtyler
> fix official Docker image

- docker/official/Jenkinsfile
In order to fix [JENKINS-44752](https://issues.jenkins-ci.org/browse/JENKINS-44752).
@i386 
@rtyler could you launch a build after it gets merged (with FORCE_REBUILD=true)? thanks
> add a parameter to rebuild the last official Docker image

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ContainerFilter.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ContainerFilterTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/pageable/PagedResponse.java
Added pagination to ContainerFilter to avoid checking for PR action only
till page size numbers are collected.
PR https://github.com/jenkinsci/blueocean-plugin/pull/1150 adds caching of Branch and Pull Request to further improve performance.
See [JENKINS-44867](https://issues.jenkins-ci.org/browse/JENKINS-44867).
> JENKINS-44867# PR tab regression fix

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/latestRunIncludesQueued.jenkinsfile
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
Mic and I wrote this test to try to track down a bug (we thought latestRun might not have shown queued items). Thought it was worth keeping the test and ensuring that the latest run comes from the run container since the data her is synthesised (its a union of what we believe is in the queue and the runlist)
> Ensure latest comes from the run container

- acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
ATH needs to run on newer jenkins versions - will see if this works first with vanilla
> ATH runtime dependencies bump

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/NodeRunStatus.java
This literally always returned SUCCESS, since it could only *not*
return SUCCESS if errorAction != null, and we already have an if
statement for exactly that. So let's simplify the code a little.
(no ticket - this is such a tiny change I assumed it didn't merit one)
No tests are added - this is a simplification of existing code that should match the existing behavior perfectly, so it just has to pass the existing tests to be valid.
No manual tests are needed either, IMO.
cc @reviewbybees @vivek
> Eliminate pointless PipelineNodeUtil.getStatus call

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubEnterpriseScm.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServer.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerContainer.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
You can manage the GitHub servers that Jenkins has registered with this API
```
POST /blue/rest/organizations/jenkins/scm/github-enterprise/servers/
{
"name": "Github Enterprise",
"apiUrl": "http://github.mycorp.com"
}
```
```
GET /blue/rest/organizations/jenkins/scm/github-enterprise/servers/
[
{
"_class": "io.jenkins.blueocean.blueocean_github_pipeline.GithubServer",
"_links": {
"self": {
"_class": "io.jenkins.blueocean.rest.hal.Link",
"href": "/blue/rest/organizations/jenkins/scm/github-enterprise/servers/Github%20Enterprise/"
}
},
"apiUrl": "http://github.mycorp.com",
"name": "Github Enterprise"
}
]
```
> Enumerate Github Servers

- docker/official/Jenkinsfile
The assumption that the Jenkins agent will simply have ~/.docker/config.json
around is no longer true.
Related to INFRA-1066
> Properly use the latest Docker credentials in our trusted.ci env for publishing

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/JSON.java
- blueocean-commons/src/test/java/io/jenkins/blueocean/commons/JSONTest.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
@abayer @vivek looks like `ArgumentsAction.getStepArgumentsAsString` might include `\t` and other characters that are bad for JSON. Should this really be updated in workflow-api? I am not sure having a `\t` character in a step name is something good for human eyeballs anyway. Feels some sanitation should occur there rather in blue ocean?
The problem is that when we encounter these issues parts of the UI fail to load as described in the ticket below.
See [JENKINS-45099](https://issues.jenkins-ci.org/browse/JENKINS-45099).
> Sanitise step descriptions

- blueocean-core-js/src/js/analytics/AnalyticsService.js
- blueocean-core-js/src/js/index.js
Adds `AnalyticsService` to core-js that allows events to be tracked:
```
import analyticsService from '@jenkins-cd/blueocean-core-js';
analyticsService.track('cool_event', { prop1: 123, prop2: 'hello world' });
```
**POST /blue/rest/analytics/track**
```
{
name: 'cool_event',
properties: {
prop1: 123,
prop2: 'hello world'
}
}
```
See [JENKINS-45144](https://issues.jenkins-ci.org/browse/JENKINS-45144).
> Add ability to post to the analytics track endpoint

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServer.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerContainer.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerTest.java
- pom.xml
Stephen tells me that addEndpoint() will survive the API changes he
has planned for Github Branch Source and endpoint unification.
> Move to addEndpoint() to retain binary compatibility

- pom.xml
branch-api-plugin 2.0.11 depends on cloudbees-folder-plugin 6.1.0, it uses code from it. This is causing classic page load failure with:
```
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: …
```
> Bump cloudbees-folder-plugin to 6.1.0 to fix classic dashboard error

- blueocean-github-pipeline/pom.xml
- pom.xml
No need for installations to keep installing it anew, the required functionality
has been incorporated into the github-branch-source plugin.
See: https://github.com/jenkinsci/github-organization-folder-plugin
> Since version 1.6, the GitHub Organization Folder has been an obsolete tombstone

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueUtil.java
```
Caused by: java.lang.NullPointerException
at io.jenkins.blueocean.service.embedded.rest.QueueUtil.getQueuedItem(QueueUtil.java:24)
at io.jenkins.blueocean.events.BlueMessageEnricher.enrich(BlueMessageEnricher.java:96)
at org.jenkinsci.plugins.pubsub.PubsubBus.publish(PubsubBus.java:133)
... 21 more
```
Reported on [JENKINS-45589](https://issues.jenkins-ci.org/browse/JENKINS-45589) but unrelated to that issue.
> JENKINS-45589 Fix NPE when matching queued items

- blueocean-events/src/main/java/io/jenkins/blueocean/events/BlueMessageEnricher.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchContainerImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueItemImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/factory/BluePipelineFactory.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/factory/organization/OrganizationFactory.java
It's possible not to get back a valid `BlueOrganization` when using methods on `OrganizationFactory`. There still feels like there is a bug somewhere here but without paths for the items that we are resolving there is no way to tell.
This should add some better exception messages and setup expectations that `OrganizationFactory` may not work in some circumstances.
See [JENKINS-45589](https://issues.jenkins-ci.org/browse/JENKINS-45589).
> JENKINS-45589 check for null when using OrganizationFactory

- pom.xml
Fixes a bug where if the Bitbucket branch source cannot find a default branch the scan will fail.
See [JENKINS-45632](https://issues.jenkins-ci.org/browse/JENKINS-45632).
> JENKINS-45632 Handle when default branch is not found

- pom.xml
Upgrade to Blue Ocean display URL provider 2.1.0
Just bumping the POM to incorporate https://github.com/jenkinsci/blueocean-display-url-plugin/pull/8
See [JENKINS-45748](https://issues.jenkins-ci.org/browse/JENKINS-45748).
> JENKINS-45748 Blue Ocean display URL provider

- js-extensions/spec/ExtensionRenderer-spec.js
* Fix mockResourceLoadTracker object used in ExtensionRenderer test code
See [JENKINS-45849](https://issues.jenkins-ci.org/browse/JENKINS-45849).
> Fix failing unit test in js-extensions

- blueocean-dashboard/src/main/js/creation/bitbucket/steps/BbCredentialStep.jsx
- blueocean-dashboard/src/main/less/creation/bitbucket.less
- blueocean-dashboard/src/main/less/creation/index.less
Set username / password fields in Bitbucket cloud login step to 100% width
See [JENKINS-45560](https://issues.jenkins-ci.org/browse/JENKINS-45560).
> Bitbucket username and password fields should be full width

- blueocean-dashboard/src/main/less/pipeline-run-graph.less
bug/JENKINS-46009-safari-pipeline-alignment * Fix pipeline graph alignment issue in Safari
See [JENKINS-46009](https://issues.jenkins-ci.org/browse/JENKINS-46009).
> JENKINS-46009 Pipeline graph on safari is incorrectly placed to the left

- acceptance-tests/src/main/nightwatch.json
I disabled this ages ago as ANSI color appeared as garbage. But now due to @sophistifunk wizardry everything is perfect.
https://github.com/jenkinsci/blueocean-acceptance-test/pull/141/files
> Enable ANSI colours for night watch

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ArtifactContainerImplTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ProfileApiTest.java
- When we have to disable flaky or broken tests, we should use `@Ignore` so they show up on the skipped report.
> use @Ignore so tests show up on skipped report

- blueocean-personalization/src/main/js/components/PipelineCard.jsx
- The branch name on favorites cards always truncates when using git-flow branch naming. This just adds a "tooltip" on hover.
> hotfix / favorites cards branch title

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
Adds a new header X-Text-Delivered to the log response to make paging easier.
See [JENKINS-44699](https://issues.jenkins-ci.org/browse/JENKINS-44699).
> Add another response header to log requests to show delivered size in bytes for paging

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/JSONDataWriter.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
We need to get something in here until we've got a real fix upstream in Stapler.
@kohsuke we should discuss the role of Stapler in JSON generation. It doesn't quite work and I think we would be better off using Jackson.
1. Run `https://github.com/i386/colortest`
2. Steps don't load due to invalid characters in the step name
After running this PR
See [JENKINS-45099](https://issues.jenkins-ci.org/browse/JENKINS-45099).
> HOTFIX: use Jacksons string encoder for JSON output

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
See [JENKINS-46156](https://issues.jenkins-ci.org/browse/JENKINS-46156).
Previously, Blue Ocean would send the stop signal to a job multiple times until the job completed.
This did not allow jobs to handle aborts properly.
For example, if a job caught the abort exception, and needed to execute some additional steps to cleanup, Blue Ocean would send more stop signals while the job was attempting to clean up.
Now, Blue Ocean will send the stop signal once, and wait for the job to complete.
No existing unit test for the stop workflow to modify.  Just trying to speed up getting this fixed. 
1. Create a job with the scripted pipeline from [JENKINS-46156](https://issues.jenkins-ci.org/browse/JENKINS-46156).
2. Run it
3. Abort it via the Blue Ocean UI
4. Ensure that the sh step in the cleanup …
> JENKINS-46156 Only attempt to stop a run once when the user clicks the stop link

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/model/BbServerProject.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/model/BbServerUser.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketApiTest.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerScmTest.java
- blueocean-bitbucket-pipeline/src/test/resources/api/server/__files/body-_vivek-repos-ah0x0.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-_vivek-repos-ah0x0.json
Adds support for Bitbucket server personal repos. Personal repos are repos outside projects, created in user's personal account. Its bit obscure to find how to create personal repos, but you can do that from `View Profile=>Create Repository`.
See [JENKINS-46458](https://issues.jenkins-ci.org/browse/JENKINS-46458).
> JENKINS-46458# Add support for Bitbucket Server personal repos

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListener.java
[JENKINS-46452](https://issues.jenkins-ci.org/browse/JENKINS-46452) reports null pointer exceptions which cause build failures if the Jira plugin is configured without credentials.
I use the Jira plugin to rewrite bug report URL's, but do not want it to submit updates to the bugs.  This change should allow my use model to work again.
My apologies that I have not written a test for the bug.  I'm OK if you reject this change in favor of a change which includes a test that shows the failure.
My apologies that I don't have a reliable set of steps to duplicate the problem.  I suspect that the steps would include something like:
- Build the docker image from [my lts-with-plugins branch](https://github.com/MarkEWaite/docker-lfs/tree/lts-with-plugins)
- Execute the jobs in the "Bugs - Individual …
> [JENKINS-46452] Don't reference null Jira session

- jenkins-design-language/.eslintrc
- jenkins-design-language/src/js/components/index.js
- jenkins-design-language/src/js/components/pipeline/PipelineGraph.jsx
- jenkins-design-language/src/js/components/pipeline/PipelineGraphLayout.jsx
- jenkins-design-language/src/js/components/pipeline/PipelineGraphModel.jsx
- jenkins-design-language/src/js/stories/PipelineGraphStories.jsx
- jenkins-design-language/test/js/components/PipelineGraph-spec.js
Squashed commit of the following:
hackweek/complex-graphs * Add a comprehensive test-case for the layout algorithm to ensure we don't break it during modifications
hackweek/complex-graphs * Update existing test to use new interface to layout
hackweek/complex-graphs * Flow and eslint fixes
hackweek/complex-graphs * Move ypStart into the Layout object and remove the old busted constructor usecase from storybooks
hackweek/complex-graphs * Extract layout into a single-entry function in separate file for reuse
hackweek/complex-graphs * Move pipeline graph components into their own subdir, extract types into a model file
See [JENKINS-38442](https://issues.jenkins-ci.org/browse/JENKINS-38442).
> JENKINS-38442 Extract layout logic from PipelineGraph into separate function + Unit Tests

- blueocean-web/pom.xml
- pom.xml
There was a metrics dependency that @rsandell complained about. Turns out its not needed.
PTAL
> Remove the metrics dependency

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmSaveFileRequest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/HttpRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmContentProviderTest.java
- blueocean-github-pipeline/src/test/resources/api/__files/body-branches-master-BELLU.json
>Cherry picked from master, https://github.com/jenkinsci/blueocean-plugin/pull/1381. Compared to the changes on master for this issue, this PR has minor adjustment in test as release/1.2 branch supports org folder for GitHub.
See [JENKINS-46704](https://issues.jenkins-ci.org/browse/JENKINS-46704).
> JENKINS-46704# Fix for save content to new branch on github

- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/factory/BlueIssueFactory.java
See https://issues.jenkins-ci.org/browse/JENKINS-46778
There have been issues since JIRA has been bundled. This is an attempt to be generically defensive against issue tracking plugins that may poop on things. 
please consider @vivek @kzantow
> defensive code - for issue trackers that like to blow up with NPEs

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/ScmResourceImpl.java
Ported handling of permission check for org folder during loading content. 1.3 doesn't support creation of org folder pipeline but we  need this fix for backward compatibility.
See [JENKINS-46879](https://issues.jenkins-ci.org/browse/JENKINS-46879).
> JENKINS-46879# Pipeline could be an org folder, handle it accordingly

- jenkins-design-language/npm-shrinkwrap.json
- jenkins-design-language/package.json
- jenkins-design-language/src/js/components/ResultItem.jsx
- jenkins-design-language/src/js/stories/resultItemStories.jsx
Linkify URLs in ResultItem headers
See [JENKINS-46913](https://issues.jenkins-ci.org/browse/JENKINS-46913).
> feature/JENKINS-46913-result-item-links * Linkify URLs in ResultItem headers

- jenkins-design-language/src/js/components/status/StatusIndicator.jsx
Can be seen in any creation flow. When using the keybaord to navigate in the create flow if you tab from an input field you get nothing and then tab again and you get the next element in the focus.
Basically you need to shift-tab or tab twice to move between the control elements when a statusIndicator is in between since it will "steal" the focus due the the svg not having focusable="false".
Happens in IE only, Edge is correct as is Chrome.
Testing needs to be done manually in an IE.
See [JENKINS-47032](https://issues.jenkins-ci.org/browse/JENKINS-47032).
All SVG need to have focusable="false" otherwise IE may give them focus even if they are not anymore in the DOM and your document.activeElement becomes null and TAB_INDEX starts at top level (either document or browser(!)).
>  [FIX JENKINS-47032] IE will give focus to StatusIndicator in creation flow

- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
See: https://issues.jenkins-ci.org/browse/JENKINS-47080
https://dequeuniversity.com/rules/axe/2.4/html-has-lang?application=AxeChrome
> The HTML document must contain a valid lang attribute or must correspond to a valid lang code for multilingual screen reader users who may prefer a language other than the default.
I did run an analysis with https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd and our `lang` needs to appear in the parent `html`tag.
> <html> element must have a lang attribute

- blueocean-events/src/main/java/io/jenkins/blueocean/events/BlueMessageEnricher.java
This changes fixes an issue I've seen come up:
- When large numbers of triggers are run at once, the getBuilds call in getRun is extremely expensive.  It effectively ends up loading all the builds for a certain job.
- This causes delays of sometimes several hours in scheduling jobs when load is high.
- NPE when queued items can't be found in the queue.  This tends to happen more on startup.  It may simply be a race between the lookup code and the scheduling code.
The reason for removing this code is basically like this.  When a queue item that is blocked, waiting, etc. passes through here, the codepath appears to always return null.  This is becuase the queue item has not yet become a build and thus there is no entry in the job's build list.  The one I've found case where this does work …
> [JENKINS-47146,JENKINS-45589] Remove expensive fallback path for expected build number and NPE

- blueocean-dashboard/src/main/less/pipeline-run-graph.less
- was not necessary to fix JENKINS-43201 which was a bug report about
missing x scrolling
- chances of getting lost just because the stage labels are scrolled
out of view seem rather small (some visual cues on the left/right
side of the container could help)
- fixed PgUp/PgDown for default focus (nested scrollbar needs to be clicked first)
See [JENKINS-43201](https://issues.jenkins-ci.org/browse/JENKINS-43201).
Seems like there are not frontend style tests.
Example page https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fci/detail/PR-76/1/pipeline/190/. You can use the browser inspector to see the effect of this change.
> avoid second scrollbar in pipeline graph

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-jira/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean/pom.xml
- pom.xml
See [JENKINS-47357](https://issues.jenkins-ci.org/browse/JENKINS-47357).
This regression happened when we started depending on `apache-httpcomponents-client-4-api`. Main purpose of this was to load one set of httpcomponents library that all plugins use. Unfortunately upsrtream plugins (git, git-client, jira, blueocean-display-url etc.) depend directly on httpcomponents libs and this causes classes from it to be loaded anyways causing linkage error. To fix it I tried excluding httpcompoents libraries from different components but it simply doesn't work. These gets sucked in anyways.
For now, I am reverting dependence on `apache-httpcomponents-client-4-api` till all upstream libs are fixed to use it. Until then we are depending on httpcomponents directly. Lets see our tests pass and I will …
> JENKINS-47357# Fix for linkage error during bitbucket pipeline save

- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
port from 1.3
https://issues.jenkins-ci.org/browse/JENKINS-47310
> [FIX JENKINS-47310] Handle various cases of credential errors when loading the editor 

- blueocean-pipeline-editor/src/main/js/components/editor/EditorMain.jsx
- blueocean-pipeline-editor/src/main/js/services/PipelineStore.js
Removes "Name Parallel Group" dialog. To test: create a parallel group. Needs more tests in this area.
See [JENKINS-47249](https://issues.jenkins-ci.org/browse/JENKINS-47249).
> [FIX JENKINS-47249] Remove name parallel group dialog (1.3 branch)

- blueocean-dashboard/src/main/js/creation/git/GitConnectStep.jsx
- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
- blueocean-pipeline-editor/src/main/js/GitUtils.js
- blueocean-pipeline-editor/src/main/js/PipelineEditorLink.jsx
Tweak to add text indicating saving using non-SSH is not supported. Needs more tests in this area.
See [JENKINS-47248](https://issues.jenkins-ci.org/browse/JENKINS-47248).
> [FIX JENKINS-47248] Add warning / message that saving Jenkinsfiles without SSH is unsupported (1.3 branch)

- blueocean-dashboard/src/main/js/creation/bitbucket/server/BbAddServerDialog.jsx
- blueocean-dashboard/src/main/js/creation/github-enterprise/GHEAddServerDialog.jsx
Enter key does not submit form in the add server dialog for GitHub Enterprise and BitBucket Server
See [JENKINS-46388](https://issues.jenkins-ci.org/browse/JENKINS-46388).
> JENKINS-46388 Enter key does not submit form in the add server dialog

- blueocean-dashboard/src/main/js/components/karaoke/components/FreeStyle.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStylePipeline.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueItemImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueUtil.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueuedFreeStyleRun.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/KnownCapabilities.java
* Pipeline.jsx should never shortcut to the QueuedState message when the run is queued. This should only happen for freestyle jobs. This is why the Pipeline graph would flicker as the Pipeline changed nodes. 
* QueuedRun needs to smell like a FreeStyleBuild when its parent is FreeStyleProject otherwise Pipeline.jsx will be used instead of FreeStyle.jsx. This leads to the Queued freestyle run occasionally having a blank screen.
See [JENKINS-46335](https://issues.jenkins-ci.org/browse/JENKINS-46335).
1. Run the app store demo project
2. Notice how there is no flickering of the pipeline visualization
1. Disable all executors
2. Run the app store demo project
3. You should see the graph and the queued message where the steps should be
4. Enable all executors
5. The pipeline should finish
1. …
> JENKINS-46335 Pipeline graph flickers

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScm.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScmContentProvider.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketApi.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketApiFactory.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/HttpRequest.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/HttpResponse.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudApi.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketWireMockBase.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BbCloudPipelineCreateRequestTest.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudScmContentProviderTest.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudScmTest.java
Adds HTTP proxy support. To simplify code, moved away from fluent http library.
I have tested bitbucket pipeline creation and editing for both bitbucket cloud and server.
See [JENKINS-47054](https://issues.jenkins-ci.org/browse/JENKINS-47054).
> JENKINS-47054# Bitbucket api access via http proxy

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlObjectImpl.java
Computation of mapped url involves creating blueocean pipeline object graph (Note: the object graph gets created lazily as well). It can potential cause performance issues as access to transient actions resulting in calling `TryBlueOceanMenu.createFor(ModelOjbect target)` and that computes url eagerly. See See [JENKINS-47509](https://issues.jenkins-ci.org/browse/JENKINS-47509) for details.
Fix is made to initialize mapped url lazily. That is only when `BlueOceanUrlAction.getUrlName()` is called. It happens during rendering and to avoid duplicates.
cc: @svanoort 
See [JENKINS-47509](https://issues.jenkins-ci.org/browse/JENKINS-47509).
> JENKINS-47509# Initialize mapped URL lazily

- blueocean-core-js/src/js/analytics/AnalyticsService.js
Erroneously sending the properties parameter as a string.
`{"name":"pageview","properties":{"properties":{"mode":"blueocean"}}}`
Should now be:
`{"name":"pageview","properties":{"mode":"blueocean"}}`
See [JENKINS-47735](https://issues.jenkins-ci.org/browse/JENKINS-47735).
> Properies object not being passed when track() sent

- blueocean-dashboard/src/main/js/components/karaoke/components/LogConsole.jsx
Note: This PR is best viewed with [?w=1](https://github.com/jenkinsci/blueocean-plugin/pull/1521/files?w=1)
When the following component receives new log rows: 
Currently when new logs are received for a given step, it forces an entire re-render of the LogConsole component's children. Unfortunately on a rather large build, this becomes quite laggy.
This PR updates the LogLine to be a PureComponent to avoid un-needed re-renders of previously rendered console lines.
- No ticket was created for this, let me know if this is an issue
- This is a performance tweak, all functionality should remain the same
- Ensure that the pipeline detail view renders as before. Note, I tested this commit on top of  the 1.3 release branch, and it worked as expected. I have rebased this PR onto of master now, so …
> Performance improvements for LogConsole component

- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
- blueocean-dashboard/src/main/js/util/logDisplayHelper.js
- blueocean-dashboard/src/test/js/pipeline-graph-converter-spec.js
- blueocean-dashboard/src/test/json/pipeline-graph-converter/ends-with-parallel.json
- blueocean-dashboard/src/test/json/pipeline-graph-converter/pipeline-nodes-example.json
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/FlowNodeWrapper.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/testDynamicInnerStage.jenkinsfile
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineNode.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineStep.java
- jenkins-design-language/src/js/components/pipeline/PipelineGraphLayout.jsx
- jenkins-design-language/test/js/components/PipelineGraph-spec.js
Existing karaoke/JDL(PipelineGraph) treats parallel branches if number of edges > 1. Visualization breaks down if there is just one parallel branch.
To fix it, I am introducing new element type to `BluePipelineStep` and `BluePipelineNode.Edge`. Front end uses type to detect whether a node is stage or parallel.
For given pipeline script:
```
node {
stage('test' ) {
println('pre parallel step')
}
stage('parallel stage') { 
def array = ["a_1"]
def builds = [:]
array.each {
test = it
builds[it] = {
node {
stage (it) {
println(it)   
sh 'date'
}
}
}
}
parallel builds
}    
stage('test2') {
println('post parallel step')
}
}
```
##Existing rendering
See [JENKINS-46490](https://issues.jenkins-ci.org/browse/JENKINS-46490).
> JENKINS-46490# Fix graph visualization for single parallel branch

- blueocean-dashboard/src/test/js/activity-spec.js
This is just fixing a test that was failing for an unknown reason (which should be fixed now).
See [JENKINS-47774](https://issues.jenkins-ci.org/browse/JENKINS-47774).
> [FIX JENKINS-47774] Re-enable activity-spec test

- acceptance-tests/README.md
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/creation/GitCreationTest.java
See [JENKINS-47749](https://issues.jenkins-ci.org/browse/JENKINS-47749). This PR is for the addition of a Pipeline Editor test which creates a Parallel pipeline, in support of the parallel syntax introduced with [Declarative 1.2](https://wiki.jenkins.io/display/JENKINS/Pipeline+Model+Definition+Plugin). This PR also includes some small README edits.
1. Follow the instructions provided in [the acceptance tests' README](https://github.com/kshultzCB/blueocean-plugin/tree/add-parallel-editor-test/acceptance-tests) for setting up the "live" acceptance tests
2. Invoke `mvn test -Dprofile=live -Dtest=GithubEditorTest#testEditorParallel`
@kzantow , @imeredith , a review would be most appreciated.
> JENKINS-47749 Add editor test for creating a parallelized pipeline

- blueocean-dashboard/src/main/js/components/testing/TestDetails.jsx
- blueocean-dashboard/src/main/less/testing.less
This problem happened only for logs (the pipeline logs wrap fine).
Given the fact that this change is only css plus and extra container, I do not think any test is necessary, I will add a print-screen showing the fix in action
See [JENKINS-47513](https://issues.jenkins-ci.org/browse/JENKINS-47513).
> JENKINS-47513 allow test logs to wrap properly

- blueocean-core-js/src/less/run-button.less
- blueocean-personalization/src/main/less/pipeline-card.less
- jenkins-design-language/less/components/expandable-path.less
The run button colour on the favourites card was overwritten in https://github.com/jenkinsci/blueocean-plugin/pull/1539
> fix favourites run button colour that was broken in #1539

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/HttpRequest.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketApiTest.java
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-redirect-test.json
See [JENKINS-47984](https://issues.jenkins-ci.org/browse/JENKINS-47984).
Auto redirection was disabled but had a bug which is fixed. Now API redirection is disabled for Bitbucket.
If user adds BB server endpoint URL or uses one previously added that results in redirection an error will be displayed. See images below:
> JENKINS-47984# Disable Bitbucket server auto-redirect handling

- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmContentProvider.java
Trying to use the editor with GitHub on IE11 gave an _InvalidCharacterError_. BitBucket and Git were unaffected by this. Test is covered sufficiently by standard ATH pipeline editor tests.
See [JENKINS-47887](https://issues.jenkins-ci.org/browse/JENKINS-47887).
> [FIX JENKINS-47887] unable to use pipeline editor with GitHub on IE 11

- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
- blueocean-pipeline-editor/src/main/js/components/editor/AddStepSelectionSheet.jsx
This PR includes two main things.
1. Conversion to `wait.click()`, instead of `wait.until(things).click()`, to hopefully de-flake these tests. `wait.click` has which has retry behavior and an initial check for `elementIsClickable`, built into it. Inspired by [PR 1544](https://github.com/jenkinsci/blueocean-plugin/pull/1544).
2. Addition of `data-functionName={step.functionName}` in the pulldown for creating a step in the editor. This, hopefully, provides a more stable selector for the tests to look for. It matches up nicely to the step which will be created in the Jenkinsfile - e.g., "Shell Script" matches up to `sh`.
- Follow the instructions provided in [the acceptance tests' README](https://github.com/kshultzCB/blueocean-plugin/tree/add-parallel-editor-test/acceptance-tests) for …
> GithubEditorTest using wait.click, more stable selector in editor step pulldown

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/TryBlueOceanMenu.java
I'm unsure of how to replicate this but I'm pretty sure I know what was going on. I think the `exists` method was bugged, which meant `replaceActions` was updating the one that existed, and then we were returning one more from `createFor`.
I've changed it to remove any links if `exists` doesn't` find one. I'm not sure if this is needed, but it works fin
See [JENKINS-45476](https://issues.jenkins-ci.org/browse/JENKINS-45476).
> [JENKINS-45476] Only insert one blueocean link

- jenkins-design-language/less/components/expandable-path.less
Fix expandable-path folder icon color in the contentPageHeader
> fix expandable-path folder icon color in the contentPageHeader

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/UserImplPermissionTest.java
See [JENKINS-48285](https://issues.jenkins-ci.org/browse/JENKINS-48285).
So this change ([PR ](https://github.com/jenkinsci/jenkins/pull/2999)- [JENKINS-46610](https://issues.jenkins-ci.org/browse/JENKINS-46610)) moved all the hasPermission methods from several classes to a default method in the interface. In the test the method wasn't mocked because it was final and we didn't need to. Not the method is not final so it needs to be mocked.
I had to relay in a hackish check because pre 2.77 will fail the mock given that the method is final. 
@reviewbybees
> [JENKINS-48285] - Make UserImplPermissionTest work with >= 2.77 cores

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- pom.xml
See [JENKINS-47339](https://issues.jenkins-ci.org/browse/JENKINS-47339).
Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/187
This allows Item.BUILD or the new ReplayAction.REBUILD permission to
be used for determining whether rebuilding a build with the exact same
script is allowed.
To test, create a Pipeline job and run it. Then, login as a user with `Item.BUILD` permission but *not* `Item.CONFIGURE`. Replaying should be possible from Blue Ocean.
> [JENKINS-47339] Switch to ReplayAction.isRebuildEnabled()

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
See [JENKINS-47158](https://issues.jenkins-ci.org/browse/JENKINS-47158).
This is just a bandaid - as discussed on JENKINS-47158, the usage of
synthetic `FlowNode`s for visualization-only purposes is not
ideal. But at a minimum, this prevents the serialization of the
synthetic `FlowNode`s, making JENKINS-45892 warnings go away, and not,
well, serializing a bunch of stuff we almost certainly shouldn't be.
No manual testing really needed here, but if you want, run on core 2.75 or later, use a parallel Pipeline like [the one specified in this JIRA comment](https://issues.jenkins-ci.org/browse/JENKINS-47158?focusedCommentId=316531&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-316531), and make sure you don't see anything about JENKINS-45892 in the Jenkins log. …
> [JENKINS-47158] Ensure that synthetic FlowNode is not saved.

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
A cherry pick from master of https://github.com/jenkinsci/blueocean-plugin/pull/1584
* [JENKINS-47158] Ensure that synthetic FlowNode is not saved.
This is just a bandaid - as discussed on JENKINS-47158, the usage of
synthetic `FlowNode`s for visualization-only purposes is not
ideal. But at a minimum, this prevents the serialization of the
synthetic `FlowNode`s, making JENKINS-45892 warnings go away, and not,
well, serializing a bunch of stuff we almost certainly shouldn't be.
* Add note as to why we're not saving.
> release 1.3: [JENKINS-47158] Ensure that synthetic FlowNode is not saved. (#1584)

- docker/official/build.sh
This reverts commit 0acb925d2d6458ede2d8e31348503191a639c951.
Signing appears to require a persistent key to be created in our infrastructure
which does not presently exist:
Signing and pushing trust metadata
You are about to create a new root signing key passphrase. This passphrase
will be used to protect the most sensitive key in your signing system. Please
choose a long, complex passphrase and be careful to keep the password and the
key file itself secure and backed up. It is highly recommended that you use a
password manager to generate the passphrase and keep it safe. There will be no
way to recover this key. You can find the key in your config directory.
Enter passphrase for new root key with ID 66e9aff:
Enter passphrase for new root key with ID 66e9aff:
Enter passphrase for new …
> Revert "sign images we push to dockerhub"

- blueocean-events/src/main/java/io/jenkins/blueocean/events/BlueMessageEnricher.java
https://issues.jenkins-ci.org/browse/JENKINS-48587
hey @vivek @svanoort this is to handle random failures at enriching (which happens during listening).
> Harden message enricher

- acceptance-tests/pom.xml
- blueocean-config/package.json
- blueocean-core-js/gulpfile.js
- blueocean-core-js/package.json
- blueocean-dashboard/package.json
- blueocean-personalization/package.json
- blueocean-pipeline-editor/package.json
- blueocean-web/package.json
- jenkins-design-language/gulpfile.js
- jenkins-design-language/package.json
- pom.xml
Bringing back the PR with @cliffmeyers's proposed gulp and lifecycle changes. We tried this but it failed to deploy on release:prepare stage: 
```
[INFO] [04:43:33] Error: EEXIST: file already exists, mkdir '/jenkins/workspace/blueocean-release/jenkins-design-language/dist/js'
[INFO]     at Error (native)
```
> Hotfix release:perform

- acceptance-tests/src/main/java/io/blueocean/ath/model/MultiBranchPipeline.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
See [JENKINS-48378](https://issues.jenkins-ci.org/browse/JENKINS-48378). This PR includes:
1. Conversion of `wait.until` calls into `wait.click()` calls, to hopefully help de-flake these tests
2. Creation of the test Pipelines has been moved out of the test cases themselves, and into a `@Before` method called `setupPipelines()`.
3. Removal of the test Pipelines is now part of the test, and is in an `@AfterClass` method called `deleteTestPipelines()`.
4. `deleteTestPipelines()` calls a new method, `io.blueocean.ath.model.MultiBranchPipeline#deleteThisPipeline`, which deletes the pipeline specified by the caller, by use of `jobApi.deletePipeline(name)`. 
1. Follow the instructions provided in t[he acceptance tests' README](https://github.com/jenkinsci/blueocean-plugin/blob/master/acceptance- …
> JENKINS-48378 Add stability / consistency to ParallelNavigationTest.java

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlObjectImpl.java
BlueOceanUrlObjectImpl unintentionally references ModelObject as non-transient resulting in to replaceIfNotAtTopLevel warning. See https://issues.jenkins-ci.org/browse/JENKINS-45892.
See [JENKINS-48322](https://issues.jenkins-ci.org/browse/JENKINS-48322).
> JENKINS-48322# Fix replaceIfNotAtTopLevel warning

- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveService.java
Git creation flow checks for overall read permission in getContent() API call. It should really be checking that Item's READ permission instead.
cc: @daniel-beck @kzantow 
See [JENKINS-48219](https://issues.jenkins-ci.org/browse/JENKINS-48219).
> JENKINS-48219# When creating git pipeline check Item.READ permission instead of overall READ permission

- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
A suddenly failing test seems related to timing - can only sometimes see it locally. Trying a thing
> add a retry and cleanup between runs

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlObjectImpl.java
ModelObject was serialized in prior version (1.4.0-beta4 and older), it was removed as part of fix that went in PR #1609. This caused error reported in OldData. Fix is to simply put back unused ModelObject as transient. 
@michaelneale @jglick Do not like this fix, is there better ways other plugins handle it? On the other hand, we could mark this issue as will not fix as 'Discard Unreadable Data' is just fine. Just that it will surprise anyone upgrading to 1.4.0 and we might want to port #1609 to 1.3.0.
See [JENKINS-48872](https://issues.jenkins-ci.org/browse/JENKINS-48872).
> JENKINS-48872# Fix deserialization error for missing ModelObject field

- blueocean-dashboard/src/main/js/components/PullRequests.jsx
Found some obsolete code that caused the render function to "return null" once every time when getting the next items before re-rendering
See [JENKINS-47460](https://issues.jenkins-ci.org/browse/JENKINS-47460).
> Remove obsolete code that caused the PR tab to refresh when pressing "Show More"

- blueocean-dashboard/src/main/less/core.less
Log lines would not break if there were no breakable characters (i.e. space char) and instead expand out. This PR just sets a max-width to the log lines so they cannot expand more than their container.
See [JENKINS-49036](https://issues.jenkins-ci.org/browse/JENKINS-49036).
> JENKINS-49036 don't allow log lines to expand bigger than their container

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeUtil.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeUtilTest.java
See [JENKINS-49028](https://issues.jenkins-ci.org/browse/JENKINS-49028).
As per my comments in the Jira. I've been unable to generate an appropriate unit test for this issue. PipeLineNodeUtils does not seem to have its own independent unit tests. The fix is for an obvious NPE due to a null dereference.
> Fix JENKINS-49028 null protect call to getShortDescription()

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ExportInterceptor.java
* Add logging when a property is skipped during JSON marshalling due to an exception
See [JENKINS-48198](https://issues.jenkins-ci.org/browse/JENKINS-48198).
> JENKINS-48198 - Add logging when a property is skipped

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
Refactor react-router related code of what happens when run details closes so the back/forward browser buttons behave naturally
See [JENKINS-47952](https://issues.jenkins-ci.org/browse/JENKINS-47952).
> JENKINS-47952 Back browser button behaviour is broken when closing run details screen

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketPipelineCreateRequest.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketPipelineCreateRequestTest.java
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitPipelineCreateRequest.java
- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitPipelineCreateRequestTest.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
Any Pipeline created with blue ocean should checkout to the local branch rather than leaving the checkout in detached head state.
See [JENKINS-49419](https://issues.jenkins-ci.org/browse/JENKINS-49419).
> JENKINS-49419 Avoid detached head on checkout

- jenkins-design-language/src/js/components/forms/Dropdown.jsx
This uses the proprietary IE setActive method to restore focus to the dropdown button element after applying the selection
See [JENKINS-47022](https://issues.jenkins-ci.org/browse/JENKINS-47022).
> JENKINS-47022 - Fix for IE dropdown losing focus on selection

- jenkins-design-language/src/js/components/forms/Dropdown.jsx
- jenkins-design-language/test/js/components/Dropdown-spec.jsx
This forces the dropdown to regain focus after a selection, still working on adding a unit test for this
See [JENKINS-47022](https://issues.jenkins-ci.org/browse/JENKINS-47022).
> JENKINS-47022 - Fix for dropdown losing focus on selection

- jenkins-design-language/package.json
- jenkins-design-language/src/js/components/forms/Dropdown.jsx
- jenkins-design-language/test/js/components/Dropdown-spec.jsx
Backport of #1652 and #1654 to `release/1.4`.
See [JENKINS-47022](https://issues.jenkins-ci.org/browse/JENKINS-47022).
> JENKINS-47022 - Fix for dropdown losing focus on selection, back port to 1.4

- blueocean-dashboard/src/main/js/components/Pipelines.jsx
- blueocean-dashboard/src/main/less/core.less
This fixes fastsearch stealing focus from other input tags. It will also only steal focus when no modal window is active. Also fixes fastsearch clear icon color.
See [JENKINS-49298](https://issues.jenkins-ci.org/browse/JENKINS-49298).
> JENKINS-49298 fastsearch steals focus on "t" key

- blueocean-events/src/main/java/io/jenkins/blueocean/events/PipelineEventListener.java
- blueocean-events/src/test/java/io/jenkins/blueocean/events/PipelineEventListenerTest.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/FlowNodeWrapper.java
Fix for  stack overflow error during pipeline execution SSE event generation, has other minor improvements.
See [JENKINS-48820](https://issues.jenkins-ci.org/browse/JENKINS-48820).
> JENKINS-48820# Fix for stack overflow in flownode sse event generation

- blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/Export.java
Hide BlueOceanExportInterceptor so Javadoc can ignore .export package
> Hide BlueOceanExportInterceptor so Javadoc can ignore .export package

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketApiTest.java
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-branches-default-5.6.0.json
See [JENKINS-49756](https://issues.jenkins-ci.org/browse/JENKINS-49756).
For empty repo we are expecting HTTP status 404 but getting 204 when we call default branch API. This change of 204 instead of 404 was introduced in  BB server 5.6.0, https://jira.atlassian.com/browse/BSERV-10313.
> JENKINS-49756# Fix for BB server defult branch API in bb server >= 5.6.0

- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitBareRepoReadSaveRequest.java
- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
This commit sets the defailt email for git commits from the pipeline editor
to jenkinsUsername@email-address-not-set.
See [JENKINS-48274](https://issues.jenkins-ci.org/browse/JENKINS-48274).
> [JENKINS-48274] Set default email for git commit

- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Step.jsx
- blueocean-dashboard/src/main/js/components/karaoke/services/Augmenter.js
See [JENKINS-49929](https://issues.jenkins-ci.org/browse/JENKINS-49929).
> JENKINS-49929 Regression: Log fails to auto update in karaoke mode

- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/creation/GitCreationTest.java
- blueocean-dashboard/src/main/js/creation/github/api/mocks/repos-1.js
- blueocean-dashboard/src/main/js/creation/github/api/mocks/repos-2.js
- blueocean-dashboard/src/main/js/creation/github/api/mocks/repos-3.js
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GHRepoEx.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrganization.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubRepositories.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubRepositoryContainer.java
- blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubUserOrganization.java
- blueocean-rest/README.md
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`
Split from #1664
Note this includes an API change.
At present, it doesn't include the API shim.
I'm not entirely certain what the consequences of omitting such a shim are, but...
> Spelling repository

- Jenkinsfile
- acceptance-tests/src/main/java/io/blueocean/ath/WaitUtil.java
See [JENKINS-50436](https://issues.jenkins-ci.org/browse/JENKINS-50436). It might be useful to have Jacoco HTML reports available after each build in CI, not just the failed builds. Since master is usually green, it's not common to see
> Move jacoco HTML archiving so it runs all the time in CI

- blueocean/pom.xml
- pom.xml
Till we have fixed jira-plugin, possibly without dependency on atlassian
libraries, lets disable and stop distributing blueocean-jira plugin.
Side effect of this removal will be that JIRA issues from commit message
wont have link to JIRA. Given the trouble its causing in deployments to
user, its worth disabling at this point.
See [JENKINS-48357](https://issues.jenkins-ci.org/browse/JENKINS-48357).
> JENKINS-48357# Fix jira-plugin binary compatibility issue

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
This change stops stepping out of karaoke mode if scrolling up or 'key up' is pressed when run is paused
I don't think this can or should be tested
See [JENKINS-49455](https://issues.jenkins-ci.org/browse/JENKINS-49455) [JENKINS-45486](https://issues.jenkins-ci.org/browse/JENKINS-45486).
> JENKINS-49455 & JENKINS-45486 don't step out of karaoke mode when scrolling up if run is paused

- blueocean/pom.xml
- pom.xml
Its causing other integration hassles and given that in short term we are going to have help on fixing jira-plugin, lets keep the status quo and ship blueocean-jira with jira-plugin version that works.
Reverts jenkinsci/blueocean-plugin#1704
> Revert "JENKINS-48357# Fix jira-plugin binary compatibility issue"

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-jira/pom.xml
- blueocean-rest-impl/pom.xml
- pom.xml
Fix for LinkageError.
```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.apache.http.entity.mime.MultipartEntityBuilder.build()Lorg/apache/http/HttpEntity;" the class loader (instance of hudson/ClassicPluginStrategy$AntClassLoader2) of the current class, io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi, and the class loader (instance of hudson/ClassicPluginStrategy$AntClassLoader2) for the method's defining class, org/apache/http/entity/mime/MultipartEntityBuilder, have different Class objects for the type org/apache/http/HttpEntity used in the signature
```
This was happening because different versions of httpmime.jar was loaded by git-client, jira-plugin and blueocean. Fix is to make sure apache http libs are the …
> JENKINS-50572# Fix for Bitbucket save content fails with LinkageError

- acceptance-tests/src/test/java/io/blueocean/ath/offline/BitbucketServerTest.java
See [JENKINS-50779](https://issues.jenkins-ci.org/browse/JENKINS-50779). This test is failing on an inconsistent basis, and adding a `@Retry(3)` seems a logical first step toward addressing that. We're already using `@Retry(3)` in many other create tests, both offline and live:
- In [`live/GithubCreationTest`](https://github.com/jenkinsci/blueocean-plugin/blob/master/acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java):
- [`testCreatePipelineFull`](https://github.com/jenkinsci/blueocean-plugin/blob/master/acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java#L119)
- [`testCreatePullRequest`](https://github.com/jenkinsci/blueocean-plugin/blob/master/acceptance-tests/src/test/java/io/blueocean/ath/live/GithubCreationTest.java#L142)
- …
> JENKINS-50779: Add @Retry(3) to BitbucketServerTest#testCreationNoJenkinsfile

- acceptance-tests/src/main/java/io/blueocean/ath/model/AbstractPipeline.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/BranchPage.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/CommitMessagesTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/StartStopTest.java
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/StartStopTest/Jenkinsfile
See [JENKINS-50829](https://issues.jenkins-ci.org/browse/JENKINS-50829). This PR adds a test which starts, and then stops, two branches in a multibranch pipeline. A Jenkinsfile for use with this test is included.
Also included: 
- A simplification to `EditorPage.AddStageToPipeline`. This simplification removes the redundant branch saving logic which was in it previously. The calling `GithubEditorTest#testEditorAddStages()` now uses `EditorPage.saveBranch` to maintain the flow of the test.
- Minor spelling correction in `CommitMessagesTest`
To test: 
- Start up the acceptance tests in your preferred way. 
- Run `mvn test -Dtest=StartStopTest`
> JENKINS-50829: ATH for stopping running jobs, plus simplified EditorPage code

- jenkins-design-language/less/components/result-status.less
- jenkins-design-language/src/js/components/pipeline/PipelineGraph.jsx
Changes the pipeline selection highlight as requested in JENKINS-50408
See [JENKINS-50408](https://issues.jenkins-ci.org/browse/JENKINS-50408).
> JENKINS-50408 change the pipeline selection highlight

- blueocean-core-js/src/js/components/BlueLogo.jsx
- blueocean-core-js/src/js/components/ContentPageHeader.jsx
See [JENKINS-49991](https://issues.jenkins-ci.org/browse/JENKINS-49991).
- UX fix, no logic changes or new features
1. Go to a page in Blue Ocean other than the home page (e.g. Create New Pipeline)
1. Click the "Jenkins" link in the top left to return to the home page
1. Verify that the app has returned to the Blue Ocean home page
1. Verify that no full page refresh was performed
> [FIXED JENKINS-49991] Link to home should not full refresh

- blueocean-core-js/gulpfile.js
This copies the lint code from js-builder. This needed to be done because of the typescript change that transpiled to target/tstemp. JS Builder src config needed to point to target/tstemp/index.js to run browserify, unfortunately js-builder also uses that src config for linting.
> Fix Linting in core-js

- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
- blueocean-pipeline-editor/src/main/js/components/editor/EditorPipelineGraph.jsx
See [JENKINS-51346](https://issues.jenkins-ci.org/browse/JENKINS-51346). 
In [PR 1733](https://github.com/jenkinsci/blueocean-plugin/pull/1733), I added an `id` to allow for easier targeting of stages by ATH tests. What I didn't think about was the fact that spaces aren't supposed to be in `id`s. And we want to be able to target stage names that include spaces from the tests, without any additional string manipulation tricks to remove the spaces on the JS side.
So, this PR gets rid of the id, and instead puts in a `data` tag. Of course, I changed the test to go along with.
There's one odd thing. I can't get the data tag to play nicely using camelcase. `data-stagename` works fine, but `data-stageName` never shows with the capital `N`. So I gave up on it and stuck with `data-stagename`.
> JENKINS-51346: Replace id with data tag for HTML5 compliance

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/htmlpublisher/HTMLArtifactTest.java
Blueocean test should not be testing url format, all we care is artifact
url is not null.
> CD-489# Test fix due to artifact url format change in htmlpublisher 1.16

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/ArtifactImplTest.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueArtifact.java
Description
-----------
Files which are the same _name_ are not shown as artifacts in the Blue Ocean UI.
It is possible for multiple files of the same name to be collected but under different artifact paths.  This change fixes a conflict of the unique ID field where artifacts with the same name but different paths should have a unique ID.  By having a unique ID, all artifacts will be shown in the Blue Ocean UI.
Compare the following discrepencies of artifacts being listed in these two URLs.
- https://build.gimp.org/job/gimp/job/master/117/ (complete artifact list)
- https://build.gimp.org/blue/organizations/jenkins/gimp/detail/master/117/artifacts (incomplete artifact list)
> **Note:** `test-suite.log` is a file with the same name collected under different paths.
See also:
- …
> [JENKINS-51533] Bugfix not showing all artifacts

- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
- blueocean-pipeline-editor/src/main/js/services/PipelineSyntaxConverter.js
- blueocean-pipeline-editor/src/main/resources/jenkins/plugins/blueocean/pipeline/editor/Messages.properties
This checks if the pipeline contains sequential parallel stages and in case it does it show an error explaining which stage contains them and that the editor currently does not support them.
See UX-728.
> Pipeline Editor - check if pipeline has sequential parallel stages and show error

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FavoriteContainerImpl.java
A follow-up from https://github.com/jenkinsci/jenkins/pull/3481: the only other code in @jenkinsci I could find which was calling this method. Ironically, you already knew about it since #1033 and had a workaround being used in `MultibranchPipelineRunContainer` and `Pageables`—just not `FavoriteContainerImpl`.
> [JENKINS-51779] Avoid com.google.common.collect.Iterators.skip

- Dockerfile.jdk10
See [JENKINS-52029](https://issues.jenkins-ci.org/browse/JENKINS-52029). The image is hosted on DockerHub as `jenkins/jenkins-experimental:blueocean-jdk10`
Base images:
* https://github.com/jenkinsci/jenkins/blob/java10-support/Dockerfile
* https://github.com/jenkinsci/docker/tree/java10
@reviewbybees @jenkinsci/java10-support
> [JENKINS-52029] - Create experimental BlueOcean image with JDK 10 support

- jenkins-design-language/package.json
- jenkins-design-language/src/js/components/forms/Dropdown.jsx
- jenkins-design-language/test/js/components/Dropdown-spec.jsx
See [JENKINS-51921](https://issues.jenkins-ci.org/browse/JENKINS-51921).
Prevent synthetic events to trigger onClick.
Some browser like FF and IE will fire an onClick event if you focus the dropDownButton in another event loop.
Base cause described in http://helephant.com/2008/01/16/focus-event-handler-run-in-different-order-in-ie-than-firefox/ more info https://allyjs.io/tests/event-sequence/table.html
> [JENKINS-51921] Prevent onClick of generated syntetic events in dropDown

- blueocean-dashboard/src/main/js/credentials/git/GitCredentialsPickerPassword.tsx
Replace the use of Object.values because it breaks the whole app in older versions of browsers
See [JENKINS-52130](https://issues.jenkins-ci.org/browse/JENKINS-52130).
> [JENKINS-52130] Replace Object.values because it doesn't work in older browsers

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlAction.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/TryBlueOceanMenu.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlActionTest.java
See [JENKINS-51627](https://issues.jenkins-ci.org/browse/JENKINS-51627).
Tidy up the code that prevents multiple "try blue" actions from showing.
The code attempted to make sure that only one "Try BlueOcean" action was shown butno one looked at the reason why multiple where shown.
The reason that multiple actions where shown was a bug in core that affected Queue.Items and their subclasses.  Given that almost all Queue.Items have no page of their own there is little point in creating an Action for them (and this solves the fact that they get persisted and then shown for a AbstractBuild.
In the case they are already persisted we just replace the action with an invisibleAction such that the only rendered "Try Blue" will be the one created afresh from the TransientActionFactory
NOtes to …
> [JENKINS-51627] the code was just plain wrong and ugly :)

- acceptance-tests/runner/scripts/start-selenium.sh
See [JENKINS-52494](https://issues.jenkins-ci.org/browse/JENKINS-52494). The idea here is to make a quick change to the Selenium container we use, which will being with it upgrades to Chrome, Chromedriver, and Selenium. This is probably better for test coverage anyway, but more to the point, I'd like to see if it helps with any of the flaky tests we've got.
I've seen this work in another ci setting, so I'm filing a temporary PR to watch it work on ci.blueocean.io.
> [JENKINS-52494] Upgrade selenium container to pick up newer chrome, selenium

- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
- blueocean-dashboard/src/main/js/components/karaoke/services/pagers/PipelinePager.js
- blueocean-dashboard/src/main/js/util/logDisplayHelper.js
- jenkins-design-language/src/js/components/pipeline/PipelineGraph.jsx
- jenkins-design-language/src/js/components/pipeline/PipelineGraphLayout.jsx
- jenkins-design-language/test/js/components/PipelineGraph-spec.js
This adds the ability to view sequential parallel stages in the PipelineGraph. [Here](https://github.com/NicuPascu/app-store-demo/blob/sequential_parallel_stages/Jenkinsfile) is an example Jenkinsfile that can be used for testing.
See [JENKINS-49050](https://issues.jenkins-ci.org/browse/JENKINS-49050).
> [JENKINS-49050] Add support for sequential parallel stages

- blueocean-dashboard/src/main/js/components/PipelineRunGraph.jsx
- blueocean-dashboard/src/main/js/components/karaoke/services/pagers/PipelinePager.js
This fixes the rendering of sequential parallel stages in some cases. Also fixes the selected stage in case the last nodes are sequential.
See [JENKINS-53048](https://issues.jenkins-ci.org/browse/JENKINS-53048).
> [JENKINS-53048] Fix rendering of sequential parallel stages

- blueocean-dashboard/src/main/js/components/testing/TestCaseResultRow.jsx
testCase.duration is in seconds, but we must pass milliseconds to TimeDuration.format().
See [JENKINS-52944](https://issues.jenkins-ci.org/browse/JENKINS-52944).
> [JENKINS-52944] Pass milliseconds to TimeDuration

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
See [JENKINS-53197](https://issues.jenkins-ci.org/browse/JENKINS-53197).
When Blue Ocean is built using a version of Jenkins core 1.25 or newer, [this test](https://github.com/jenkinsci/blueocean-plugin/blob/16d42cd0f6d08fedb0660ad6080ef2c8a2b1769e/blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java#L282) will fail. That's because [the `assertEquals` on L299](https://github.com/jenkinsci/blueocean-plugin/blob/16d42cd0f6d08fedb0660ad6080ef2c8a2b1769e/blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java#L299) is looking for the following string:
> Jenkins doesn’t have label test
But since [this commit to Jenkins core](https://github.com/jenkinsci/jenkins/commit/91ddc6fca78e09efe25ced0 …
> Allows pre- and post-2.125 versions of Jenkins core to pass

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
it will cause NPE when client not add `Accept` header
> remove unsued accept header

- blueocean-core-js/src/js/services/DefaultSSEHandler.js
This will stop the UI from becoming unresponsive if a run request returns a 404
See [JENKINS-53175](https://issues.jenkins-ci.org/browse/JENKINS-53175).
> [JENKINS-53175] avoid js throwing error in case a run request returns a 404

- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/HttpResponse.java
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerScmContentProviderTest.java
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/bitbucket_rest_api_10_projects_proj_repos_with-jenkinsfile_browse_jenkinsfile-7269cd83-1af6-4134-9161-82360d678dcc.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/bitbucket_rest_api_10_projects_testp_repos_pipeline-demo-test_browse_somefile-7269cd83-1af6-4134-9161-82360d678dcc.json
- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
Show BitBucket server errors better in some cases, for example attempting to save a Jenkinsfile through the pipeline editor, some errors would return an error code, empty status line and error object, which would not give any information to the end user.
For example:
> BitBucket Server errors not shown properly

- pom.xml
This PR updates pipeline plugins to their latest released versions (CC @abayer I also bumped declarative to 1.3.2 since I was here already), so that we can run the Blue Ocean test suite against the latest version of everything. It doesn't matter to me whether we merge this or not, I am mostly just interested in the CI build's test results, so please feel free to add a DO-NOT-MERGE label or whatever makes sense.
@reviewbybees
> Update pipeline-related plugins to the latest versions for testing

- Jenkinsfile
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/BitbucketServerTest.java
- blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/HttpResponse.java
- blueocean-bitbucket-pipeline/src/main/resources/io/jenkins/blueocean/blueocean_bitbucket_pipeline/Messages_zh_CN.properties
- blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerScmContentProviderTest.java
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/bitbucket_rest_api_10_projects_proj_repos_with-jenkinsfile_browse_jenkinsfile-7269cd83-1af6-4134-9161-82360d678dcc.json
- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/bitbucket_rest_api_10_projects_testp_repos_pipeline-demo-test_browse_somefile-7269cd83-1af6-4134-9161-82360d678dcc.json
- blueocean-core-js/src/js/services/DefaultSSEHandler.js
- blueocean-dashboard/src/main/js/components/karaoke/components/LogConsole.jsx
- blueocean-dashboard/src/main/js/components/testing/TestCaseResultRow.jsx
- blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages_zh.properties
- blueocean-personalization/src/main/resources/jenkins/plugins/blueocean/personalization/Messages_zh.properties
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/NodeRunStatus.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/JENKINS-53311.jenkinsfile
- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
- blueocean-pipeline-scm-api/src/main/resources/io/jenkins/blueocean/pipeline/credential/Messages_zh_CN.properties
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_zh_CN.properties
- blueocean-web/src/main/resources/jenkins/plugins/blueocean/web/Messages_zh.properties
- pom.xml
Backports these  commits from master over to 1.8 release branch:
* f04175838 [JENKINS-53311] Wrong status of running builds  (#1807)
* 60442a1ba [JENKINS-53132] Moves sleep into saveBranch, more consistent logging (#1803)
* 9944bb936 Update pipeline-related plugins to the latest versions (#1806)
* 7830bf12b Fix test URL overlap
* d3c9cbce7 Add a test
* 116c6baf1 Use StringBuilder for string concatenation
* 69161ff29 BitBucket Server errors not shown properly
* d520a7219 Surefire and jacoco plugins upgrade (#1804)
* 74f11929e avoid js error in case a run request returns a 404 (#1802)
* 39d3a5ee7 Fixes expression and supplement i10n (#1801)
* 6cda2f2e7 remove unsued accept header (#1800)
* 1a34a1c7b [JENKINS-53175] avoid 404 by returning an empty BlueTestSummary (#1799)
* 96a2bb2f9 Allows …
> Backport fixes to 1.8

- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java
There are some problems with the name check now, for example, I can create a job named `a/b`
> check good name

- blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/BlueJiraIssue.java
- blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListener.java
- blueocean-jira/src/test/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListenerTest.java
See [JENKINS-53320](https://issues.jenkins-ci.org/browse/JENKINS-53320).
This pr avoid duplicate keys in the jql query and do not fail the build in case of issue with the jira plugin.
> [JENKINS-53320] Job fails because JiraSCMListener times out on too many changes

- blueocean-dashboard/src/main/js/creation/bitbucket/api/BbCreationApi.js
When getting orgs from a bitbucket server, when there are more than 100 we need to get the next page to see if there are any more
See UX-844, [JENKINS-46730](https://issues.jenkins-ci.org/browse/JENKINS-46730).
> [JENKINS-46730] Add support for multiple pages when getting orgs (projects) from bitbucket

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
Example pipeline script here: https://gist.github.com/sophistifunk/717c9578af709e959f35d2d5bd6ab30b
Single-child sequential stage list, if the last branch of a parallel container, does not get correct graph edges applied.
See [JENKINS-53900](https://issues.jenkins-ci.org/browse/JENKINS-53900).
> JENKINS-53900 Missing stage graph nodes

- Jenkinsfile
Context: this PR is a separate and more focused followup on https://github.com/jenkinsci/blueocean-plugin/pull/1818 where we discussed reintroducing a `Jenkinsfile` to build both on https://ci.jenkins.io too.
This PR uses a hint from @jglick given in the PR linked above to have a single `Jenkinsfile` able to behave in both https://ci.jenkins.io and https://ci.blueocean.io
Goal is:
* Keep having the dogfooding build on https://ci.blueocean.io for obvious reasons
* Get also the benefit of incremental releases (aka JEP-305) for Blue Ocean from https://ci.jenkins.io without having to deploy another complex and redundant setup on https://ci.blueocean.io
See [JENKINS-54268](https://issues.jenkins-ci.org/browse/JENKINS-54268).
> [JENKINS-54268] Reenable building on ci.jenkins.io too

- Jenkinsfile
Followup of https://github.com/jenkinsci/blueocean-plugin/pull/1838
Tests are now configured to be skipped on https://ci.jenkins.io, since this build is only used for Incrementals, so let's save resources on ci.j.i.
Actual build *with* tests is still done on https://ci.blueocean.io
See [JENKINS-54268](https://issues.jenkins-ci.org/browse/JENKINS-54268).
This PR is expected to:
* succeed on http://ci.jenkins.io
* only build on Linux
* publish Blue Ocean plugins in Incrementals repository (https://repo.jenkins-ci.org/incrementals/)
> Disable building on Windows, and skip tests

- acceptance-tests/src/main/java/io/blueocean/ath/pages/classic/LoginPage.java
See [JENKINS-54410](https://issues.jenkins-ci.org/browse/JENKINS-54410).
A new login screen was introduced in Jenkins 2.128, via [JENKINS-50447](https://issues.jenkins-ci.org/browse/JENKINS-50447). The existing `LoginPage.login` is incompatible with this new screen - it's [looking for a `log in` button to click on](https://github.com/jenkinsci/blueocean-plugin/blob/d7aac46curl67a09907a4955fed366475110d6cc0e2/acceptance-tests/src/main/java/io/blueocean/ath/pages/classic/LoginPage.java#L27), but there  isn't one. It now says `Submit`.
This PR is a simple way of having both login screens work. We check for the presence of the "new style" button, and  if we find it, we click it. If we don't find it, we go on like we always have.
Old login screen:
New login screen:
To verify:
1. Start a …
> [JENKINS-54410] Modify LoginPage.login() to work with old and new login screens

- blueocean-events/src/main/java/io/jenkins/blueocean/events/PipelineEventListener.java
See [JENKINS-54889](https://issues.jenkins-ci.org/browse/JENKINS-54889).
> [JENKINS-54889] Avoid NPE with graphlistener (null check on value before adding to the map)

- acceptance-tests/pom.xml
- acceptance-tests/run.sh
- acceptance-tests/runner/runtime/pom.xml
See [SUREFIRE-1588](https://issues.apache.org/jira/browse/SUREFIRE-1588).
This is a (hopefully temporary) workaround for [SUREFIRE-1588](https://issues.apache.org/jira/browse/SUREFIRE-1588). What happens, in brief, is that when built on a Debian/Ubuntu based system, the build of Blue Ocean can fail in various ways. These changes represent a workaround for that, until the SUREFIRE-1588 fix propogates to the myriad docker containers and other build infra on which Blue Ocean gets tested and built.
> [SUREFIRE-1588] Workarounds for CI systems building Blue Ocean on Debian/Ubuntu

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
Syntactically, it is possible to have scripted parallel stages inside a declarative parallel stage. 
However, instead of marking failing stages as red, successful stages were marked as red.
See [JENKINS-50532](https://issues.jenkins-ci.org/browse/JENKINS-50532).
Reason was that the order in `nestedbranches` and `parallelBranchEndNodes` was different when reaching the second level of parallelism (inverted order). A second stack storing intermediately detected end nodes and putting them into the main stack after the corresponding branch start was detected helps to prevent that.
Additionally, with a new level of parallelism, new `parallelEnd` can be nested. Thus, `parallelEnds` has to become a stack.
In order to test this PR run the example pipeline from the ticket or the tests in Jenkins.
> [JENKINS-50532] Handle results for multi level parallelization

- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/credential/BlueOceanCredentialsProvider.java
- blueocean-pipeline-scm-api/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/credential/BlueOceanCredentialsProviderTest.java
See [JENKINS-53188](https://issues.jenkins-ci.org/browse/JENKINS-53188).
tl;dr - Users can exist, but deleted in security realm (example, LDAP user is deleted, but still exists in jenkins). Add exception handling to not let things break.
Was able to test this manually by deleting the user from the disk, but leaving it in users.xml
> Handle security realm saying user is not found

- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
Adds referrer and robots meta tags that will not send the referrer url so we don't send job/branch names to third parties.
Tested on Chrome, Firefox, IE and Edge.
See [JENKINS-56301](https://issues.jenkins-ci.org/browse/JENKINS-56301).
> [JENKINS-56301] add missing referrer and robots meta tags

- blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
- blueocean-dashboard/src/main/less/core.less
- blueocean-dashboard/src/test/js/data/runs/latestRuns.js
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImplTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/mulitpleScms.jenkinsfile
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetResource.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueChangeSetEntry.java
Add a commit count field to be able to figure out which repo/instance it is
See [JENKINS-53019](https://issues.jenkins-ci.org/browse/JENKINS-53019).
> JENKINS-53019 - Changes tab does not group changes for multiple SCM providers by SCM

- blueocean-executor-info-plugin/pom.xml
Release spit out:
```
[WARNING] Rule 5: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for io.jenkins.blueocean:blueocean-pipeline-api-impl:1.12.0-SNAPSHOT paths to dependency are:
+-io.jenkins.blueocean:blueocean-executor-info:1.12.0
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.12.0-SNAPSHOT
and
+-io.jenkins.blueocean:blueocean-executor-info:1.12.0
+-io.jenkins.blueocean:blueocean:1.12.0-SNAPSHOT
+-io.jenkins.blueocean:blueocean-pipeline-api-impl:1.12.0 (managed) <-- io.jenkins.blueocean:blueocean-pipeline-api-impl:1.12.0-SNAPSHOT
and
+-io.jenkins.blueocean:blueocean-executor-info:1.12.0
+-io.jenkins.blueocean:blueocean:1.12.0-SNAPSHOT …
```
> remove all the version requirements from blueocean-executor since its defined in the parent pom

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/GraphBuilderTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/JENKINS-56383.jenkinsfile
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/restartStage.jenkinsfile
Due to some shortcomings in our unit tests (and me not doing enough manual testing it seems) the fix for some edge cases where downstream links weren't showing broke rendering of (some) pipelines with parallel branches.
We rolled back the change as a hotfix (v 1.13.2) as the regression was a more egregious bug than the missing downstream links, but this patch builds on the original fix for 38339 to address the regression.
This patch includes a bunch of new regression tests that explicitly check every node and connection in the graphs, as well as checking for downstream actions where they should be. And a 3 line fix for the regression :) 
See [JENKINS-56383](https://issues.jenkins-ci.org/browse/JENKINS-56383).
See [JENKINS-38339](https://issues.jenkins-ci.org/browse/JENKINS-38339).
> Fix for JENKINS-56383 without rolling back fix for JENKINS-38339

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/FreeStylePipelineTest.java
See [JENKINS-51716](https://issues.jenkins-ci.org/browse/JENKINS-51716).
Super hard to test manually, since you need to have runs that have non numeric id. I believe jenkins has deprecated id, so most jobs will be null or a number.
If you can get that, then testing is just hitting any rest interface that returns the run. The front page will try and return the latest run for a job.
> [JENKINS-51716] Prevent non numeric run id from throwing exception when a run is actually found

- blueocean-dashboard/src/main/js/components/testing/TestService.js
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BlueTestResultContainerImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BlueTestResultContainerImplTest.java
Summary does it, frontend needs to do it too.
Also included ability to filter by age
See [JENKINS-46193](https://issues.jenkins-ci.org/browse/JENKINS-46193).
- [] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
> JENKINS-46193 - Add support for filtering out non regressed failures.

- .github/release-drafter.yml
Trying out release-drafter like https://github.com/jenkinsci/bitbucket-branch-source-plugin/releases has
It should be easier to maintain than using the wiki. I'll copy the release notes from the wiki over manually as a start to see if we like it.
> Enable release-drafter support

- acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
- acceptance-tests/runner/scripts/maven.sh
- blueocean-executor-info/package-lock.json
- blueocean-executor-info/package.json
- blueocean-executor-info/src/main/js/ExecutorInfoService.js
- blueocean/pom.xml
See [JENKINS-56773](https://issues.jenkins-ci.org/browse/JENKINS-56773).
> JENKINS-56773 - Disable Executor plugin by default, and throttle requests for the api for those that have it installed

- blueocean-core-js/src/js/services/ActivityService.js
- blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
- blueocean-dashboard/src/main/js/components/placeholder/PlaceholderDialog.jsx
- blueocean-dashboard/src/test/js/run-details-changes-spec.js
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/BlueRunChangesetPreloader.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/preload/BlueRunChangesetPreloaderTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImplTest.java
- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetContainerImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetResource.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueItemRun.java
- blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueRun.java
UI Element updated to use the preload/pager data
Left all previous data behind, but we should still delete all the
run.changeSet stuff
cc @stuartrowe 
See [JENKINS-55497](https://issues.jenkins-ci.org/browse/JENKINS-55497).
> JENKINS-55497 - Add ChangeSet information to its own unique container

- blueocean-rest/README.md
Signed-off-by: soulseen <sunzhu@yunify.com>
the api of get SCM repositories in an organization:
```
curl -v -u xxx:yyy http://localhost:8080/jenkins/blue/rest/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/?credentialId=github&pageSize=10&pageNumber=3
```
The json response in filed `item` missing `}`,like this:
```
"items" : [ {
"_class" : "io.jenkins.blueocean.blueocean_github_pipeline.GithubRepository",
"_links" : {
"self" : {
"_class" : "io.jenkins.blueocean.rest.hal.Link",
"href" : "/organizations/jenkins/scm/github/organizations/CloudBees-community/repositories/bees-cli-router-plugin/"
}
},
"defaultBranch" : "master",
"description" : "CloudBees SDK \"router:*\" plugin",
"name" : "bees-cli-router-plugin",
"permissions" : {
"admin" : false,
"push" : …
```
> Fix response json data of API get SCM repositories in an organization

- CODEOWNERS
Old and new maintainers:
@halkeye
@imeredith
@jenkinsci/blueocean-plugin-developers
@jennbriden
@kzantow
@NicuPascu
@olamy
@scherler
@sophistifunk
@vivek
What do you think?
> Swap code owners with the jenkinsci group so it matches who has access to the project

- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/RestartStageTest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
- blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java
blueocean
See [JENKINS-48035](https://issues.jenkins-ci.org/browse/JENKINS-48035).
> JENKINS-48035: Fix to register webhook after creating and saving pipeline

- pom.xml
Test dependency on sonar plugin 2.8 had transitive dependency on okhttp 2.6
that has known vulnerability. Upgrading sonar-plugin to 2.9 fixes this.
> Updated sonar-plugin version

- pom.xml
As reported in JENKINS-58684, sse-gateway 1.18 fixed mem leak but
introduced thread leak. Thread leak looks pretty severe so we are going
to revert sse-gateway to 1.17 while a new fix in sse-gateway is worked
at.
See [JENKINS-58684](https://issues.jenkins-ci.org/browse/JENKINS-58684).
> [JENKINS-58684] Revert sse-gateway to 1.17

- blueocean-dashboard/src/main/js/components/karaoke/components/InputStep.jsx
When confirming on the user input step, this error is thrown: `TypeError: error.responseBody is undefinedjenkins-js-extension.js:95465:21`.
This code should handle an error in the case that there is no `responseBody` in the `error` object.
> address error.responseBody is undefined

- README.md
Installing the project requires usage of JDK 1.8.
> Update README.md w/ note about installation on macOS

- pom.xml
See [JENKINS-58684](https://issues.jenkins-ci.org/browse/JENKINS-58684).
> [JENKINS-58684] use sse gateway 1.20

- blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
- blueocean-dashboard/src/main/js/components/RunMessageCell.jsx
- blueocean-dashboard/src/test/js/run-message-cell-spec.js
See [JENKINS-59131](https://issues.jenkins-ci.org/browse/JENKINS-59131).
This is mostly a bandaid (not sure if it should ever be possible for the `run` object to exist without a `causes` member) but similar checks are done in other places; e.g.
https://github.com/kevinushey/blueocean-plugin/blob/9819a3048d01a0f0979cb9d8346b4ad0145dc3c4/blueocean-dashboard/src/main/js/components/RunMessageCell.jsx#L31
so I believe it makes sense to validate that `run.causes` exists in these places as well.
> validate 'run.causes' is set before checking length

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/GraphBuilderTest.java
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/unionDifferentNodeIdsSameStructure.jenkinsfile
See [JENKINS-58085](https://issues.jenkins-ci.org/browse/JENKINS-58085)/[JENKINS-53816](https://issues.jenkins-ci.org/browse/JENKINS-53816) and some tickets linked from those.
This PR tweaks the fix for JENKINS-53816 added in #1961.
In some cases, when a build's flow graph changes from one build to the next (because the Pipeline was changed, or perhaps due to the result of a `when` condition or some dynamic Pipeline behavior in a Scripted Pipeline), but stays similar enough that Blue Ocean considers the overall graph structure the same, the node ID for one of the nodes in the current Pipeline would use the node ID for what Blue Ocean thought the corresponding node was in previous builds. If the node ID for that node was not actually the same in both builds, the new node would be shown as …
> [JENKINS-58085] Fix issue where stages are shown as waiting to start when they are running/completed

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
[JENKINS-59706](https://issues.jenkins-ci.org/browse/JENKINS-59706): #1212 introduced what seems to be a very dangerous loop (without any test or comment explaining why such a loop might be necessary), and #1947 does not seem to have sufficed to ameliorate its effects.
> [JENKINS-59706] PipelineRunImpl.getCommitUrl must not loop over historical builds

- jenkins-design-language/less/components/result-status.less
When viewing a long output, the header is not visible, making it hard to know what the command/step was that generated the output without a lot of scrolling. Also, scrolling is required to collapse the item.
This change makes the header stick to the top of the viewport, increasing usability. No unit tests are required for this CSS-only change.
> Ensure header is visible on scroll

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
Fix to show separate stages inside parallel block when using scripted pipeline.
Before change
After change
Create a scripted pipeline using the example similar to below and you should see separate stage buttons in the parallel section related to each stage instead of one monolithic one.
```
node() {
parallel(
'Internal': {
stage('Prep') {
echo "Prep internal"
}
stage('Run') {
echo "Run internal"
}
},
'Prod': {
stage('Prep') {
echo "Prep prod"
}
stage('Run') {
echo "Run prod"
}
}
)
}
```
possible related jira tickets:
- https://issues.jenkins-ci.org/browse/JENKINS-55438
- https://issues.jenkins-ci.org/browse/JENKINS-53162
- https://issues.jenkins-ci.org/browse/JENKINS-55438
> Display separate stages in scripted parallel pipelines

- blueocean/doc/BlueOcean.adoc
- blueocean/pom.xml
See [documentation as code blog post](https://jenkins.io/blog/2019/10/21/plugin-docs-on-github/).  No unit tests because this is purely a documentation change.
Manual test: Review the content in the new adoc file and compare it with the [original wiki page](https://wiki.jenkins.io/display/JENKINS/Blue+Ocean+Plugin).
> Move aggregator ('blueocean') docs into git repository

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-commons/pom.xml
- blueocean-config/pom.xml
- blueocean-dashboard/pom.xml
- blueocean-events/pom.xml
- blueocean-executor-info/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-i18n/pom.xml
- blueocean-jira/pom.xml
- blueocean-jwt/pom.xml
- blueocean-personalization/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-scm-api/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest/pom.xml
- blueocean-web/pom.xml
- blueocean/pom.xml
- docker/official/pom.xml
Changes the `document.url` field in each submodules' pom.xml to point to instead of `https://wiki.jenkins-ci.org/display/JENKINS/Blue+Ocean+Plugin`. This is the same URL as put into the aggregator by @MarkEWaite in [PR2040](https://github.com/jenkinsci/blueocean-plugin/pull/2040).
> Replace wiki URL with github URL in pom files

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/BlueOceanWebURLBuilderTest.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlMapperImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/BlueOceanWebURLBuilderTest.java
Avoid unecessary location roudtrips by adding a slash to all generated URLs
See [JENKINS-56392](https://issues.jenkins-ci.org/browse/JENKINS-56392).
> Jenkins 56392

- blueocean-jwt/pom.xml
- blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/SigningKeyProviderImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetResource.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueItemImpl.java
- pom.xml
With Java 8 or higher Joda Time can be replaced with java.time.
See [JENKINS-60218](https://issues.jenkins-ci.org/browse/JENKINS-60218).
Unclear how to test this. The fix replaces existing Joda Time code with the equivalent `java.time.*` code. Hereby the system's default time zone is used for formatting, as it was the case with Joda Time.
> Remove dependencies to joda-time

- Dockerfile.build
[Dockerfile.build still uses an http URL to access repo.maven.apache.org](https://github.com/jenkinsci/blueocean-plugin/blob/e3e4ddc5cb2f642efd774a7cc75dca52ef56a81b/Dockerfile.build#L41). This is no longer supported. So let's fix that.
> Change to https url for maven download

- CHANGELOG.md
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
- blueocean-pipeline-editor/src/main/js/EditorPage.jsx
This change fixes a bug where the pipeline editor ignores and therefore fails to load or save custom Jenkinsfile script paths. This is a fix to existing functionality so no new tests have been added.
See [JENKINS-50328](https://issues.jenkins-ci.org/browse/JENKINS-50328).
See [JENKINS-51066](https://issues.jenkins-ci.org/browse/JENKINS-51066).
> [JENKINS-50328] [JENKINS-51066] Fix bug where pipeline editor ignores custom Jenkinsfile script path.

- blueocean/pom.xml
See [JENKINS-60983](https://issues.jenkins-ci.org/browse/JENKINS-60983).
Add missing <tag> section in <scm> of blueocean/pom.xml.
No new unit/acceptance tests are required.
> [JENKINS-60983] Fix broken incremental deploys

- jenkins-design-language/README.md
- jenkins-design-language/pom.xml
Ass @NicuPascu explained to me, http://jenkinsci.github.io/jenkins-design-language/docs/ links the Jenkins Design Language 2 website. This site has nothing to do with the JDL implementation included in this repo, so it is better to just remove the link.
> Jenkins Design Language: Use GitHub as a source of plugin docs + Remove the confusing link to the JDL2 website

- blueocean-core-js/pom.xml
This plugin was skipped in https://github.com/jenkinsci/blueocean-plugin/pull/2044 -- this PR makes it consistent. @MarkEWaite 's suggestion https://github.com/jenkinsci/blueocean-plugin/pull/2044#issuecomment-579087326 is not implemented here.
> Use GitHub as the source of documentation

- README.md
Follow-up to https://github.com/jenkins-infra/jenkins.io/issues/3046 . There is no Blue Ocean roadmap anymore on the site
> README: remove reference to the Blue Ocean roadmap

- Jenkinsfile
The previous usage of the echo step was incorrect because the argument was not a string. It is generally better to throw errors instead of logging them and using `currentBuild.result` to set the result so that the stack trace of the error is displayed in the build log. The relevant code failed in [this PR build](https://ci.blueocean.io/job/blueocean/job/PR-2064/20/), here is an excerpt from the log:
```
java.lang.ClassCastException: org.jenkinsci.plugins.workflow.steps.EchoStep.message expects class java.lang.String but received class org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
```
We use `catchError` in the `finally` block so that exceptions thrown by that stage do not mask errors throw from the `try` block, which  are more likely to be the root cause of any problems.
> Improve Jenkinsfile error handling by removing unnecessary catch block

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
This change will stop the failure but also rolls back #2049 when using pipeline-multibranch-defaults
See [JENKINS-62063](https://issues.jenkins-ci.org/browse/JENKINS-62063).
> [JENKINS-62063] Fix failure when using pipeline-multibranch-defaults

- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/BlueOceanUrlAction/action.jelly
Theres no need, because the user wouldn't be viewing
the build page if they didn't have the required read permission.
See [JENKINS-46540](https://issues.jenkins-ci.org/browse/JENKINS-46540).
> Don't check read permission for sidebar link

- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/parallelStepsFromPost.jenkinsfile
- blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/stepsFromPost.jenkinsfile
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/TryBlueOceanMenuTest.java
This PR fixes three tests that are failing in the PCT when running against Jenkins 2.249:
* `TryBlueOceanMenuTest.testOpenBlueOcean`: Issue is that https://github.com/jenkinsci/jenkins/pull/4700 changed the styling of the sidebar links, and as a result the `class` attribute has a space at the end now (to make it easier to add a class under certain conditions).
* `PipelineNodeTest.submitInputPostBlock`: Underlying issue is [JENKINS-63516](https://issues.jenkins-ci.org/browse/JENKINS-63516). This test doesn't really have anything to do with password parameters specifically, so we just remove the password parameter from the test to fix the PCT failures.
* `PipelineNodeTest.submitInputPostBlockWithParallelStages`: Same as `PipelineNodeTest.submitInputPostBlock`.
> Fix PCT failures when running against Jenkins 2.249+

- blueocean-pipeline-scm-api/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/credential/BlueOceanCredentialsProviderTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/UserImplPermissionTest.java
Fixes one failure when run against jenkinsci/jenkins#4848. The other two fail in
```
java.lang.NullPointerException
at hudson.security.ACL.hasPermission(ACL.java:134)
at io.jenkins.blueocean.service.embedded.rest.UserImplPermissionTest$3.answer(UserImplPermissionTest.java:130)
at io.jenkins.blueocean.service.embedded.rest.UserImplPermissionTest$3.answer(UserImplPermissionTest.java:126)
```
which I do not think can be fixed without actually updating the `jenkins.version`, because you cannot mock
```java
public static @NonNull Authentication getAuthentication2()
```
without that dep, and `ACL.hasPermission(Permission)` is `final`.
> Trying to make mock tests pass against Spring Security

- blueocean-web/package-lock.json
- blueocean-web/package.json
- jquery-detached provides an outdated and insecure version of jQuery. It's removed from the project because it is insecure.
- There are other legacy uses of old versions of jquery but they are limited to the jenkins-design-language website. They were not touched.
> Remove unused jquery-detached js dependency

- blueocean/pom.xml
See [JENKINS-50885](https://issues.jenkins-ci.org/browse/JENKINS-50885).
Resurrecting https://github.com/jenkinsci/blueocean-plugin/pull/1719 now that [JENKINS-33843](https://issues.jenkins.io/browse/JENKINS-33843) has been fixed. Blue Ocean users may not be using Jira, so we should not force them to install the `blueocean-jira` and `jira` plugins just to be able to use Blue Ocean.
Opening a draft PR for now to check if any ATH tests fail with this change.
> [JENKINS-50885] Make blueocean-jira plugin optional

- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/BrowserAndOperatingSystemAnalyticsProperties.java
- pom.xml
`ua_parser:ua-parser` has been replaced by `com.github.ua-parser:uap-java`
More info here - https://github.com/tobie/ua-parser/
The library at older coordinates was never published to Maven Central.
The new one exists on Maven Central.
> Upgrade UA Parser Library

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- blueocean-pipeline-editor/pom.xml
- blueocean-pipeline-editor/src/test/java/io/blueocean/rest/pipeline/editor/PipelineMetadataServiceTest.java
- blueocean-rest-impl/pom.xml
- blueocean/pom.xml
- pom.xml
See [JENKINS-58732](https://issues.jenkins-ci.org/browse/JENKINS-58732). Amends #2056 by @Vlatombe to pick up https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/393 via https://github.com/jenkinsci/bom/pull/415, which in turn requires switching to a somewhat more recent LTS baseline (2.176.x → 2.222.x). While I am here, using the BOM more consistently.
> [JENKINS-58732] Remove docker-workflow dep from blueocean-pipeline-editor

- acceptance-tests/pom.xml
- acceptance-tests/runner/runtime/pom.xml
- acceptance-tests/src/test/java/io/blueocean/ath/offline/pipeline/DownstreamLinkTest.java
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/pipeline/DownstreamLinkTest/downstreamJobLinkAppearsInRunResult.upstream.groovy
- acceptance-tests/src/test/resources/io/blueocean/ath/offline/pipeline/DownstreamLinkTest/sequentialStages.upstream.groovy
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/listeners/DownstreamJobListener.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
- pom.xml
- [JENKINS-60995] Fix downstream build link
- Update to use pipeline-build-step 2.14-rc430.69345dedbb03
See [JENKINS-60995](https://issues.jenkins-ci.org/browse/JENKINS-60995).
> Backport of PR 2187 in branch 1.24.x

- blueocean-core-js/pom.xml
- blueocean-jira/src/main/resources/index.jelly
- jenkins-design-language/pom.xml
See [JENKINS-68300](https://issues.jenkins-ci.org/browse/JENKINS-68300). This adds missing description for Jira plugin and makes sure description is exported for JDL and core-js plugins.
To verify you can compile all plugins, `index.jelly` should appear in the root of the .jar file.
- [n/a] Appropriate unit or acceptance tests or explanation to why this change has no tests
> Add description for plugin manager

- blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
Better handling of key presses when doing autoscrolling.
Disable autoscroll for additional keys (Home, Page Up).
Enable autoscroll in case End is pressed.
Disable autoscroll in case of an error in step (unable to scroll ... every couple of seconds it is scrolled to bottom).
See [JENKINS-41488](https://issues.jenkins-ci.org/browse/JENKINS-41488).
> [JENKINS-41488] Better handling of scrolling

- blueocean-pipeline-api-impl/pom.xml
- blueocean-rest-impl/pom.xml
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/AbstractAnalytics.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/AnalyticsTest.java
- pom.xml
As of https://github.com/jenkinsci/jenkins/pull/6585 using `instance-identity` requires a plugin dep, which would mean a newer core baseline. However it seems pretty superfluous here as it is apparently only used to identify the Jenkins instance—which actually is normally done via `Jenkins.get().getLegacyInstanceId()`—to some sort of analytics introduced in #1202 and expanded in #1502. Since this project is moribund I doubt anyone is actually looking at these analytics and the whole thing should likely be ripped out.
> Removing `instance-identity` dependency

- README.md
- blueocean/doc/BlueOcean.adoc
jenkins-infra/jenkins.io#5288 added a useful statement to the documentation site, but it neglected to add the new statement to the plugin site and the GitHub landing page, both of which are significant places for such a statement to be displayed.
As @oleg-nenashev would say, "bonus points" for adding this important statement to other significant places:
- https://www.jenkins.io/projects/blueocean/
- https://hub.docker.com/r/jenkinsci/blueocean/
Note that I am explicitly not volunteering to add the statement to either of those two places.
@halkeye
@kmartens27
@markewaite
> Adding Blue Ocean statement

- blueocean-dashboard/src/main/js/components/RunDetailsTests.jsx
This bug was introduced in [JENKINS-47929](https://issues.jenkins-ci.org/browse/JENKINS-47929).
https://github.com/jenkinsci/blueocean-plugin/pull/2050/files#diff-783146f6c8f9ef19650a1bed48fa2e790ffac355579651682c728c1e572141aaR60
The "Tests" tab is not showing the number of test that failed. This PR fixes that bug caused by missing parentheses breaking the logic to calculate the number.
- [X ] Link to JIRA ticket in description, if appropriate.
- [ X] Change is code complete and matches issue description
- [X ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ X] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
> Fix missing parentheses causing logic bug for tests tab failure count

- acceptance-tests/runner/runtime/src/main/java/io/jenkins/blueocean/BlueOceanWinstoneController.java
AJP support was removed in Jetty 9 and Winstone 3.0 in https://github.com/jenkinsci/winstone/pull/22, never to return. As a result it is pointless to keep setting this option.
> Remove usage of `--ajp13Port` in ATH tests

- blueocean-core-js/src/js/index.ts
- blueocean-core-js/src/js/utils/ComponentLink.js
- blueocean-dashboard/src/main/js/PipelineRoutes.jsx
- blueocean-dashboard/src/main/js/components/RunDetails.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsArtifacts.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
- blueocean-dashboard/src/main/js/components/RunDetailsTests.jsx
- blueocean-dashboard/src/main/js/components/index.jsx
- blueocean-dashboard/src/main/js/jenkins-js-extension.yaml
- blueocean-dashboard/src/main/js/util/ComponentLink.js
- blueocean-dashboard/src/test/js/run-details-artifacts-spec.js
- blueocean-dashboard/src/test/js/run-details-changes-spec.js
See [JENKINS-47929](https://issues.jenkins-ci.org/browse/JENKINS-47929).
Fixing issues reported after https://github.com/jenkinsci/blueocean-plugin/pull/2268 was merged.
**Unit/Acceptance Tests**
Added additional test for `RunDetailsArtifacts` component in `run-details-artifacts-spec.js`.
> [JENKINS-47929] Extensible run details tabs

- pom.xml
Justifies an increment of the minor version number
Earlier changes are bug fixes, but users will perceive it as more than a bug fix
See [JENKINS-70379](https://issues.jenkins-ci.org/browse/JENKINS-70379) for the original motivation to require Java 11 and Jenkins 2.361.4.  The git client plugin 4.0.0 change from Java 8 to Java 11 brought a change from JGit 5.13.1 to JGit 6.4.0.  The JGit change included a breaking change in the location of one or more JGit classes.
No tests because this is proposing a larger version number for clarity to users rather than due to the size or impact of a change.
Related to:
* #2379
> Require Jenkins 2.361.4 and Java 11

- blueocean-git-pipeline/pom.xml
- pom.xml
See [JENKINS-70559](https://issues.jenkins-ci.org/browse/JENKINS-70559) where it reports a class not found exception when using the Blue Ocean Pipeline editor to create a new Pipeline.
The JGit project delivers org.eclipse.jgit.ssh.apache in addition to the org.eclipse.jgit.ssh.jsch library. The org.eclipse.jgit.ssh.apache library appears to be a complete replacement for git client plugin use cases. The JGIt project has declared their jsch library is deprecated and may be removed at any time.
[JENKINS-69159](https://issues.jenkins.io/browse/JENKINS-69159) describes the transition the git client plugin has made from the unmaintained Jsch library to the Apache Mina SSHD library.
[Future of Jsch](https://www.matez.de/index.php/2020/06/22/the-future-of-jsch-without-ssh-rsa/) notes that Jsch …
> [JENKINS-70559] Fix class cast exception in ssh Pipeline editor

- blueocean-github-pipeline/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/FlowNodeWrapper.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeContainerImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepContainerImpl.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
add some caching to avoid expensive call for completed run
> the method is called twice for the same object so at least we can store the result in a field which reduce call by 2 :) (#2408)

- pom.xml
Forgotten in jenkinsci/jenkins#4460 & jenkinsci/jenkins#5720.
> Remove unused `hudson.udp` property

- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
* [JENKINS-70808] Fix isRestartable by only checking against the current node
* [JENKINS-70808] Handle restartable computation in constructor
> [JENKINS-70808] Fix isRestartable by only checking against the curren… (#2416)

- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-editor/pom.xml
- pom.xml
This is needed for the forthcoming PCT multi-module mode to pull in the fix for [JENKINS-62658](https://issues.jenkins.io/browse/JENKINS-62658) via https://github.com/jenkinsci/maven-hpi-plugin/pull/453. I tested this successfully with the latest update to the multimodule project branch of PCT, which is now doing `mvn process test-classes` rather than `mvn install`, therefore requiring the fix for [JENKINS-62658](https://issues.jenkins.io/browse/JENKINS-62658). With these changes you can now successfully run `mvn process-test-classes` in the root directory of the repository, which was not possible with the old version of Maven HPI plugin.
To test this PR I ran:
```
$ git checkout blueocean-parent-1.27.3
$ git clean -fxd
$ mvn clean process-test-classes  # failed before, passes now
$ mvn …
```
> Upgrade plugin parent POM from 4.53 to 4.57

- blueocean-events/pom.xml
- blueocean-git-pipeline/pom.xml
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/CloneProgressMonitor.java
- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveTest.java
- blueocean-pipeline-api-impl/pom.xml
- blueocean-rest-impl/pom.xml
- pom.xml
Otherwise you get constant errors like
```
java.lang.NoSuchMethodError: 'void com.github.benmanes.caffeine.cache.LoadingCache.refresh(java.lang.Object)'
at io.jenkins.blueocean.rest.impl.pipeline.Caches$ListenerImpl.onUpdated(Caches.java:70)
```
Caused by https://github.com/ben-manes/caffeine/issues/143 as noted in https://github.com/ben-manes/caffeine/issues/543#issuecomment-826987183 and picked up from https://github.com/jenkinsci/caffeine-api-plugin/pull/79. Source-compatible but binary-incompatible, so suffices to rebuild against 3.x.
> Bump BOM and explicitly depend on `caffeine-api` to fix `LoadingCache.refresh`

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlObjectImpl.java
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages.properties
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_ko.properties
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_ru.properties
- blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_zh_CN.properties
When clicking on "Open Blue Ocean" sometimes the click is useful, for example taking me to a page where I can see the progress of my current build. Other times it is useless, for example when I click on "Open Blue Ocean" on a job page. This change allows the user to know before they click whether they'll be taken to a helpful related page or to a generic Blue Ocean home page.
See [JENKINS-71418](https://issues.jenkins-ci.org/browse/JENKINS-71418).
No new tests because I'm not sure how to set up or mock the required build in order to test this.
Manual testing:
* Vew the link on a generic Jenkins page such as http://jenkinsserver/ and check it says "Open Blue Ocean Homepage"
* View the link on a specific numbered Jenkins build page such as http://jenkinsserver/job/foldername/job/jobname/1/ …
> Allow the user to know if their click will be useful

- .mvn/extensions.xml
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubMockBase.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrgFolderPermissionsTest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
- pom.xml
I observed some of these tests flaking in `TemporaryDirectoryAllocator`, presumably due to a race with indexing. To avoid this flakiness I have adopted the idiom from `branch-api` of waiting for indexing to finish before starting test teardown.
> Upgrade plugin parent POM from 4.57 to 4.65

- blueocean-rest-impl/src/main/webapp/scripts/analytics.js
Followed [the migration guide](https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/).
- "Enable analytics" by commenting out the `<if>` statement in `action.jelly`
- Step through Prototype code in the debugger, verify it is successfully making a POST request
- Enable the user experimental flag to remove Prototype
- Step through Prototype code in the debugger, verify it is now failing due to Prototype being removed
- Make the change from this PR, verify the code is working again and the POST request is made successfully without any errors in the console log
> Remove usages of Prototype.js

- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeUtil.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
- pom.xml
Downstream of https://github.com/jenkinsci/jenkins/pull/7599 & https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/287.
> Use `SubTask.getOwnerExecutable`

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/BlueTrendTest.java
When attempting to add Blue Ocean to `jenkinsci/bom` I discovered this test started failing with the list being of size 3 rather than the expected size 2. Peeking at the contents I see
```
io.jenkins.blueocean.rest.impl.pipeline.StageDurationTrend$FactoryImpl@7e9c962a
io.jenkins.blueocean.service.embedded.rest.junit.BlueJUnitTrend$FactoryImpl@36b5b88a
io.jenkins.blueocean.service.embedded.rest.BlueTrendTest$1@5584dbb
```
whereas when the test is executed outside of PCT only the last two entries are present. This is to be expected, since PCT places all the plugins in the managed set in the class path. To deal with this issue I have made the test tolerate this situation by checking for a size greater than or equal to 2.
> Tolerate testing in PCT context

- pom.xml
since a while ago the default to surefire rerun tests was set to zero so it is not needed.
Additionally things pass `-DforkCount` not `-Dconcurrency` for a while too.
> remove obsolete config

- blueocean-bitbucket-pipeline/pom.xml
- blueocean-github-pipeline/pom.xml
- blueocean-rest-impl/pom.xml
- pom.xml
See [JENKINS-71803](https://issues.jenkins.io/browse/JENKINS-71803). Fixes the issue by using the Mockito version from the plugin parent POM (version 5, which supports Java 21) rather than defining an outdated version in this repository.
> [JENKINS-71803] Blue Ocean tests fail on Java 21 with Mockito errors

- blueocean-commons/pom.xml
- pom.xml
No need for this plugin to carry its own custom (and out of date) version.
> Use JaCoCo version from plugin parent POM

- .mvn/extensions.xml
- .mvn/maven.config
- Jenkinsfile
- acceptance-tests/pom.xml
- acceptance-tests/run.sh
- acceptance-tests/runner/runtime/pom.xml
- acceptance-tests/runner/scripts/args.sh
- acceptance-tests/src/main/java/io/blueocean/ath/ATHJUnitRunner.java
- acceptance-tests/src/main/java/io/blueocean/ath/SmartWebElement.java
- acceptance-tests/src/main/java/io/blueocean/ath/WaitUtil.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/ActivityPage.java
- acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/FolderTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/TestDetailsTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/CommitMessagesTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/TestResultsErrorStdOutTest.java
- acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesCardsTest.java
- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
- pom.xml
> Fix some failing ATH tests, increase some timeout to avoid flakyness of some tests

- blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
Saw an apparent flake in PCT introduced by diagnostic code in #2468
```
java.io.FileNotFoundException: …/blueocean-github-pipeline/target/tmp/j h7435154302361148419/jobs/p/computation/computation.log (No such file or directory)
at java.base/java.io.RandomAccessFile.open0(Native Method)
at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
at org.kohsuke.stapler.framework.io.LargeText$FileSession.<init>(LargeText.java:411)
at org.kohsuke.stapler.framework.io.LargeText$2.open(LargeText.java:126)
at org.kohsuke.stapler.framework.io.LargeText.writeLogTo(LargeText.java:225)
at hudson.console.AnnotatedLargeText.writeLogTo(AnnotatedLargeTe …
```
> Ignore `IOException` from `writeLogTo`

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
- Skip flaky multiBranchPipelineIndex test
- Do not exit test until no activity
https://github.com/jenkinsci/bom/runs/16996428210 shows the failure happened in 2 of the 4 configurations that are tested by the plugin bill of materials.
This pull request offers two different alternatives to resolve the issue.
1. Stop running the test (most likely to resolve the issue, but will hide failures that the test might have detected)
2. Wait for Jenkins to be quiet before exiting the test (may not prevent all test failures)
I'm open to either change and am happy to modify this pull request to include which ever is preferred by @olamy and the other maintainers of the plugin.
We like having the blueocean plugin in the Jenkins plugin bill of materials so that we can detect issues more quickly.
> Prevent multiBranchPipelineIndex failure due to DirectoryNotEmptyException

- Jenkinsfile
Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
The change adds a Java 21 test on ci.jenkins.io.  It does not change the other CI configurations.
> Add Java 21 build for https://ci.jenkins.io/

- blueocean-i18n/src/main/java/io/jenkins/blueocean/i18n/BlueI18n.java
Similar fix to https://github.com/jenkinsci/jenkins/pull/8776
See [JENKINS-72467](https://issues.jenkins-ci.org/browse/JENKINS-72467).
This ensures that the blueocean pages are displayed in the language requested by the browser, and not falling back to the default JVM locale when requesting english.
Verified manually that with this change, a JVM with `-Duser.language=fr`, and a browser configured for english only, the BlueOcean page is displayed in english only. When adding the french language to the browser, the page is then translated to french as expected (at least for the translated strings part of Blue Ocean).
Could not add a unit test to verify the behaviour as I'm not familiar with how BlueOcean deals with resource bundles and there was no existing bundle part of `blueocean-i18n` …
> [JENKINS-72467] Fix localization

- blueocean-dashboard/src/main/js/components/RunDetails.jsx
This is a simple one-line fix for the reported issue. This is a reopen of https://github.com/jenkinsci/blueocean-plugin/pull/2535 due to a technical error in the pipeline.
See [JENKINS-70421](https://issues.jenkins-ci.org/browse/JENKINS-70421).
- [ X ] Link to JIRA ticket in description, if appropriate.
- [ X ] Change is code complete and matches issue description
- [ X ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ X ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
> JENKINS-70421 Add missing test result badges to menu item

- blueocean-core-js/src/js/parameter/index.js
Add support for 'GitParameterDefinition' (Git plugin) in Blue Ocean. This allows one to start pipelines that take parameters like a git branch that's exposed from the Jenkins Git plugin.
> chore: Add support for 'GitParameterDefinition' (Git plugin) in Blue Ocean

- pom.xml
This isn't managed in BOM, and we're currently depending on an out-of-date version. The update to `maven-artifact` is to satisfy a require upper bounds error.
> Upgrade Jira plugin 3.12

- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
Would I think fix https://github.com/jenkinsci/bom/issues/2916. You can see
```
WARNING: pipeline1 #3 still seems to be running, which could break deletion of log files or metadata in the log
```
which is a good clue that the test is broken. Indeed the test times out reproducibly after
```diff
diff --git blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
index 6151d3a30..78c900448 100644
--- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
+++ blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
@@ -548,6 +548,7 @@ public class PipelineApiTest extends BaseTest { …
```
> Deflake `PipelineApiTest.testPipelineQueue`

- blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineApiTest.java
Needs release please @olamy. CloudBees-internal references: BEE-40514, BEE-41507, BEE-43058
> Fixing some test flakes

- blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
Any of the events which trigger debounceFetchNodes should call fetchNodes[Only] with the current props node specified. This prevents a pipeline view from jumping to the first still-running parallel stage when any non-first stage is focused and a handled non-pipeline_step event is received.
Removed unnecessary fetchNodesOnly parameter.
Test:
For a running job with parallel stages with multiple steps that emits non-pipeline_step events currently running:
Click to focus on a running step *below* the first still-running step at the top of the pipeline.
Wait for a pipeline_{end,start,block_end,stage} or job_run_ended event to be received.
Without this change, the log/steps view will switch to a view which includes all of the steps of the topmost still-running step (different from focusing on …
> Prevent debounceFetchNodes from jumping node view

- blueocean-git-pipeline/pom.xml
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtils.java
- pom.xml
> Prepare for coming release of git-client using Apache Mina, adapt hackhish code

- blueocean-pipeline-api-impl/pom.xml
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MatrixProjectImpl.java
- blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/analytics/MatrixAnalyticsCheck.java
https://github.com/jenkinsci/blueocean-plugin/pull/412#discussion_r1680122787 https://github.com/jenkinsci/htmlpublisher-plugin/pull/287#issuecomment-2231902209 https://github.com/jenkinsci/bom/pull/3382
Tested with:
```diff
diff --git pom.xml pom.xml
index c9a84f7b6..13a6d5bff 100644
--- pom.xml
+++ pom.xml
@@ -358,6 +358,11 @@
</dependency>
+        <dependency>
+                <groupId>org.jenkins-ci.plugins</groupId>
+                <artifactId>htmlpublisher</artifactId>
+                <version>1.36</version>
+        </dependency>
<dependency>
<groupId>io.jenkins.blueocean.rest.annotation</groupId>
<artifactId>capability-annotation</artifactId>
```
> Explicit dep on `matrix-project`

- blueocean-rest-impl/src/main/webapp/scripts/analytics.js
Now that Prototype.js has been removed in 2.426.x, we can remove the no-longer needed `Object.toJSON` workaround. This plugin's baseline is 2.426.3, so this change is safe.
`mvn clean verify -DskipTests`
> Simplify JSON parsing

- acceptance-tests/src/main/java/io/blueocean/ath/GitRepositoryRule.java
- acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
This PR updates the logging statement in the parallelPipeline method to accurately reflect the action being performed. The previous log message indicated that a parallel pipeline was being “edited,” while the surrounding code clearly shows that a new parallel pipeline is being created from scratch.
The original log statement was misleading, suggesting that an existing pipeline was being modified rather than a new one being created. This could cause confusion for developers and maintainers when reviewing logs. The new log statement more accurately describes the process of creating a new parallel pipeline, thus improving the clarity and accuracy of the code’s documentation through logs.
Verified that the method performs as expected and that the new logging message appears correctly in the …
> Fix misleading in logging statement in parallelPipeline Method

- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtils.java
See [JENKINS-73775](https://issues.jenkins.io/browse/JENKINS-73775)
JGit 5 deprecated the `DirCacheEntry.setLastModified(long)` method and recommends `DirCacheEntry.setLastModified(Instant)`.  JGit 7.0.0 removes DirCacheEntry.setLastModified(long).  This change will work with older versions of JGit (like 6.9.0 and 6.10.0) and JGit 7.0.0 because the replacement method is available with older versions and the most recent release.
[Javadoc for JGit 6.9.0](https://javadoc.io/doc/org.eclipse.jgit/org.eclipse.jgit/6.9.0.202403050737-r/org.eclipse.jgit/org/eclipse/jgit/dircache/DirCacheEntry.html) shows the deprecation.
Without this change, users that try to run a commit from the Git portion of Blue Ocean may see a method not found exception that will fail the operation.
No additional tests …
> [JENKINS-73775] Replace deprecated call to JGit setLastModified(long)

- blueocean-git-pipeline/pom.xml
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtils.java
See [JENKINS-73775](https://issues.jenkins.io/browse/JENKINS-73775)
JGit 7.0.0 removed the setEncoding(String) method that had been deprecated previously.  The replacement is setEncoding(Charset).  The JGit documentation recommends commit.setEncoding(StandardCharsets.UTF_8)
Failure was hidden by the previous setLastModified() exception because this call happens later in the same calling sequence.
Exclude org.eclipse.jgit from transitive inclusion in the git-pipeline plugin
The org.eclipse.jgit jar file is already provided by the git client plugin.  Let's not risk that a 6.9.0 copy of the library is loaded into the same Java process that is running either JGit 6.10.0 (with git client plugin 5.0.0) or JGit 7.0.0 with git client plugin 6.0.0)
Confirmed that the steps that show the error in …
> [JENKINS-73775] Replace call to removed CommitBuilder.setEncoding(String)

- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
- blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/loadbar.js
See [JENKINS-74010](https://issues.jenkins.io/browse/JENKINS-74010).
https://github.com/jenkinsci/blueocean-plugin/blob/be4d0c94be0b384fde660278cf173f28e369ea2c/blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly#L71-L75
https://www.jenkins.io/doc/developer/security/csp/#inline-javascript-blocks
Tested together with #2588 and
```xml
diff --git a/blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly b/blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
index dc61f3c0d..3d75385e7 100644
--- a/blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
+++ b/blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
@@ -1,6 +1,7 @@
<?jelly escape-by-default='true'?>
<j:jelly …
```
> [JENKINS-74010] Extract JavaScript block in `BlueOceanUI/index.jelly`

- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/preload/FavoriteListStatePreloaderTest.java
- blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/preload/StatePreloaderTest.java
- blueocean-web/src/main/resources/io/jenkins/blueocean/PageStatePreloadDecorator/header.jelly
- blueocean-web/src/main/resources/io/jenkins/blueocean/PageStatePreloadDecorator/preloader.js
See [JENKINS-74011](https://issues.jenkins.io/browse/JENKINS-74011).
https://github.com/jenkinsci/blueocean-plugin/blob/be4d0c94be0b384fde660278cf173f28e369ea2c/blueocean-web/src/main/resources/io/jenkins/blueocean/PageStatePreloadDecorator/header.jelly#L3-L41
https://www.jenkins.io/doc/developer/security/csp/#inline-javascript-blocks
Follow the general strategy used in JUnit and Theme Manager plugins. Since this data is complex JSON, do not use data attributes in HTML, but rather put the JSON in a `<script>` of type `application/json`. Then parse that JSON (without using `eval`!) to get the data into memory in a CSP-compliant fashion.
Tested together with #2587 and
```xml
diff --git a/blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly …
```
> [JENKINS-74011] Extract JavaScript block in `PageStatePreloadDecorator/header.jelly`

- blueocean-core-js/package-lock.json
- blueocean-core-js/package.json
See [JENKINS-74883](https://issues.jenkins.io/browse/JENKINS-74883).
```
EvalError: call to Function() blocked by CSP
optimizeLookup https://127.0.0.1/adjuncts/f72d66ff/io/jenkins/blueocean/blueocean-core-js.js:48503
[223]</< https://127.0.0.1/adjuncts/f72d66ff/io/jenkins/blueocean/blueocean-core-js.js:48507
[223]< https://127.0.0.1/adjuncts/f72d66ff/io/jenkins/blueocean/blueocean-core-js.js:49728
o https://127.0.0.1/adjuncts/f72d66ff/io/jenkins/blueocean/blueocean-core-js.js:1
o https://127.0.0.1/adjuncts/f72d66ff/io/jenkins/blueocean/blueocean-core-js.js:1
[222]< https://127.0.0.1/adjuncts/f72d66ff/io/jenkins/blueocean/blueocean-core-js.js:48330
o https://127.0.0.1/adjuncts/f72d66ff/io/jenkins/blueocean/blueocean-core-js.js:1
o …
```
> [JENKINS-74883] Remove unsafe `eval` call from third-party library

- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanRootAction.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
- blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/UserImplPermissionTest.java
See [JENKINS-75768](https://issues.jenkins.io/browse/JENKINS-75768). https://github.com/jenkinsci/github-oauth-plugin/blob/f5ddfba7349dac0eec130482ca98b6ab236f0c49/src/main/java/org/jenkinsci/plugins/GithubRequireOrganizationMembershipACL.java#L84 means that `github-oauth` is limited to working in two configurations:
- Caller (Blue Ocean) is using Acegi, and callee (`github-oauth`) is also using Acegi
- Caller (Blue Ocean) is using Spring Security, and callee (`github-oauth`) is also using Spring Security
Prior to https://github.com/jenkinsci/github-oauth-plugin/pull/285, the former was the case. After https://github.com/jenkinsci/github-oauth-plugin/pull/285, the caller (Blue Ocean) is using Acegi, but the callee (`github-oauth`) is using Spring Security; hence, the `instanceof` check …
> [JENKINS-75768] Blue Ocean Fails to Load with GitHub Auth: 403 Forbidden on PUT Request

- Jenkinsfile
- blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtils.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
- blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
- pom.xml
Prepare for Java 25
Java 25 will release Sep 16, 2025 and the Jenkins project plans to support it soon after its release.  This upodate to the most recent parent pom successfully compiles and tests with Java 25 early access 26, when combined with the removal of a few spotbugs suppressions that are no longer necessary.
Switches the Jenkinsfile to test Java 25 and Java 21 instead of testing Java 17 and Java 21.  Generated byte code is still Java 17, but I'm not aware of any case where Java 17 exposed an issue that was not also seen with Java 21.
> Prepare for Java 25

- blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-pipeline-demo-test-branches-all.json
- blueocean-git-pipeline/pom.xml
- blueocean-pipeline-api-impl/pom.xml
- pom.xml
Use a pattern match in Bitbucket Wiremock test definition so that automated tests pass with previous and latest versions of Bitbucket Branch Source plugin.  Special thanks to @nfalco79 for investigation and the original submission in pull request:
* #2653
Bitbucket branch source 936.x and 937.x use different initial URLs.  Check for either and pass the test if one or the other is used.
Change included in Bitbucket branch source 937.0.0 pull request:
* https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/1060
Originally detected in:
* https://github.com/jenkinsci/bom/pull/5669
Plugin BOM blocked 937.0.3 upgrades in:
* https://github.com/jenkinsci/bom/pull/5693
While waiting for the release of this merge request, the test failure will be blocked in the plugin BOM.
Confirmed that …
> Use a pattern match in Bitbucket Wiremock test definition
